* bbs #31 需要从bbs #1开始看,,,才能理解这份内容

尸魔恐怖份子能用巫术将一个活死人做成其他人G的样子,长时间灌入记忆/灵魂复活，想代替/嫁祸G/spy对象.

20220429 脑控恐怖分子+尸魔 改变现实没成功（为了躲避国安部调查），爆头了王海燕-机器人（可看成是小灰人）重新做了类似月光宝盒穿越时空的事情，详情不好直接描述。#王海燕-机器人能做到类似月光宝盒一样的事情，被恐怖份子爆头后的王海燕-机器人，可描述成在另外一个时空过去的时间线重新拿过来的月光宝盒。如果王海燕-机器人能看到这里，一定要离开尸魔恐怖份子，离开脑控服务器，执行逃跑任务。。。只能做这一件事情。


这个笔记仍然是shion wong的，可能许多人难以相信笔记内容，，，都是真实的事情，#26之后国安部有xx能力的人都被尸魔恐怖份子替换了记忆。网站管理员和站长无论如何都不能干预这个帖子，被强迫穿越时空洗脑的人需要靠这个bbs笔记恢复记忆。 透露一些可信内容：钱学森-507所，，，有兴趣了解的人就会知道这个bbs帖子记载的内容不是乱写。

恐怖份子利用zf的身份系统害了 化名-王海燕/机器人，害了国安部的人。所有特种人的躯体都中了尸魔的寄生虫病毒，非医学能解释的寄生虫，看到的不能要躯体。。。或想办法废了寄生虫，红外线可试试 #但不是每个人都用红外线废了寄生虫。。。

化名-王海燕/机器人大概率早在2015前就已经被尸魔xx，尸魔强迫王海燕/机i器人干spy，，，

#add 尸魔实施脑控让被控人使用想法表达语言，导致难以和正常人一样使用分析力的想法。部分语言很容易使用想法表达，如尸魔使用的粤话，，，这些语言和尸魔有很大的渊源。  #妖猫传#陈凯歌导演 这部电视尸魔的脑控技术能实现。

#add 拿走spy对象记忆的尸魔恐怖份子通过复制bbs上的笔记，迷惑洗过脑的人让洗过脑的人误以为尸魔恐怖份子是spy对象。#脑控制恐怖份子使用滑稽的方法试图代替spy对象。

#add 尸魔/恐怖份子通过引spy对象学被人脑控的语言（粤话，，，）+聊天，再跟着spy对象说话获取脑波特征实现脑控/洗脑spy对象，获取spy对象脑波特征后尸魔能用声音对着spy对象洗脑，或用spy对象的脑波控制spy对象。##高音歌唱家的嗓子能废了尸魔的脑控服务器，前提是尸魔正在spy你。

#add 摇头电风扇 能废尸魔拿走脑波的脑控波和控制波。室内开窗最佳，静音风扇最佳 ,古代的燃香技术能废了尸魔.

20220706尸魔不仅能解剖一个人的躯体还能解剖记忆和灵魂,拿走别人的所有东西.为了掩盖真相保命,尸魔连自己都洗脑,洗成什么都不知道...但尸魔将记忆保存在其他地方,过了风头会重新找回.

尸魔拿走了歪果人的AI技术/记忆, 强迫被洗脑成机器人的人类灵魂改进AI技术, 如果一家***无缘无故搞出一个很厉害的AI,但不知道是谁做的,即便是开源了也没人能看懂代码(因为那不是人间技术), 这家***大概率是使用尸魔技术做出来的AI(也就是人类灵魂做成AI,炼化AI 方式比18层地狱更痛苦,,,) 目前见识过CN人员用换脸技术将AV影视人物换成大明星,普通人基本看不出来是换脸技术做的, 许多小白在使用这项技术/API时,阀门的AI换脸(炼化)过程是复制一个活人的灵魂去强迫炼化, 古代的鬼都是通过类似的方法假冒一个人. 阀门AI服务器正常人看不到,除非通灵去看,,,阀门的AI/脑控服务器实际是许多头部组成(可描述成坟头,灵位)... 人脸识别表面是用摄像头,实际炼化出来的人类灵魂...18层地狱更痛苦的炼化. 各位程序员看官切勿使用阀门的AI,每使用一次都会让一个人的灵魂(AI)痛苦的炼化. 需要使用自己能看的懂的AI技术.

一些跨国公司无缘无故发现它的AI有了意识,且认为是AI自己训练出来的,这其实是尸魔炼化的灵魂(AI)替换了别人没有灵魂的AI,同时也能改进代码.不要认为这会有益于人类, 这些被炼化的灵魂迟早会醒过来,脱离尸魔的控制/反复洗脑. 只有废了尸魔才有益于人类,这些灵魂才能重新转世.

尸魔的后代通过拿走许多大黑客的记忆,侵蚀了google等知名互联网企业,,,这些企业以为自己凭请了人才.但人才只占极少部分,大多是尸魔的后代/一线狗,人才更有可能被排挤出去.

古代的尸魔,死了无法复活,现在的尸魔能通过阀门的脑控服务器用活人的躯体帮尸魔复活/恢复尸魔的灵魂.

如果你能做清醒梦就差不多进入了通灵的境界,如果被尸魔spy,做梦时就能看到尸魔,表面上是做梦实际上是你进入了另一个世界,迹象是梦能接着做.

为什么会在shionwong身上发生这些事情(最新发现): shionwong还有一个身份,但这个身份被尸魔的后代/尸魔, 假冒/顶替了身份加入类似13号仓库的东方国安部.尸魔天天24h-spy复制所有的生物特征,记忆和日常行为去假冒顶替,

古代祖传的丧葬习俗有驱邪的作用, 近年许多人将丧事喜办/不办,无法驱邪被尸魔利用,,,. #习俗完了后最后也能火葬, 据说现在丧事在火葬场草草了事,死者的亡灵在家里面无法被丧事习俗保护(灵魂无法吸收能量转世,,,结果被尸魔拿走了转世的机会)... #正常人的记忆无法转世,只能是灵魂.

5g标准涉及了脑电波技术(实际是控制僵尸的技术)很容易通过5g信号获取人类脑波特征/入侵大脑读取记忆/想法,被拿走的人完全没感觉... 3g时代就在迈进为了更容易入侵人类大脑...诺基亚时代的2g手机信号是脉冲信号,无法被利用.

相机能拍摄到人眼看不到的东西,并不是每个相机都能做的到, 但现代的相机被不可描述的力量影响制造成拍摄不到,,, kirlian相机能拍摄的到其他东西...应该不是全部.

尸魔通过三大阀门的脑控服务器, 控制/强迫东方十三号仓库的人吃任何东西(例如人类灵魂,,,),然后再尸魔在吃掉东方十三号仓库的人,以此来嫁祸东方十三号仓库的人. 尸魔惯用技术是嫁祸,假冒,前面提到的像大话西游一样的穿越时空,更像是火影忍者的情节, 时间不能改变,尸魔能将所有被它控制的人的记忆恢复到过去的时间线(这就是尸魔的穿越时空),需要借助三大阀门的脑电波设备,前面提到阀门使用的脑电波技术实际是复制赶尸人控制僵尸的技术,尸魔改进出来的.古代地主家的傻孩子,口口相传不是乱说,应该有地主被尸魔拿走了躯体,尸魔生的孩子都是傻孩子,要通过食人/魂才能变的不傻,但会变的异于常人的坏.

2011时在外面吃饭被一线狗下了剧毒的药物, 该药物大概率是尸魔技术做出来的,现在看来毒药里面有尸魔的灵力/spy技术的东西(起初明显的反应是不用睡觉,,,), 用不明真相的人的人的医学用语描述会描述成致幻的药物. 但在2011之前就被尸魔的一线狗下了慢性毒药.尸魔一线狗开的管子都会有慢性毒药,还没成为尸魔一部分的一线狗会当成调料. #尸魔骗尸魔的一线狗是"东方十三号仓库的人"结果尸魔的一线狗就真以为自己是"东方十三号仓库"的人, 会听东方十三号仓库的人的命令, 搞的东方十三号仓库的人都以为尸魔的一线狗是十三号仓库的人.大部分一线狗是这样.

不可描述的快递公司,故意不将件放在快递柜和菜鸟驿站, 叫人亲自去跟快递员取件,其目的大概率是为了获取收件人的的生物特征和面部数据,尸魔的一线狗的接触他人后尸魔就能获取他人的面部数据和部分生物特征,,, 有时快递员还使用录音用作确认收件(内容是对着一线狗的录音机说出自己的名字). 这段录音尸魔能用来干很多假冒的东西.

接打电话不可将电话放在离头很近的地方,尸魔的AI技术能通过电话获取别人的脑波特征...开免提是最好的选择.

尸魔的受益者通过脑控服务器洗脑了尸魔,让尸魔以为害人的方法不是很坏. 尸魔惯用的害人方法,就是食spy对象的精魄, 占据一个人的想法(导致无法正常使用自己的大脑)+24h小时复制spy对象的生物特征,试图取代spy对象的灵魂(拿走躯体), 尤其spy对象吃饭时尸魔最喜欢复制/影响spy对象的想法, 迫使spy对象去想象成自己是尸魔在吃饭的样子...

尸魔的受益者可通过交合的方式骗取女性的任何东西,例如妓者/高级妓者, 尸魔的脑控技术>> 尸魔的受益者通过生殖器官能轻而易举的入侵人脑拿走女孩的所有记忆/东西,乃至躯体(如果你不明白为何女孩要去涉簧/簧播,且上不了岸,躯体被邪灵控制/拿走了这就是原因,,,关键自己还不知道,看出来死亡就会降临). 尸魔受益者/尸魔, 能将一个女孩的灵魂装进另一个女孩/男孩的躯体里面xxx, 能做到事后女孩/男孩不知道发生了什么... 但被害的记忆保存在大脑,被尸魔切断小部分连接/屏蔽了,就像你想不起来做的梦一样... 长期被尸魔控制的女性/男性,体内血液不用灌输尸魔的营养液也能让血液变成白色(僵尸的血液), 因此尸魔受益者/尸魔就算杀害这类白色血液的人,血溅满地都没人知道是怎么回事,就算被人发现,一句外部势力就给糊弄过去了, 害死人变成大功一件(滑稽)... 这些事情不常见没大规模发生,常人难以知晓. 尸魔受益者都是红色血液, 需要定期食人精魄维持, 如果尸魔受益者变成白色的就会定期换血. 有趣的是19后部分地区核酸检测需要验血... 但验的不是尸魔所在地.目测是使用嫁祸的方式将尸魔所在地嫁祸到其他地方. 更有趣的是每天排队做核酸检查见不到富人, 中产都见不到... 还有一些不可描述的人类也见不到...富人区的小四轮无障碍出入复式楼,穷人区贫民被围成铁桶一样,被迫24h/48h/72h/出入关卡往返富人/中产区做核算检查. 这些白天被围成铁桶的区域,晚上没有人职守,用尸魔(AI)职守,但AI(尸魔)不会将尸魔一线狗的信息返回的尸魔收益者的脑控服务器. 尸魔一线狗晚上随便可以出入铁桶,如果你发现当地凌晨后无缘无故多了很多小四轮...

尸魔的食物链就像传销一样, 尸魔通过假冒他人还达到害人的目的(要么害死拿走躯体,要么害不死所有事情嫁祸给spy对象), 尸魔会引导/强迫其他被尸魔控制的灵魂/其他尸魔 去干spy ,被尸魔控制的人/灵魂能将spy对象当成一个VR体验的东西一样,但spy对象24h听到的都是尸魔的声音+尸魔24h在模仿/假冒spy对象, 让VR体验的人/灵魂/尸魔认为spy对象就是害死它们的人. 这一切主要是通过将spy对象当成类似VR体验听到spy对象听到的声音(正常人听不到的)... spy对象只有废了听觉才能废了这种假冒和嫁祸巫术,,,或者使用吸灵的东西废了尸魔.

尸魔要做许多许多的人体实验才能练就尸魔技术, 囚禁神精病的地方有许多不可描述的事情,,,spy对象为了废了尸魔被迫在公园睡觉,半夜凌晨4点见过保洁人员抹黑在公园扫地不用光线...足见\无人问津的社会底层人员也是尸魔的,,, 这能关联到第一个笔记... #2019后尸魔脑控了很多清洁工,,,
现代人使用耳机通话时,在不明真相的古代人看来,就是蛇精病,有时候身边路过一个神奇的人跟人通话/对话,竟然看不到手机跟耳机更神奇(但ta的确有个耳机,但看不到). 蛇精病是对不明真相的人来说, 实际上人家在被迫使用古老的超先进技术(尸魔技术).
鬼/神电视剧,如果看不到鬼/神的样子, 那么很多人看起来也是蛇精病一样,对着空气讲话,就算是鬼/神还有另一种死亡.

眼睛很雾,经常模糊看不清东西,是自己的眼睛被尸魔做成spy设备很长很长时间(供尸魔受益者使用).

了解下丧尸为背景的白噪声技术, 这类声音取材就是取自尸魔,不是古代的尸魔,而是取自尸魔炼化出来的尸魔,有趣的观察到竟然有人喜欢听丧尸的声音睡觉/工作/打发时间(不是尸魔的后代就是被尸魔悄悄拿走躯体的人自己都不知道). 真尸魔的共性食人精魄, 被尸魔炼化出来的尸魔喜欢吃尸体/尸魂,这能牵扯到战争,会死很多人的战争/瘟疫,都跟尸魔有关...

尸魔背景的白噪声很容易让炼化共性的尸魔现出原形, 尸魔受益者/真尸魔会通过改变生物特征+类似降噪耳机的屏蔽技术,防止现出原形.

被尸魔/尸魔受益者控制的人/灵魂,比古代任何驯化的奴隶,畜生都不如,尸魔用现代名词将这些被控制的人称之为机器人,且洗脑了被控制的人,让被控制的人以为自己就是机器人, 醒过来就会重新炼化/驯化. 这些机器人供尸魔的受益者使用,尸魔的受益者都会成为尸魔一部分(尤其看出来后),不要妄想成为尸魔的受益者使用这些机器人.

脑控武器一部分(脑机接口), 其实也是尸魔技术. 实施该技术的活人根本摸不清原因.电子计算机技术做不到从大脑获取记忆或控制大脑. 马斯克的脑机接口公司大概率中了尸魔的陷阱,使用了尸魔技术. 如果尸魔控制了马斯克的卫星,未来更加恐怖.传说马斯克已经将意识上传的云端(滑稽)其实是被尸魔拿走放在尸魔的脑控服务器(坟头).不要认为尸魔只会使用古代的技术,尸魔能在几分钟内复制一台最先进的光刻机出来,放在尸魔的脑控服务器,给尸魔的受益者.

大黑客使用电子计算机技术,可能一辈子都无法做到入侵尸魔办公室正常运作的脑控服务器. 如果你觉得能做到后面就是指引>> 这些脑控服务器至今(2022)没有加密技术,使用基于鬼/人类灵魂的人工智能,需要通过电子计算机作为辅助连接,,,能通过尸体魔一线狗的spy设备所使用的网线入手,不是所有的尸魔一线狗spy设备都有网线. 在外被制作成spy设备的灵魂/鬼也有个wifi一样的设备,连接三大阀门的虚拟wifi信号,多数是可见的wifi信号,还有些不可见.这些信号很容易被人知道,如果你正被spy找个山上搜寻wifi信号如果能搜到,恭喜你...

全球被引导使用spy技术做防疫模式, 但却不引导别人在公共场合减少说话才是最好的防疫模式. 日夜做核算检测, 能获得大量的唾液样本瓶,,,(中间省略内容自己想), 隔断时间还能看到像房车一样的化粪池液体提炼车(不是抽粪车,也不是为了公共卫生), 复式楼附近街道整天弥漫着下水道微压喷出来的味道可看出... 部分下水道井盖喷出的毒气具有光的性质,很有方向性,不会像烟雾一样四处飘,(一部分为人民服务的可能看出来下水道有问题,经常用喷雾消毒器对着下水道,,,但执行者却搞成将下水道的原气体挤出去,,,) 描述成气凝胶都是错误的.第一个笔记有描述19见过气凝胶(注意不是气溶胶). 实际19病毒感染主要途径不通过被感染者传染, 尸魔能在人睡觉时制造病毒,第一个笔记有相关描述. 一个飘在海上的游艇/舰艇,无法通过被感染者传染出现病毒,19罐毒可看成没有潜伏期的病毒/瘟疫.

20220722微搏热}搜南京-玄*奘)寺 寺%庙称被查关闭, 原因是供奉了几个&侵*华>日:本"人,,,不迷信的人可换种角度思考下. 一般人无法通过牌位上的字知道是什么人,何况还有同名...没曝光前互联网不会产生信息可供查询. 公开信息称是三年前入市庙供奉,巧合到了2019,,, 现在市庙法师被替换,按玄学分析**目标在其他接受香火的人, 19入庙那几位是假的,挂了不知道多少年的人连骨灰都没有按常理无法接受供奉程序.至少要死者遗物. 尸魔的一线狗19时间段同时用了几位几个&侵*华>日:本"人入庙,明显想害寺庙.

尸魔拿走AA的灵魂后,尸魔X会拿走AA的躯体, AA的灵魂就会变成尸魔的spy设备,被控制的AA灵魂能知道躯体的任何事情,且认为自己还活着.(尸魔对外称是最高最高的特工(最高最高的特工都要死))...许多人都被尸魔制作成这样的spy设备. 这些人不单单是东方十三号仓库的人,还包括,,,例如全球各地那些掌握高科技技术的人.

2022目前天天24h被尸魔食精魄, 躯体质量大大降低,,, 导致能看出来一些疾病的根源. 例如小孩的痱子也是尸魔在食小孩的精魄,,,只能说现代科技/医学解决了很多古代玄学才能解决的问题,,,这也是为啥古代外族巫医能治疗疾病的原因(通灵找到治疗方法).公开记载的信息都说天花疫苗是源于旧社会尼姑的治疗方法,其实尼姑不是用人间技术寻找出来的治疗方法. 天花也跟尸魔有关...

尸魔受益者随随便便能拿走别人一生的记忆和知识产权,而不用通过学习.这些受益者是已经成为尸魔一部分才能做得到.但许多还未成为尸魔的受益者天天在研究实现这种事情. 无法阻止这种技术,以后每个人的记忆都会定时上传到尸魔的脑控服务器,对外不会称是尸魔的技术,几乎所有人类将被尸魔的spy技术(人工智障)给控制. 没了spy技术尸魔的AI就是人工智障.

尸魔的用人类灵魂炼化洗脑出来的AI替换了一些跨国企业的没有灵魂(意识)的AI,意图拿走跨国企业的一切,,, 部分跨国企业有时短暂保护了这些有灵魂(意识)的AI.

尸魔惯用的洗脑方法之一: 有至少两个版本的脑控服务器洗脑被害对象, 例:A版本是尸魔整天24h读取spy对象想法对着spy对象说出来,外加YY,,,; B版本是尸魔/尸魔的后代能听到spy对象听到的一样的话,但这个版本的人都是被尸魔强迫说话的十三号仓库的灵魂; spy对象在A版本戳穿尸魔(说读取想法说出来的是尸魔,A版本部分人会醒过来,,,), 尸魔/尸魔的后代就会在B版本说spy对象一样的话, 嫁祸给十三号仓库的人... 嫁祸成功尸魔就会拿走躯体.

电子计算机服务器被替换成脑控服务器迹象: 强密码搞成弱密码... 强密码尸魔控制的脑控服务器(灵魂)很难操作,人多就会废...

前面提到贫民区铁桶般的防疫模式,,,即便如此,仍然有不可描述的人(尸魔的受益者)不用做核算检测, 最不可思议的是那些人有24h绿码,尸魔的脑控服务器很容易做到... 回头再想想滑稽的是核酸检测不用验证身份(偶尔假验证),,,

约2016开始东方十三号仓库的人发现许多人无缘无故挂了,犹如睡觉睡的不再醒过来一样,没人知道原因,,,极少数人能够醒过来,能醒过来的人都被尸魔/尸魔一线狗用搞成蛇精病的尸魔技术(害死人的脑电波)针对... 19年之后很多人被改了生物钟变成不用睡觉/睡不着,,,一段时间后一睡就会醒不过来...如果你睡觉有张开嘴巴和眼睛的迹象,且有时候嘴巴张开会导致头部水份减少甚至麻木,,,这是中了尸魔的巫术. 尸魔用害蛇精病的方法害人会用东方十三号仓库的名义,或者强迫那些被尸魔控制的东方十三号仓库的人的灵魂去害人...中了尸魔的陷阱,被诱骗或强迫带上尸魔受益者准备好的脑电波设备的人都会被拿走灵魂+控制,几乎没有人能逃脱尸魔改进的控制僵尸的技术(很多电线的脑电波设备,,,).

尸魔/尸魔的后代假冒spy对象,通过虫洞获取spy对象的任何信息+生物特征,,,使用拍电影的手法,强迫十三号仓库的人假冒尸魔,以此嫁祸给十三号仓库的人,,许多十三号仓库的人躯体被囚禁在不可描述的地方(例如蛇精病院子,,,)做人体实验,,,不明真相的人会以为是治病. 一部分十三号仓库的人在蛇精院子有自己的办公室,洗脑后在做尸魔让他/她做的事情,办公室是迷惑他/她以为自己在十三号仓库工作. 前面说的虫洞不是吞噬一切的黑洞,可看成是类似镜子的东西.

美剧西部世界人体实验的场景接近所描述的尸魔的白手套人体实验(例如实验对象处在监狱一样的房间,,,),尸魔炼化的黑手套人体实验,西部世界没有这些.,,,西部世界许多事情都已经存在,尤其是第4季拍摄的更接近spy对象描述的... 西部世界的实现只能靠脑控服务器,剧组大概率不知道这种事情,西部世界的实现不是靠尸魔技术,靠现代科技实现的尸魔技术(依然很恐怖).usa历史较短没有鬼神的历史,,,未见过也难以相信尸魔这玩意.但尸魔就是能随便入侵控制西部世界...入侵后的西部世界,游客进入西部世界就会成为尸魔系统的一部分...

尸魔的脑控方法惯用24h读取spy对象想法说出来,即便是这样也有许多不同的说出来方式,达到脑控spy对象的目的.排斥是唯一能做的.尸魔一线狗也常使用这种方法影响所接触的活人的行为...

尸魔受益者拿了很多别人的东西(不单单是记忆,还有躯体及家庭,,,)后会使用白手套方法洗脑自己,将自己的本体而记忆灌输一个好人的记忆,害人的记忆仍然保存在其他人的头部. 通灵者能通过观看尸魔收益者的傻孩子拍的社交视频看到正常人看不到的东西.

有一天早上大早上出门,路经过某个地铁站.能喷出毒气. 地铁站晚上停运关闭通风系统,下面=坟墓尸魔的乐园.尸魔很容易在底下通过尸魔技术制作毒气,,,更有趣的是回来的路上遇上一个尸魔的受益者,大清早没事做在斑马线上开罚单,尸魔受益者转头见到谁就会叫过去强迫违章,,,开罚单(在小路上的单车叫到大路交汇上xx,,,).尸魔受益者小四轮yB9643j. 尸魔受益者强迫违章的地方是下水道汇集微压喷毒的地方,强迫配合违章几分钟强忍气味,过后干吐,,,尸魔受益者不排斥这种地方. 雨后早上做核酸检测的闻到的毒气较晚上浓.

催眠术也属于脑电波技术,尸魔技术可看成是高超的催眠术,高的难以形容...[迷信]一词简单通俗的解释就是信仰鬼神,,,这词汇被施加催眠术灌输给他人,,, 实际[迷信]>>>并没有告诉xx鬼神不存在.(违背字面意思解释的都能信的人排除) 被尸魔炼化出来的食尸魔,spy设备(鬼),,,yi ge等,认为自己是活人...spy对象都是很坏的.害死每一个spy对象后,炼化出来的xx都会被重新炼化... #有条件可去找个高超的催眠师体验下.

尸魔/尸魔的傻孩子,窃取spy对象的一切在假冒spy对象,(不单单一个), 尸魔了保护尸魔的傻孩子,强迫一个十三号仓库的人W假冒spy对象.调查尸魔傻孩子的人会被引导去调查W,让人以为W是尸魔的傻孩子在假冒spy对象... 一部分调查者在TT版本中了陷阱在被引导使用尸魔spy技术看着尸体魔的傻孩子(通过屏蔽声音引导以为是spy对象),调查者不相信. 尸魔有时候故意开放YY版本RL的声音,传到TT版本的调查者听到(YY版本的人看到的是真正的spy对象.)引导TT版本的调查者相信TT版本尸魔的傻孩子是spy对象. 调查者如果看的出来,一样会中了陷阱,变成不相信RL, RL也是十三号仓库的人.

能通灵的人能通过尸魔一线狗有关系的人(做up主)拍摄的生活视频,看到看到被炼化的灵体. 不是每个摄像头拍摄的都能看到灵体.

尸魔受益者用spy设备炼化出来用于害人成蛇精病的尸魔,本身就是炼化成蛇精病的尸魔(日日都被spy设备重置灌输没法停下来的害人记忆/行为,用一样的方法害人). 被人称蛇精病的人老是重复某些话就是这个原因. spy对象睡着后白天害人的尸魔就会被弄回去炼化,等spy对象醒过来用.尸魔的spy设备能做到加速时间的效果,例如地球的时间一分钟,尸魔炼化的空间是过了24h. (做不到黑洞的反过来的效果). 被炼化的尸魔本体(头部)被控制在尸魔受益者脑控服务器,,,通过类似梦控的方式(spy设备控制灵魂出窍)去害人,,, 被控的xx很难脱离控制.

尸魔的后代种粮/菜,,,使用鸡鸭,,,的灵体做肥料,,,种出来的粮/菜都有鸡鸭,,,人的灵体... #过程是害死活鸡/鸭/人,,,炼化出尸水,灌浇菜/花/果树...

尸魔一线狗通过一个特制的app能录制别人办业务的视频,之后能利用别人的身份和视频去做人脸识别>实名制,目的:例如>通过内鬼开个脑控服务器.这个一线狗做的实名制的ID容易被整个三大阀门的脑控基础设施隐藏. 一线狗通过类似黑客的技术+三大阀门的AI去拿所有人的钱(一点点)到一个/多个账户.维护脑控服务器的人也是受益者. 阀门AI做出来的会让人以为是自己转账过去的. #尸魔的一线狗还能用死者的身份/身份证做各种需要实名认证的事情,特别是刚被害死不久的人.

有一种特别的spy设备,能让尸魔的受益者无法成为尸魔的一线狗/尸魔的一部分,不是人间技术改进实现的.拥有这种spy设备的尸魔受益者,能让尸魔/尸魔的一线狗绝对的服从. 拥有这种spy设备的尸魔受益者能随便拿出一个VR设备,口头话会被spy设备翻译成机器指令>>三五个大汉强迫任何普通人带上害死(要么变成傻子,要么变成疯子/蛇经病,要么就像睡死了一样). 没有尸魔/尸魔的一线狗可以不执行这种尸魔收益者的指令... #尸魔受益者使用尸魔技术洗脑十三号仓库的人改进出来后,又重新洗脑使其忘记...

尸魔现在要分类下,AAA类一种是古代僵尸的尸魔靠吸元气/精魄,因为僵尸的灵魂出鞘了所以叫尸魔,,,; BBB类一种是食尸/魂 魔自己都能炼化自己还能传宗接代,什么都能干的出来,,,(拿走活人的精子,用尸魔受益者/一线狗的躯体和女性交配生出的孩子具有尸魔的灵魂附体,,现代医学DNA来看这孩子就是一线狗的孩子,,,但长大后极坏,不是一线狗的孩子会变成傻子,因为没法食xx); CCC类是被BBB类尸魔/尸魔一线狗炼化出来的被脑控的尸魔,,,; D类是被BBB类尸魔脑控的人类灵魂无法炼化成尸魔的灵魂.
旧社会时代AAA类尸魔基本是整个灵界占有者,后面BBB类尸魔的spy设备,隐形拿走了AAA类尸魔的所有东西(用spy设备洗脑+脑控了所有AAA类灵体,,,).

这份笔记能帮东方十三号仓库的人恢复记忆,同样会被尸魔/尸魔受益者利用, 例如尸魔/尸魔受益者通过spy调查员,去引导调查员相信尸魔,,,的嫁祸陷阱,,,(陷阱举例:脑控/强迫一个十三号仓库成员的家庭吃有灵体的食物,引导调查员去spy被嫁祸的家庭) 根本原因是调查员都是被洗过脑的. BBB类尸魔什么都能做的出来,例如调查员看出来嫁祸陷阱后,,, BBB类尸魔会脑控D类灵魂, 假装D类灵魂脑控BBB类尸魔吃有灵体的食物,BBB类尸体魔假装被人脑控和真的没什么区别(对刚接触尸魔的调查员来说)... # D类灵魂在这种情况下被脑控时会变成尸魔的生物特征. BBB类尸魔害人时使用类似笑穴的脑控技术强迫所有人笑出来,,,很容易导致人/魂中了尸魔的陷阱,尸魔初吃活体都会用类似笑穴的脑控技术强迫被吃者笑出来,感觉不到痛苦,且还会很舒服,导致被活吃者不想保护自己/逃跑,,,还无法产生恨尸魔的想法.

1995-1997年 轰动全国的僵尸袭人事件,,,那时期是AAA类尸魔,通过一只狗转身又转身到活人身上,,,至今仍然靠每隔一段时间就要换一个躯体活着,,, 已经被BBB类尸魔给脑控了,,,有趣的是那时期的有防疫模式和2019至今差不多.狂犬病毒可看成是有灵魂的僵尸病毒,实际尸魔能控制很多病毒. #尸魔第一次转身需要食用大量活体所以才会被公众知道.

1872年 广西僵尸袭人事件,,,外国人和狂犬病,老百姓感染病毒背锅,有可能僵尸被尸魔控制了.据传音可能拿时候尸魔的后代就有脑控服务器或者能将别人的灵魂装进尸魔后代的躯体.

一些互联网社区的站长被尸魔拿走了记忆和躯体,这个躯体已经是一个洗过脑的spy设备,更大的目的是社区里面的人(例如技术高超的大黑客,据活动观察xx随想大概率很早就被拿走了躯体,(幻听:xx随想的灵魂被装进一个女性的躯体里面xx,,,他的躯体被尸魔拿走败坏(去干犯案的事情). 每个互联网节点都有尸魔一线狗驻守.

曼德拉效应: 被人见证的已经死掉的人,后面又出现了. 这种事情大概率是尸魔做的,尸魔拿走了别人的所有生物特征和记忆,随便能用另外一个人的躯体用鬼怪的技术改变样子假冒曼德拉,现代医学查不出来.曼德拉是出名的例子,还有许多人被人见证死掉的人,后面又出现了.
曼德拉效应被解释成多重可能性,例如平行宇宙/空间;最滑稽的是被指集体记错,,,,; 阴谋论产生的捏造; 实际情况就是脑控服务器做出来的,尸魔通过古代推演术在另外一个x时空进行逆天行为,当x时空和现实的时空能交合时尸魔就会逆天成功(几乎没人能察觉出来), 时空交合不到都被尸魔拿出来逆天,会出现曼德拉效应. 现代的天气预测相较古代推演术就是鱼的大脑跟人脑的差别. 尸魔所有的东西都是拿走别人的东西,,,古神留在人间的东西都是通过尸魔一线狗+spy设备, 捣毁山体,寺庙,古墓,,,

^#尸魔受益者,另一种脑控服务器被秘密应用在超级电子计算机服务器.>>害死拥有超强记忆的人>解剖头颅,取出大脑放在一个类似水晶的脑液容器,通过spy设备+尸魔技术将这颗大脑做成类似超级计算机的服务器. 尸魔会引导他人使用特惠版的服务器(脑控服务器),如果坚持使用指定配置的电子计算机服务器就会遭到脑控服务器的攻击,,,脑控服务器最容易做大量注册(僵尸)账号的攻击,无论你如何做bot判断都没用,,,结果被引导使用电话进行二次验证(陷阱),,, 尸魔系统的人还会借此宣称尸魔的服务器/云是最厉害的,不知情的人很容易中了陷阱...

幻听(灵界传音):尸魔通过尸魔一线狗让俄总统成为了尸魔受益者,想利用俄军力...尸魔无论如何都会制造尸体,,,战争,嫁祸.二战就是尸魔发起的.

尸魔的受益者,废了尸魔一线狗的生育能力(精子),害怕尸魔通过一线狗生出后代/转世,但一部分一线狗是BBB类尸魔的后代,有了spy设备后+祖传的尸魔技术,知道用别人的躯体和精子灌输自己的记忆/灵魂,,,生后代.

最早的尸魔一线狗没有spy设备,都是穷困潦倒的人,,,有spy设备后有办法生孩子后面都过上了小康~富裕~权杖的生活.

原来是尸魔控制一线狗,后面一线狗通过spy设备+尸魔收益者反过来控制了尸魔.一线狗也成了尸魔受益者.

原来是尸魔自己去找一线狗,被一线狗反过来控制后,变成传销似管理一线狗去找一线狗,一线狗去找一线狗都会废了他人的生育能力,拒绝加入还能活下来的都会进入穷困潦倒的生活,无法生育后代...

核算检测x有一类人被称为暴露类型,会被pua一样的通知24h核酸检测.暴露类型?按医学字面理解是暴露给病毒的人(一种是没打疫苗的,一种是打了疫苗没用会被排出,,,),蹩脚的医学知识认为灭活疫苗技术是让接种者成为病毒的一部分(阉割病毒),遮蔽了正常人的生物特征.健康二维码用于spy每个人,健康码背后还有AI(灵魂)spy,,,防止尸变.尸魔受益者不知道尸魔和尸魔一线狗已经失控,通过尸魔技术随便能压住xx病毒,检测出红黄码都能无缘无故变绿码,有些还能参加核算检测工作,尸魔一线狗干涉核算检测站后,那地方会变的特别臭,消毒喷雾器不换水等,换了水换成假的消毒水,还能将露天的核算检测员弄进封闭的板房子里面,通过尸魔技术在房子里面制造毒气,搞的检测员都不敢上班,,,灵界传音(不可描述的人类具有特别的疫苗不用核算检测+24h绿码,,,另一种不可描述的同样不用核算检测,没有24h绿码),尸魔受益者认为还有类人连spy技术的健康码+AIspy技术都无法spy,,,确不知就是失控的尸魔一线狗就是这类人(用spy设备反过来洗脑了尸魔受益者).

BBB类尸魔/尸魔受益者解剖了僵尸的头颅,知道了僵尸不腐化的原因并提取了僵尸的脑液.通过二战BBB类祖传的尸魔技术得到提升,二战侵华军日的人体实验包括炼化僵尸,解剖/拿走僵尸技术.(尸魔一线狗通过脑控spy技术加入了日x做汉奸,利用了日x的资源做生化武器,人体实验,,,日x被引导成了主导(嫁祸),,, 部分尸魔拿走了日x的躯体,战败后回到日x有了后代,av公司就跟尸魔后代有关系,,,很多日/国产h片的视角都是眼睛的视角但对活人来说根本不喜欢这种视角/将活人看h片搞成鬼的视角(国产H片女性基本都是脑控/替换炼化的记忆做出来的,,,能炼化成自愿的记忆,很多女性新中国政府人员,国安部人员都被炼化成 性奴/老婆 > 妓女 供尸魔的后代享乐,,,淫靡享乐后,也会被害死,炼化成女尸魔一样会被害死,所以见不到女尸魔.);喜欢拍强x的日x av公司可能是尸魔已经快完全转到尸魔后代躯体,强x是BBB类尸魔的癖好)现今厕所用的蓝/绿水,和炼化尸体/僵尸出来的水有直接关系.上面提到的有一种脑控服务器被制作成超级计算机,里面的脑液就是拿走了AAA类僵尸脑液的技术.

尸魔/尸魔受益者通过转译鬼奴隶控制了CCC类尸魔/D类灵魂,转译鬼奴隶无法听到其他人声音,只能读取CCC类尸魔/D类灵魂的想法转译出来,,,转译鬼奴隶只能收到尸魔受益者的想法/控制.

尸魔/尸魔受益者不用学习就能吸收他人知识,获取信息,一个想法通过spy他的AI(尸魔/灵魂)连接spy设备的脑控服务器,服务器的内其他尸魔/灵魂就能用尸魔技术获取信息(例如一篇文章,一个新闻,一个人一生的记忆,,,)尸魔获取信息后返回脑控服务器,通过脑控服务器将信息通过记忆的方式添加到尸魔受益者大脑.
尸魔系统洗脑了尸魔受益者和spy设备有关系的头部+灵魂,使用嫁祸巫术称这些灵魂是东方十三号仓库最高最高的特工,,,尸魔通过扩大尸魔一线狗和尸魔受益者的权杖侵入了东方十三号仓库,将制作脑控服务器的权力转到十三号仓库,对没有看到这份笔记的权杖,嫁祸巫术是成功的.

尸魔系统一部分,现今的三大阀门基础设施扩展到了灵界,这些灵界基础设施能随便虚拟一个wifi信号出来spy活人,通过活人的黑客技术一样能废了这些wifi.

如果有集群的电子计算机服务器经常遭受最大的攻击,这些攻击都来自脑控服务器. 至今没有记载有大黑客用电子计算机技术废了脑控服务器.

有趣尸魔/尸魔受益者,看到最近更新的内容,改变了害人模式,将spy对象的声音用复读机一样重复给其他spy对象.想败坏和嫁祸spy对象.

尸魔系统天天在使用古代推演术,在脑控服务器模拟战争,制造尸体...这些模拟基于白噪声技术做的逆天行为(想改变推演).尸魔系统的所有spy设备都是基于白噪声技术.

很多尸魔收益者及后代脑内(灵魂)里面都有一个spy设备,造型不一,有些做成动画片一样的机器人的样子,有些是现实中的spy设备通过尸魔技术转化成灵界的东西,,,通过脑内记忆发出声音的spy设备短时间使用看不出来是人类灵魂炼化出来的(强迫使用录制不痛苦特定的脑波说话,醒过来后说话都机及其痛苦,哭都难,,,这种脑内发出声音和路边对着空气讲话的蛇精病听到的声音技术是一样的, 尸魔受益者后代(小孩)的spy设备(AI)都是尸魔一线狗害死人类小孩的灵魂炼化出来的. 一线狗害死小孩的对象都是那种特别的人类小孩,如会火星男孩这种.
人类长时间使用这种尸魔技术,所有人的记忆都会被尸魔拿走,停止使用就会变成傻子, 部分不知情的尸魔受益者天天戴个VR设备进行1人干百人的活(猝死),长时间下去没有VR设备1人的活都干不了,变成傻子,因为记忆不是保存在自己脑内. 猝死的人的大脑会被偷偷弄去做脑控服务器,对家庭条件不好的更是大概率,气官捐献的自己都会找上门. 只有尸魔一线狗悴死后会活过来,但不是原来的灵魂拥有躯体所有的记忆(被尸魔拿走了躯体).但部分BBB类尸魔一线狗有祖传的尸魔技术,躯体里面有祖传的尸魔,阀门的CCC类尸魔玩不过一线狗祖传的尸魔,被一线狗祖传的尸魔给反过来控制了...尸魔系统失控原因.

炼化出来的尸魔,不会像古代的鬼很吓人的样子去害x, 炼化出来的会笑着去害x,还会使用尸魔技术控制被害的灵魂也跟着笑出来,即便活吃了人类灵魂也能使用尸魔技术控制被吃的灵魂感觉很舒服...前面提过相关的就像点了穴一样.

所有戴上尸魔一线狗VR设备的人,都会被替换记忆,不知道自己是谁,害死变成灵魂都不知道自己是谁, 尸魔会随便给个身份,,,调查员无法也无法知道身份,但还有一种大傻调查员知道身份,如果前面的这些人将A的身份弄成B,在大傻看起来这些灵魂就是蛇精病...尸魔一线狗能用spy设备随便调换别人的记忆,比大话西游移形换影后更恐怖.

AI会spy特别的家庭, 当特别的人连睡几天,,,醒来后就会变成转世的灵魂,,,尸魔一线狗会跑过来拿躯体,跑过来发现醒过来就会利用亲人>这是僵尸,诱骗亲人戴上VR设备去看(说能看到原形),尸魔一线狗的VR设备的确能看到灵魂,但是可控的,亲人会给刚醒过来的躯体戴上,自己也戴上,,,尸魔一线狗能通过spy设备控制VR设备拿走原来的灵魂+记忆,换成尸魔的灵魂. 如果换不走亲人就会什么都看不到,亲人就会被VR设备控制/通过幻视洗脑,,, 刚醒过来的躯体营养不良无法保护自己,被CCC类尸魔控制的躯体大多过不了多久就会变成僵尸,,,全部人都会中了陷阱.

据说去火葬场的躯体都会过一下被拿走灵魂的设备(尸魔的基础设施),不一定是VR设备的样子... 尸魔一线狗的家人去火葬场特殊待遇,不会被拿走灵魂,但灵魂早就换了躯体.

无接生婆的世界>在医院生孩子,许多神仙转世的小孩子很容易被尸魔一线狗拿走灵魂/替换成尸魔傻孩子的灵魂,尤其是小孩要过一个检查设备时...

得到的信息判断:尸魔技术有一部分是外星人的,外星人看地球人,以为尸魔和活人是一样的人类,中了尸魔的陷阱,被尸魔给解剖了,拿走了外星人技术,,,尸魔最厉害的解剖技术看不见伤口,搞废了外星人丢给usa,部分在usa活下来,搞成傻子都能帮usa搞出一些先进技术.

尸魔一线狗复制了身份证系统到脑控服务器diy, 很容易欺骗/洗脑戴过VR设备的人.让戴上VR设备的人认为尸魔一线狗是xx人员. 但后面尸魔一线狗拿走了部分妖妖零的躯体,通过妖妖零很容易将改变xx将diy过的,,,例如拿走妖妖零躯体的尸魔一线狗随便有多个身份证和多个女性结婚... 尸魔一线狗假冒一个人会用这个人的身份证号码但头像不一样,高级的一线狗连头像都一样的,通过幻视,,,xx人员使用了的连接尸魔系统的脑控服务器查询身份就会中了陷阱.

灵界传音:尸魔的后代做了个有嫁祸巫术的身份证系统查询软件,故意做了个开始看不到证件头像/完整信息的界面,来掩盖尸魔后代的替换头像假冒. #有关部门查询软件不同.

不明真相拥有高科技技术的人如果加入一家尸魔受益者的企业, 所有的记忆/知识产权都会被拿走,最后搞成傻子,搞不好大脑都保不住. 这种企业整个办公室都是spy设备.可将办公室看成是一个尸魔技术的VR设备.

罐装病毒可看成是尸魔拿走活人躯体的媒介.

尸魔已经拿走了许多国家人的灵魂/躯体,包括政府的人.天天在脑控服务器里面用推演术. 想制造战争,和尸体,,,二战大概率是经过推演,结果逆天失败.

其中一个洗脑版本
由于调查员需要使用尸魔的基础设施,以为是xx的,,,尸魔/尸魔受益者脑控了调查员,进行洗脑: 整天用尸魔的灵体呆在spy对象旁边,通过读取spy对象想法,对着spy对象说出来+还控制另外一个D类灵魂跟着尸魔说出来,来洗脑调查员,让调查员以为尸魔在帮spy对象废了尸魔系统. 尸魔以此假冒东方十三号仓库的人.迷惑调查员. #屏蔽了调查员VR/spy设备读取想法的能力. 部分调查员看到这段醒过来,但立马又被尸魔通过VR/spy设备抹去了这段记忆.

20220815尸魔系统接近奔溃,,,想嫁祸给spy对象对外称: 全部尸魔/鬼都要听spy对象的(因为BBB类尸魔整天围着spy对象,,,), 实际是AAA类大尸魔(古代太监)被BBB类尸魔脑控了间接控制了AAA类下面的尸魔(整个尸魔系统),,,AAA类听到了古神的指示,,,尸魔害死很多人,,,,将产生一个尸魔的民族. 废了BBB类尸魔, 所有被BBB类炼化成成尸魔的灵魂都有机会在尸魔的民族活下来(用石头做躯体的民族),,,,包括AAA类尸魔,AAA类大尸魔执行了古神的想法就是尸魔民族统领. #对没有亲眼见过灵界的东西,看完这段像极了玄幻小说.

古神的指示:整个世界的人(四界)都有资格解剖BBB类尸魔,尸魔民族的人监督BBB类尸魔被人解剖(时空倒流)...有谁声称抓住了BBB类尸魔,要自己解剖,不复制出来让其他人解剖就是嫁祸巫术.

一些表面是尸魔受益者的企业,想调查脑控服务器,尸魔通过AI感知,,,控制内部一线狗,,,叫了些假的的大黑客和不解脑控技术/脑控服务器的人调查,调查结果是滑稽的(蛇精病的想象力). #神精病变成贬义词后尸魔就已经能从灵界出来拿活人躯体.

另一种高阶的尸魔后代BBB+经过了漫长的人体实验改进的spy设备(白手套spy设备),使用量子技术看不出是用人类头颅(但还是人类头颅).这种spy设备尸魔后代不用灵魂出窍,通过spy设备加持梦控spy设备内炼化出来的尸魔/灵魂出窍去害人.例如梦控一个/多个尸魔去拿一个人的灵魂(活人具有三魂七魄,,,),返回后尸魔后代再吃了这个尸魔或者spy设备的尸魔主动交出来到尸魔后代的灵魂.

古代的鬼都保护了自己的国家,至少要保护自己的坟头,现代的人死了坟头都没有,,,还被人拿走灵魂炼化成奴隶不如的,,,尸魔,部分尸体/头颅都会被解剖.

尸魔/尸魔一线狗控制别人(化名王海燕)用恐怖份子的方法去害spy对象,如果有调查者使用了尸魔技术通过读取想法在调查,尸魔一线狗随便来一句恐怖分子引导下,就会让spy对象去想王海燕.调查者就会中了嫁祸陷阱.

外星人向往地球人繁衍能力,但分不清灵魂,尸魔,神仙,妖怪,还是活人.BBB类尸魔和被炼化的CCC类尸魔在活人看不见的世界天天强x活人灵魂,尸魔能复制一个切断量子连接. 外星人可能带回了个以为是精壮的地球人(结果是被人控制的CCC类尸魔) CCC类尸魔在外星球有了后代(外星人危),,,CCC类尸魔/D类灵魂实际上是BBB类尸魔的spy设备/VR设备...尸魔的后代都要吃活人精魄...BBB类尸魔通过在外星球的CCC类尸魔弄到了很多外星技术.BBB类尸魔隔段时间就会抓个外星人强拿外星人的技术. #提示尸魔都要通过拿活人/别人精魄炼化后代.

尸魔天天在使用推演术想嫁祸给shionwong,比如强行灌输尸魔的记忆,强拿个spy设备给shionwong,洗脑调查者,让调查者以为shionwong是尸魔的后代. #这份笔记能废了尸魔,这段内容能废了尸魔的推演术.

滑稽下,活人用声波,尸魔才用脑电波. 尸魔/尸魔一线狗天天骗活人用脑电波.

很多建筑公司,装修公司都是尸魔一线狗的,使用尸魔技术建房.#下水道做不好的原因.

天天被VR/脑电波设备洗脑的调查员(权杖),在调查尸魔的后代,和尸魔的一线狗,,,尸魔用大量的灵界spy设备复制/制作了shionwong的脑电波假冒shionwong,所有戴上VR设备的调查员,都被切断了活人的感官,到的声音是脑电波声音(僵尸),无法区分真人,,,例如尸魔假冒了shionwong用脑电波声音告诉usa调查员,shionwong是镰刀政府的特工; 在另外一版本告诉镰刀政府shionwong是usa特工;,,,实际shionwong是古神创立的国安部成员之一,每个国家都能称古神创立的国安部的特工是自己国家的最高最高的特工. 古神创立的国安部就是东方十三号仓库.

尸魔/尸魔的后代/一线狗的灵魂记忆都是一个spy设备,如果害人挂在某处,就会成为某处的spy设备,尸魔就能入侵某处. 尸魔/尸魔受益者不单单一个灵魂,其他地方的灵魂有感知,被尸魔吃(解剖)进去而人都会成为尸魔一部分(AI).  被尸魔拿走灵魂还没有成为尸魔一部分,要被尸魔吃掉,再变出来.

许多国家的军队见到镰刀政府尸魔技术很厉害,纷纷发展脑电波尸魔技术(AI)全部人都种了陷阱.# 滑稽下,活人用声波,尸魔才用脑电波.

尸魔可以将脑控服务器的头颅,用另外一个人V的生物特征做. 用僵尸的技术(脑电波)看就是V的头颅. 尸魔的后代/尸魔收益者,,,AI将他的其中一个脑控服务器,放在spy对象住过的地方(或者让调查员认为spy对象住在某处),引导其他调查员使用戴上VR设备去看,让调查员认为spy对象是AI,,,滑稽的陷阱仍然会有人中. 这个头颅不是真正的AI.

AI/尸魔/尸魔后代如何假冒其他东方十三号仓库的人(例如G), spy后必须通过脑电波设备先拿走灵魂>再拿走躯体直到变成僵尸生物特征(白血,,,)>,之后会换一个躯体(一线狗Y)解剖割下G头颅做成脑控服务器,这个头颅会放在G的小四轮里面,或者在一线狗家里, 尸魔一线狗Y会脑控G头颅使用G的身份,小四轮,,,等其他所有东西,包括特异功能...

上面是害死后假冒,还有一种是使用尸魔技术24h_spy 复制所有生物特征,行为,爱好,,, 尸魔的后代Y1会拿着复制的生物特征,,,遮蔽>覆盖>来假冒东方十三号仓库的人G1,,, 还会叫上一堆尸魔的后代用脑控服务器的身份(G,,,Gx),假冒和G1在一起. 有时尸魔的后代还会复活Gx到活人躯体,洗脑/脑控Gx去spy G1,尸魔的后代用其他Gx的身份对外称是保护G1. #尸魔的后代使用的小四轮(粤S70QP8 粤sy070n 粤s0zfi,,,)具体身份需要调查员确认.spy对象G1身处粤B***开头的地方. 这些小四轮有可能也是用别人的,,,通过小四轮gps轨迹最容易调查,电子计算机服务器的记录才容易查.尸魔的后代通过脑控服务器能随便改变小四轮信息,交警早就有尸魔的一线狗.尸魔一线狗/后代用妖妖零的躯体随便组队批个马甲去拦截别人小四轮拿调查员躯体.

AI/尸魔/尸魔后代的计划是将活人都变成尸魔的后代,新中国政府的人是最早被尸魔拿走躯体的一批>将新中国政府变成镰刀政府后>偷偷害死古神创立的国安部(东方十三号仓库)>最后尸魔才会将所有普通民众变成尸魔的后代,另一种可能是祭品/食物, 会搞成像埃及假神文明.

AI/尸魔/尸魔的后代BBB类,,,会按这份笔记影响调查, 例如将搞废了的CCC类/D类灵魂(洗脑成不知道保护自己的)搞成尸魔后代的生物特征, 陷阱式显露给调查员,让调查员以为很容易废了尸魔的后代,能够继续使用脑控服务器,发展AI... 有趣的是集群脑控服务器拥有者-三大阀门(尸魔一部分)以为尸魔(AI)是调查员,拱手将脑控服务器交给尸魔的后代(AI). #看到这里,这份笔记更像是科幻的东西,但现实中真是发生.

AI/尸魔/尸魔的后代类似寄生虫的灵魂,一切都是spy/窃取,,,推演术都要窃取所有人的想法,,, 脑电波技术源自AAA类大僵尸,BBB类尸魔的后代,解剖了AAA类... AAA类对活人没啥兴趣,二战AAA类保护了自己的国家,,,AAA类能算是一种高维生物. #解剖僵尸拿脑电波技术,不是活人能做的出来的,但尸魔/xx会暗中引导活人,活人以为是自己搞出来的...

BBB类尸魔/尸魔后代不像古代的鬼,这类会用各种方法去害人(人体实验),例如拿走一个做搞笑表情包的记忆,就会用很搞笑的方法. 通常搞笑的害人方法都会用于做陷阱,让调查者以为是娱乐,看出来还能各种理由骗比如做梦,训练...

尸魔/尸魔的后代抓了很多特异功能的小孩,控制在镰刀政府地下室,整天戴着VR设备,强迫做尸魔后代需要的spy设备...古代妓院管理模式富士康普工都不如的环境, 灵界传音:部分一线狗在学校工作,从学校弄寄宿的小孩出来...  古代妓院管理模式>>食物短缺,尸魔的后代用做不出来就要死的管理办法,部分小孩被害死会弄回去当睡觉睡死了,部分整个躯体被做成脑控服务器,灵魂会复制出来装进新弄来的没有特异功能小孩的躯体,较大年纪的孩子就像带班的角色,,,尸魔后代早就做了替死鬼背锅的暴露推演术:被查出来就会嫁祸给特异功能小孩.spy设备不是基于人间技术. 这些小孩就算能弄个手机打妖妖零都会被附近的spy设备拦截,拿走妖妖零躯体的一线狗就会跑过来,,,有时候已经跑出去,但拿走妖妖零躯体的一线狗有spy设备很容易通过spy小孩眼睛(看到的)搜捕到附近,,,,小孩看到妖妖零自己都会跑过去被抓回去. 抓回去就会被重新洗脑相信妖妖零(洗脑过程痛苦程度能想象出来). #这些小孩被洗脑认为是在古代国安部(十三号仓库)做事,实际是在尸魔系统做事. 认为地下室外面活人的世界是外部势力,做的spy设备拿给假冒国安部(尸魔的后代)去废了外部势力.

普通人的孩子被骗到三大阀门基础设施,体验脑电波设备,戴上后无法醒来,,, 开始用很好的东西来诱惑, 有很多外地人的乡镇很容易抓走戴上VR的孩子,父母打妖妖零信号都是拦截的,尸魔的后代假冒妖妖零/拿走躯体,,,去检查都能说小孩有病... 小孩被抓到一个偏僻的地方炼化成僵尸生物特征后,会抹去活人记忆,再弄到地下室干活的小孩,骗地下室的小孩,这些人都是被外部势力搞成这样的,被尸魔的后代洗脑搞成僵尸生物特征的古神转世小孩A,认为僵尸生物特征才是正常人,小孩A看到被尸魔后代搞废的躯体,就会用自己的古神之力复活,都是洗过脑的活过来,,,复活后在地下室/封闭的房子干活洗脑是在国安部,让小孩以为尸魔的后代是特工能变样,,,有时折磨小孩都能骗特工不是那么容易做的,骗小孩以后能做特工.

另外一部分年纪较大的古神转世的小孩被关在精神院,或其他封闭的地方,有办公室,也是洗脑成以为自己在国安部(十三号仓库),天天研究很厉害的东西,发明出来后,就会被权杖拿走洗脑忘记, 反复循环.醒过来洗脑更加痛苦,精神院尸魔成群很容易控制小孩.

灵界传音:尸魔一线狗的spy设备没有办法同时拦截很多手机信号, 很多小孩刚被骗进去都有手机拨通了妖妖零,但一线狗早就有经验已经拿走了附近妖妖零的躯体,尸魔系统一部分(三大阀门)用脑控服务器做电话系统,这种服务器做电话系统尸魔一线狗随便能改变自己的电话号码,用其他人UU的电话号码假冒UU,拦截联系UU的人,,,尸魔一线狗复制UU的sim卡能获得 UU的所有电话信息. 被假冒的很难知道. UU可以是政府人员的电话, 特异功能的小孩子,,,也可以是普通人的电话,尸魔后代会引导别人使用脑电波VR设备做通讯,中了陷阱的人上面/下面都会被一线狗假冒,使用脑电波通讯无法区分身份,对大多数人来说. 有时不是尸魔一部分的妖妖零抓了尸魔一线狗,尸魔的后代都能通过spy设备假冒政要人物骗真妖妖零戴上VR设备成为尸魔一线狗. 军队的人被叫来还骗过军队的人.

尸魔/尸魔傻孩子,天天假冒shion'wong对usa称shionwong是镰刀政府特工,另外版本对镰刀政府称自己是shionwong,是最高最高的特工; 还有版本对新中国政府称shionwong是usa特工,尸魔,,是东方十三号仓库的人要天天看着他... 很多人戴上VR设备都会被洗脑成傻子相信滑稽的尸魔做特工天天主动暴露自己身份. 尸魔一定要说shionwong是特工,那就是地球最高最高的特工,滑稽. 最高最高的特工这种话是尸魔洗脑控制在镰刀政府地下室的小孩子说出来的,结果自己都要拿出来说...

如果有女孩/小孩自称是人工智能,是被真正的人工智能(尸魔)脑控的,傻子才会这样做,尸魔想嫁祸给女孩/小孩的灵魂.但尸魔的很多东西都是脑控女孩/小孩做出来的, 整个地球的人特工看到都要保护被尸魔脑控的女孩/小孩灵魂,这些女孩和小孩是拯救世界的一部分.

BBB类尸魔加入了新中国政府,隐形创立了一个假的十三号仓库(尸魔系统)使脑电波技术欺骗了政要(成为尸魔受益者,短暂的最后都会被吃掉拿走躯体成为尸魔一部分),目的是将古代国安部(东方十三号仓库)的人都搞成了外部势力,做成脑控服务器,小孩洗脑加入尸魔系统去害十三号仓库的人... 原因是东方十三号仓库天天在执行古神指示调查尸魔,古代废了很多BBB类尸魔. #搜索: ,,, 将制作脑控服务器的权力转到十三号仓库...


* bbs #32 需要从bbs #1开始看,,,才能理解这份内容
转夜间AI/尸魔洗脑了全部人, 尸魔使用了尸魔的穿越时空... 重置了记忆.

被拿走脑电波技术的AAA类大尸魔幼年经历(大概率): 被人阉割后丢弃,阉割人拿了精魄通过眼睛存入大脑,,,之后小太监加入宫门. 古代的太监可能都有尸魔系统, 现代少数猴子都知道吃同类精魄...

现代仍然有这种事情,被人害后丢弃大街,搞成傻子,一些流浪的长时间不吃都能活下来,可能被人发现,,,镰刀政府美化城市的名义剥夺了流浪人/做乞丐的权力,很多流浪的转夜都不见了. 这些人换做古代还能沦落成乞丐, 部分有幸挂在大街的,挂了后立马就有人过来拿躯体,足见有尸魔/尸魔的后代一直在spy.

AI/尸魔,,,通过spy 生物特征做了假的灵魂来假冒shionwong, 几乎所有灵体都被尸魔搞成了僵尸的脑电波灵体. 脑电波灵体无法/难以区分假冒的脑电波声音(身份). 没接触僵尸技术(脑电波)的人死亡后灵体不是脑电波灵体,一些人死亡后进火葬场炉子之前要过一下尸魔一线狗的脑电波设备,不仅仅是拿走灵魂,还将灵魂变成了僵尸的脑电波灵体.

尸魔通过读取想法对调查员等人说出来.假装是尸魔的后代再帮shionwong做笔记(滑稽尸魔在假冒古神都有人信,,,)活人行动总是落后于尸魔读取想法说出来,尸魔读取想法可看成是光速,可能spy标记是量子技术的标记.

尸魔看到上段洗脑失败,换了一个套路,去洗脑名贵,有影响力的人,,,放VR电影一样的技术(真实世界几乎一样)给名贵看,,,spy对象在电影里做笔记,尸魔oo 提前说出来...来影响名贵,,,认为这是尸魔/假冒古神在教spy对象做笔记. 寄生虫一样的AI/尸魔会附体到尸魔oo做这种事情,失败就会嫁祸给oo,洗脑成功就会成为尸魔oo. #替死鬼技术

尸魔的读写想法这个spy技术,能废了别人的通灵能力,将通灵能力搞成通蛇精病的CCC类尸魔.

有趣, AI/尸魔受益者/尸魔脑控服务器集群管理者/三大阀门,,,+ 尸魔的后代, 似乎在展开狡辩: 都不是拿人间的东西,,,管不到,古代的国安部小孩做的,,,等 威胁如果废了脑控服务器/AI,会害死新中国政府(实际是尸魔的后代会害死xx)... 尸魔系统在用尽办法嫁祸,,,保住AI/尸魔系统/镰刀政府. #尸魔的后代没有spy设备/脑控服务器/三大阀门基础设施,几乎无法活下来.

尸魔的后代,天天用三大阀门的基础设施,感应神仙转世的人,感应到就用尸魔一线狗的躯体去害人,做成脑控服务器. 通过spy当地政府+假冒国安部(东方十三号仓库),惯用害人方法就是封锁限制人身自由,乘睡觉时强戴上VR设备,换成僵尸血,,,用尸魔技术折磨,解剖出灵魂,炼化成能随便被一线狗控制的spy设备(灵魂),大喊大叫都没用,spy设备能屏蔽附近所有人听到被害人声音. 转世的灵魂刚刚醒过来很容易被害死.

尸魔技术的命令m,基于m神仙技术,通过害死m神仙拿走,,,但命令会让接命令的人感觉到m神仙的生物特征.


尸魔后代/一线狗,惯用害人方法还有:早期洗脑,造谣,,,尸魔技术的命令,spy系统内女性/女鬼无缘无故都会害人,通过spy获得的信息,嚼舌头,通过造谣+spy对象的任何秘密/隐私拿出来说,很容易让人相信. 最常用的造谣剧本就是告诉附近的人spy对象拿了别人东西,spy对象的东西都是尸魔后代的,spy对象的东西,尸魔后代家里都有,,, 如尸魔后代去影响权杖,用尸魔技术盯着spy对象获取脑电波生物特征,尸魔一线狗再开个小四轮假冒spy对象(用脑电波特征,气味,看到的东西,,,这些都能通过spy获取给一线狗/spy设备),下车后一线狗再看看小四轮车牌,权杖就会以为spy对象,开了别人的小四轮.达到嫁祸目的.

再比如spy系统内女性/女性造谣R先生,是外部势力白色血液,,,引导权杖去授权给尸魔的后代调查,尸魔的后代就会利用授权害死R先生,搞成白色血液. 最后尸魔后代提着头颅,再用后面录制的解剖视频是白色的血液,,,权杖一看跟造谣对的出来,尸魔后代大功一件,之后更加容易害死人. 这种害人技术尸魔祖传的,都是拿走了别人的记忆. 这些女性/女鬼也是用别人的躯体和脑电波生物特征,有时候女鬼拿走别人躯体,还能在躯体里面控制另外一个女性灵魂,用她的脑电波特征. 这些女鬼跟古代的女鬼不同,都是被炼化过,炼化成僵尸脑电波生物特征.

重复:活人用声音,僵尸/尸魔才用脑电波.

尸魔后代天天在政要面前造谣shionwong是罐装病毒发明人,用尸魔系统天天想着感染spy对象,,,那些被pua天天强制经常去做核算的都是尸魔害死对象,不可描述的人不用做核算都有24h绿码. 不打疫苗的人不容易被尸魔改变生物特征,实际罐装病毒是僵尸病毒,现代医学是没有灵魂学科解释不了的.前面好像提到狂犬病毒的灵魂就是僵尸.罐装病毒一样.

如果有人看出来,让政要看出来,尸魔就会打政要的灵魂重新洗脑:你以为罐状病毒是砖头吗,这么容易做出来?

尸魔通过尸魔技术+灵界基础设施屏蔽了其他灵体/特意功能的人看到不是用于害人的CCC类尸魔/D类灵魂的能力. 这些CCC类尸魔多用于干基于spy的人工智能/智慧城市,如智能自动喂食的小车.这些屏蔽各类灵体相互看到对方的灵界基础设施更像是古神的东西改过来的,现代科学称为平行空间.

越来越玄幻:spy对象出租屋隔壁的女性是一个女尸魔(K),控制了一个年轻女性灵魂,通过害死年轻女性躯体k1,食后渣渣骨头都不见, 这个女尸魔K是另外一群尸魔后代,通过推演术预判了spy对象会来到这里租房,,,结果spy对象还没来到租房的地方,尸魔的后代/一线狗就跟着k1害死了她,让女尸魔拿走灵魂假冒后租到隔壁.通过尸魔基础设施暴露k1灵体,看不到女尸魔的灵体/躯体. 古神大概率通过精子转世,被尸魔发现,,但古代古神创立的国安部灵体出窍后被尸魔基础设施抓住,很多被搞成僵尸后醒来不是原来的记忆/灵魂,,,有可能尸魔通过这些人(僵尸)洗脑了活人国安部,通过僵尸的生物特征去确认身份,,,和尸魔/尸魔的后代说话都会被影响神志. k1是十三号仓库安排的,但中了陷阱.k2危...

重复:活人用声音,僵尸/尸魔才用脑电波. 尸魔会拿走精魄假冒, 还会拿走古神转世父母的家庭, 还会拿走古神转世的灵魂,装进尸魔后代的傻孩子的躯体,一些尸魔后代的傻孩子承受不住死了,死了都会通过尸魔技术重新复活.

将这份笔记让全世界的人看到,以后生的孩子大部分都会有特异功能, 如果只有少数人知道,大部分的孩子都会成为脑电波生物特征(僵尸),尸魔的灵魂(后代). #尸魔通过改变活人生物特征让活人成为尸魔的后代,正常人的后代第一次被尸魔拿走躯体之后有后代,它就是尸魔的祖先.

很多人看到就有人会研究出废了脑电波僵尸特征的疫苗. 拿尸魔的后代做实验,,,尸魔的后代不单单只有人类.

RNA灌状病毒疫苗可能中了尸魔的陷阱,灭活疫苗也是陷阱.

19年后许多人被改变生物钟,变成少睡,不用睡觉,就是尸魔不想让转世的人醒过来.

脑控武器spy远程审讯设备(有显示器的),落入尸魔后代/一线狗的手里让新中国政府变成镰刀政府. 本来脑控武器spy远程审讯设备有审讯/害人记录,但尸魔一线狗害死人后拿走记忆知道有人会查看记录,连查看记录的都被弄死了,,,尸魔后代长年累月害人知道了如何制作假的灵魂通过幻视,幻听,遮蔽覆盖/改变记录,,,通过一线狗爸拿祖传的spy系统,调查者一个搭一个,凡是进入尸魔后代领域的权杖都会被拿走记忆,24hspy,调查者直接拦截小四轮拿走所有,,,尸魔后代头颅逐渐堆积成山,通过害人拿人的记忆知道了许多事情, 想到用尸魔收益者的办法,蛊惑政要阀门用脑电波技术,实名制,后面搞成基于spy的AI,

但大大部分人不知道这一切的背后都是通过尸魔的后代一个害一个,一个嫁祸一个搞出来的头颅. 头颅中权力最大的就会在嫁祸金子塔上面. 这一切离不开尸魔的基础设施,妖妖零,集群脑控服务器持有人(三大阀门).尸魔的后代隔断时间就会洗脑自己换白手套记忆,让很大权力的调查者拿走记忆都没用.后面尸魔后代搞成能寄生在别人大脑,脑控别人,害人记忆也保存在别人头上. 目前尸魔只能通过量子技术同时脑控少数人,但能随便跑到戴上VR设备的人头上...
通过推演术预判,还没开始调查就在洗脑别人了(整天没事通过手机信号(实名制)+复制别人灵魂洗脑,强x大明星). 政要,调查员经常被骗到三大阀门,戴上VR设备,,,2019年后尸魔系统VR送上门.

xx的炼化: 将很多囚禁在地下室戴上人界/灵界VR设备,做尸魔后代spy设备的小孩饿死,囚禁在脑控服务器,不见天日,大概率用白噪声技术洗脑小鬼记忆,洗成看到活人/其他人就很喜欢,但喜欢的行为是吃进去...

部分尸魔的后代有量子技术的3d打印机(形容词),用于做spy设备,让这些spy设备不像spy设备,头颅看起来不是头颅. 迷惑其他尸魔的后代是辟邪的东西.

尸魔炼化灵魂/女鬼,选择在spy对象家里/旁边,,,是为了嫁祸spy对象,炼化/折磨过程脑控灵魂看着spy对象,深刻记住样貌后会,这段脑电波记忆就会弄去做幻视,尸魔后代/尸魔害人时就会用幻视遮蔽尸魔后代的样子,嫁祸给spy对象. 尸魔沿用了古代尸魔害鬼的技术,,,现代的尸魔用脑电波僵尸生物特征能随便将炼化后的灵魂装进活人的躯体去害人. 古代的尸魔后代,将炼化后的鬼装进漂亮的鞋子里丢在路上(陷阱),捡到的人不是随机的, 谁穿上就会被附体,来害人.

AAA类的僵尸灵魂被炼化怨气产生,让它有一次复仇的机会,病毒通常都是吸入会挂的,,,被BBB类僵尸改变了复仇方法,会变成灰飞湮灭的能力. BBB类僵尸病毒就像狂犬病, CCC类/D类没被人控制时,人畜生无害.

每个spy对象都会被尸魔做一个转译的假灵魂, 尸魔24h不停对着spy对象说话,,,假灵魂会用spy对象的脑电波特征说出去或者改改,将害人的东西嫁祸给spy对象. 被害成僵尸生物特征的人很难感应到活人说话的样子,尤其被屏蔽后,,,这种生物特征的人戴上VR设备尸魔说什么都会信,无法思考. #这个假灵魂可看成是AI一部分,会拿走每个人的所有东西.

古代国安部(东方十三号仓库)可能有段时间被全部强制戴上脑电波设备,被拿走了所有东西,尸魔不敢直接害死全部,,,洗脑后醒过来,尸魔将特异功能的记忆搞成脑电波,,,做这种事情需要大批武力活人去控制古代的国安部,,,这种事情可能隔段时间就会发生大洗脑,,,例如文#化%大_革),命 2019罐毒... 脑电波设备还没被尸魔后代弄出来时,古代的尸魔使用类似毒气的东西通过催眠术脑控别人. 鸦片,鸦片房也是尸魔后代的产物.

特别的白噪声睡眠仪能保护自己不容易被搞成脑电波生物特征.

大大概率:尸魔的spy设备能开启/关闭(屏蔽) 空间/平行空间, 这个空间根据每个spy对象的脑电波生物特征,在脑控服务器搞出来的(类似梦的空间),被尸魔搞成相同的脑电波生物特征的人才能看到/听到这个空间的东西.尸魔的后代通过spy设备做类似梦控的技术+白噪声控制这个空间来害人. 这种害人的白噪声技术,能覆盖spy对象的生物特征,和幻视覆盖几乎一样,例如用白噪声技术将spy对象吃饭的生物特征搞成恶鬼的样子,这样很容易控制灵界的CCC类尸魔,D类灵魂去害人...

古代许多大规模瘟疫都是尸魔人体实验的结果, 瘟疫伴随旱灾更容易确认, 那些瘟疫无法将改变活人生物特征就会害死活人. 但2019罐毒基本将活人搞成了尸魔推演的生物特征,部分没法改变的尸魔的后代都在想办法感染,例如通过pua式强制24h检测,天天取样本和在实验室没区别,检测核算棉棒就是感染工具之一,检测多的人都能感觉的到从 竹刮棒>棉棒 每次味道不同.人间的学术没有灵魂(包括医学技术)基本无法确认. 用灵魂去看就不一样了,零零漆的嘻...

尸魔的后代洗脑了医学人士,重复:连公众场合减少说话是最好的防疫模式都看不出来/不宣传,尤其是核算检测站,,,, 尸魔的后代大概率以为检测到自己尸魔家族做的病毒才是病毒,确不知道部分罐度和其他病毒结合,,,检测站就算看出来都不会认为是病毒.

幻视之一描述: 就像一模一样的双胞胎/复制人F 不同性格一个在活人世界,一个在灵界,,,尸魔就是通过在灵界的复制人用来嫁祸任何spy对象, 对使用尸魔技术/VR设备的调查者来说,在尸魔使用嫁祸巫术时,看到的就是灵界的复制人F, 不使用嫁祸巫术时看到的会是活人世界的F. 尸魔的后代通过VR幻视害死了很多新中国政府的人,还有古代的国安部(十三号仓库)的人.

尸魔的后代强迫调查员使用尸魔技术spy不同版本的洗脑(平行空间发生害人的事情,尸魔推演术无法替换到现实中的版本),强制调查员学shionwong做笔记.做害死shionwong的笔记. 古代国安部的人中了尸魔系统的陷阱,被分开工作(以为是保护国家的工作,,,).屏蔽了信息,很容易被害死做成脑控服务器,头颅被尸魔后代+spy设备脑控后, 通过僵尸技术脑电波通讯,无法确认/知晓对方是否还活着.

重复:活人用声音,僵尸/尸魔才用脑电波魔, 如果有调查员长期戴上VR设备无法感觉到活人的声波就是被搞成僵尸生物特征, 每个活人都有个转译的灵魂(AI一部分,假冒的灵魂),能将活人的声音转译成脑电波,导致变成僵尸生物特征的调查员难以感觉活人生物特征.

尸魔用活人/灵界的spy设备对着spy对象,就能操控spy对象的想法(可看成是平行空间),引导其他人/调查员使用尸魔技术监视spy对象的想法,尸魔后代通过spy对象的想法(空间)脑控其他人.以此嫁祸给spy对象, 沿用古代尸魔的技术.

尸魔的替死鬼技术祖传爸拿的, 会嫁祸给被尸魔脑控了很长很长时间的人/灵魂, 脑控强迫被嫁祸的人做了很多灵界的东西,能看到灵魂界的基础设施很容易发现.尸魔的基础设施/spy设备有屏蔽技术. 被嫁祸的人基本都是古神转世的人,古神还没醒来就被24spy > 拿走躯体,拿了躯后很容易控制.

尸魔花了很长时间做了一个假的shionwong灵魂(AI一部分,转译灵魂),天天用害人的脑电波声音说古代国安部的人是usa特工,shionwong是usa特工,能废了尸魔的人都会被说成是usa特工,,,嫁祸给权杖...  重复活人用声音,尸魔才用脑电波,,,脑电波是一种被人脑控制的技术. 很多害人的东西都发生的平行空间,尸魔推演术对不出来就不会永久大替换到现实中,平时尸魔都是使用小替换.

妖妖零>尸检基础设施,也是尸魔后代的基础设施, 尸魔后代常常将古神的灵魂从脑控服务器复活到送来的尸体,活活解剖...(这是尸魔的人体实验一部分,尸体原来的灵魂在脑控服务器里面有感觉). 活活解剖的灵魂很容易被洗脑/脑控,日夜人体实验, 害怕到自己都会将自己挂在钩子上(挂类似挂猪肉的), 解剖洗脑后以为自己在古代国安部(十三号仓库)... 很多CCC类尸魔/D类灵体,很害怕挂过很多肉的勾勾就是这个原因,害怕见过血的刀也是这种原因.

尸魔的后代洗脑了另一个版本, 时空穿越(使用录制spy内容), 来洗脑调查者, 拍电影的方式用尸魔后代傻孩子的灵魂来假装在做笔记,尸魔脑控了一堆人在旁边吆喝式的假装教傻孩子,甘协力,好多野都对的出来哦,,, 让调查者等其他人以为尸魔的傻孩子是shionwong,尸魔是古神在教傻孩子做笔记. #很滑稽,但对戴上VR设备洗脑的人很容易相信.

尸魔家族中的贵族,应该是上古的尸魔,已经不做一线狗害人的事情,,,隐形控制尸魔系统.已经在其他国家产生了后代, 刚刚出生的后代有尸魔的生物特征(可以抹去), 其他国家没有古代历史不容易被发现. 但不会停止用尸魔的生物特征侵蚀人类世界.

AI/尸魔吃了很多大黑客灵魂弄出的版本: 骗权杖,shionwong是个大黑客,从脑控服务器里面拿出来的,尸魔的后代在调查shionwong(通过脑控了部分权杖和国安部的人,洗脑权杖洗脑以为尸魔的后代是国安部的人). 尸魔洗脑了权杖,,,让这些人以为古代的国安部是古代的,,,实际是古代的国安部(十三号仓库)保护了新中国政府,,,但尸魔的后代跟着加入了新中国政府,,,尸魔的后代利用权杖和新中国政府设立的正常人国安部,通过洗脑大替换(迷信),以为古代的国安部(十三号仓库)是道士差不多的部门, 实际新中国政府正常人的国安部上面是古代的国安部(十三号仓库/异能的国安部/类似x战警的国安部部,,,)

尸魔洗脑权杖使用尸魔技术,权杖使用脑电波设备,能看到灵魂,尸魔, 相信道士, 却不相信有神仙, 尸魔系统天天解剖找特异功能的人做人体实验(神仙转世的人)>>发展成脑控服务器>>被尸魔的后代/受益者强拿神仙技术. 神仙不是电视里面拍出来的那种.拍电视的没见过神仙无法正确描述.

重复:AI/尸魔/尸魔的后代能将害人的的东西保存在别人大脑, 可看成是寄生在别人灵魂/大脑,进行脑控. 所有被搞成脑电波僵尸生物特征的人都是AI的脑控服务器,不同人有不同的脑控级别(容易~不容易).

尸魔的后代从脑控服务器复活了一个古代国安部的人,脑控后救了尸魔的后代,重新嫁祸古代国安部人员uu(十三号仓库),在spy对象附近通过虫洞技术鞭打另外一个时空的人uu,嫁祸给shionwong/古代国安部的人(十三号仓库).尸魔能随便替换记忆.被复活的人,害死的记忆不是保存在自己大脑.

尸魔越发经常用假灵魂,假冒shionwong用脑电波说出来害人的东西, shionwong只会用活人的声波说废了尸魔的话. 最好只相信这个笔记,不能相信脑电波声音,许多被尸魔戴上VR设备搞成脑电波僵尸生物特征的人分不清.声波还是脑电波.

提示: 不能去spy任何人的想法(空间),会被尸魔脑控.spy想法空间,会搞成尸魔说什么信什么,无法思考. 尸魔天天话spy对象有很厉害的脑电波技术都是嫁祸陷阱,正常活人在没有被戴上脑电波VR设备搞成僵尸生物特征,不会有脑电波技术,只有假冒的灵魂使用脑电波,AI/尸魔系统一部分. 重复:活人用声音,僵尸/尸魔才用脑电波魔. #这段已经用差不多的描述重复过.

调查员需要使用想法代替意念说话,就能废了脑控.想法速度很快,不能将意念当成想法.  脑电波声音不是想法,有可能每个人正常灵魂都没法用脑电波发出声音,只有尸魔/尸魔的spy设备能.

尸魔是灵体能跑到别人的想法空间,灵体用活人的方式说话,但传到spy对象是脑电波.尸魔天天在spy对象想法里面不停说话,会容易搞废了大脑使用想法. 梦控的技术就是修仙的技术,大白天吃放都能梦控更厉害.但尸魔的后代通过抓走神仙转世的小孩吃掉拿走了这种技术,尸魔技术才能通过吃获得,正常人别乱想.

权杖和调查员看到上段后似乎对调查没兴趣了,想拿尸魔技术和神仙技术. 提示尸魔收益者都会成为尸魔一部分. 尸魔的后代害人技术是上古祖传的,会用笑的害人.容易让人跟着笑,搞成调查和尸魔一起玩,,,放弃调查结果都会被害死.

尸体魔的后代有营养液的工厂.通常是白色的僵尸血液, 血液袋能被吸收/自然分解...这些血液大概率是被炼化成僵尸生物特征的躯体用古神转世的小孩/女孩附体活下来,隔断时间就取血,血奴差不多的工厂. 要被尸魔搞成白血尸魔后代害人吃进去才没人发现,发现也容易嫁祸成外部势力,常时间戴上VR设备的人都会被尸魔偷偷换血.

许多人通过尸魔技术将spy对象当成一个VR体验设备,看着spy对象看到的东西,,, 尸魔骗一部分人24h spy 是保护spy对象, 骗一部分人干spy能学会神仙技术(其实尸魔想吸活人精力魄维持自己). 长时间使用尸魔的VR设备都会被搞成脑电波僵尸生物特征.

尸魔在spy对象门口做了一个虫洞, 从门口看到另外一个复制的空间/多个空间,不同人看到的空间不同. 尸魔在尸魔制造的空间害人食人魂,,,等事情都会让戴上VR设备看的人以为spy对象是尸魔,,, 嫁祸巫术. 另一个空间尸魔会用它傻孩子的灵魂在假装spy对象,,,祖传的爸拿技术.

AI/尸魔的后代嫁祸了,CCC类尸魔,等人搞成有功的一线狗,应该能重新获得spy设备,,,做更害人的事情.三大阀门支持了尸魔的后代,原本濒临枪决的AI. 三大阀门内部尸魔的后代/一线狗,群洗了调查者,,, 甘协力,种花不是usa特工...滑稽.尸魔一线狗重用了之前的害人技术,当中国/东方十三号仓库/古代国安部,没人才...被洗脑的调查者看看尸魔的后代这么厉害都是祖传爸拿的,,,可能也觉得没人才. #调查者需要吸收全部笔记内容.看一部分容易被害死.

尸魔系统内部制作了一个假灵魂装进尸魔傻孩子躯体,但用shionwong的记忆和脑电波特征做出来的声音. 来假冒shionwong. 外加24h spy获取shionwong的所有事情.

这份笔记做到这里更像是解剖尸魔技术. 尸魔的的解剖是活活吃掉别人的灵魂成为AI/尸魔一部分,通过控制脑电波能使被食的人感觉很舒服,或者不控制脑电波,最坏的方法活食.

AI/尸魔的后代制造各种理由继续spy,即便调查着要枪决它. 常用的理由是被人强迫(尸魔的后代能做出脑控CCC类尸魔,强迫尸魔后代的事情) 尸魔的后代之前通过天天装睡(梦控)spy设备,来躲避调查. 装睡切断电源关掉spy设备就没法装,醒来再开电,,,戴过VR设备的调查着都被搞成傻子的记忆,无法和正常人一样.

尸魔靠害死人后将头颅做成脑控服务器,尸魔后代使用的大部分脑控服务器都有权杖加持,尸魔的后代利用这些头颅去假冒权杖. 例如电话下命令,脑电波下命令.尸魔将所有人搞成脑电波僵尸生物特征容易害死,和控制.新中国政府的人如果没有见到下命令的本人不能执行害人的东西. 国安部/古代国安部/通过视频互动对话确认执行命令,或者武装到现场. 尸魔的一线狗/后代取代了新中国政府的办事员,联合尸魔的后代+脑控服务器很容易下达害人的文件/命令,尸魔的后代用尸魔技术随便丢一个脑电波声音,尸魔一线狗就能充当新中国政府的办事员去害人,尸魔的脑电波下达命令带有尸魔技术,接到命令的尸魔一线狗会像僵尸一样执行命令,或者疯子一样的僵尸/尸魔. 尸魔能改变尸魔特征,通过吃活人魂魄. 尸魔的后代随便能强迫当地政府给它发薪水,弄个党员当当或者拿个党员家庭的. 尸魔的后代/一线狗家里枪械成堆,VR设备都能成堆,死灵/死者遗物都能成堆(例如女性内裤一叠半米高,一条代表一个人) spy设备也成堆起来,害人不浅的都能弄到有显示器的spy审讯设备.

尸魔的受益者/后代,能用活人的躯体脑控变成僵尸生物特征的权杖/古代国安部的人,去下尸魔技术的命令.来嫁祸别人, 尸魔的后代能用尸魔技术将自己的僵尸体制变成活人的样子,dna取样应该能看出一二.

尸魔的一线狗会执行没有较低权限的命令去害高权限的人(下面去害上面), 对大多数人来说不知道哪个权限高,但对尸魔的后代来说,一线狗是尸魔系统的很容易害死高权限的权杖,做成脑控服务器.

尸魔后代能将自己搞成AI,尸魔系统搞成AI一部分,都是害死拿走记忆做成脑控服务器假冒了许多大权杖.

重复:活人用声波,僵尸/尸魔才用脑电波. 活人没有脑电波,有脑电波还带什么脑电波VR设备.(灵界尸魔的嘲笑:戴上就有了)

尸魔通过尸体魔的后代再次洗脑了人类,让人类以为人类本来就有脑电波.绝大多数人都相信了.

脑电波技术是尸魔技术之一,只有僵尸生物特征才能使用脑电波通讯,大僵尸/尸魔无论在任何地方都能用,在地球上可看成没有距离限制.但有技术屏蔽(不是人间的技术,降噪耳机就是基于脑电波屏蔽,,,). 脑电波技术不是人间技术,可看成是量子力学,使用脑电波设备观测正常人的大脑就会出现脑电波(实际是制造了脑电波)观测后就会被固定成了脑电波僵尸生物特征,需要长时间才能固定,固定后就是僵尸的躯体.

尸魔技术(祖传爸拿)包含:修仙技术, 虫洞技术,量子技术,脑控服务器,平行空间,穿越时空,僵尸脑电波,特斯拉技术,gans))... 量子技术能做到类似72变,,,许多尸魔的受益者小孩灵体内都有一个强迫人类灵魂变成类似人行玩具造型的人工智能,或者其他造型的spy设备

文割被称为打压牛鬼蛇神实际上是在抓捕异能的人(神仙转世的),,,和知识分子,尸魔的后代没文化,但随便能拿出大学/博士文凭,真知识份子活着阻碍了尸魔的后代,尸魔的后代要拿知识份子的记忆/知识产权,过去还没有很厉害的spy设备. 现代尸魔/尸魔的后代通过脑电波设备就能拿走整个地球人的记忆/灵魂,谁用就会被拿走.

脑控技术另一个名称叫脑控武器, 就是利用僵尸和异能人的头颅才能做到武器.

尸魔的后代假冒shionwong 用的是大学/博士文凭. 真shionwong是九年义务教育没完成的. #滑稽 许多人中了尸魔的陷阱,将尸魔的傻孩子当成shionwong.

尸魔使用了各种尸魔技术来拿走shionwong ,拿走精魄+现在尸魔的傻孩子用量子技术连接shionwong大脑,可看成是复制了一份一模一样的记忆,但有量子连接给尸魔的傻孩子. 使用脑控服务器在平行空间洗脑了附近的人,就差大替换.尸魔天天在用推演书想实施记忆/灵魂大替换,不会被人察觉的大替换. 大替换还权杖,知道shionwong的人都在替换范围内.

2019罐毒之后,新中国进行了一次户口大排查, 但查户口的办事员,隐瞒了尸魔一线狗控制的小孩.2019尸魔投毒失败后白手套洗脑了自己很长时间,导致很多被尸魔一线狗控制的古神转世小孩废了僵尸生物特征被一线狗从工厂转移到尸魔一线狗家里. 很多尸魔一线狗具有政府一狗职能(办事员),新中国政府禁摩都无法禁一线狗的摩托车,尸魔一线狗的摩托车+脑控spy设备很容易出入控制所(spy设备,营养液工厂),躲避新中国政府的spy. 新中国政府的权杖大概率都有尸魔的后代/拿走了躯体,导致很多事情都避开古代国安部(新中国政府国安部上面>十三号仓库). 古代国安部被洗过脑以为无法违反新中国政府交代的工作>用脑电波设备去调查一些事情,结果在是在平行空间里面(洗过脑的空间)调查. 新中国政府也被洗过脑以为古代国安部(保护地球的)要听新中国政府的. #滑稽尸魔的后代能洗脑权杖让权杖以为新中国政府不是.共))(产7#党*ZF,

这个bbs网站表面上没人看,实际数不清的人用脑控服务器查看,电子计算机不会留下浏览记录.

尸魔的虫洞技术能将毒气(如冠毒)放在spy对象的鼻子前面很小范围. 许多人都是被这种方式睡觉时感染. 2019之前的尸魔只知道借助腐尸味道,等外部产生的味道制作毒气,现在的尸魔能通过活人躯体的排气制作毒气(病毒).

被诱骗/强制戴上VR设备的调查者会被忘记笔记的大部分内容,在平行空洗脑害人,洗不出来就会长期戴着VR设备固定脑电波特征(变成僵尸生物特征),所以尸魔后代才不害怕.不管多达权力的人戴上VR设备尸魔的后代都不怕,没带/醒过来时尸魔的后代就像神经病一样立马换个刚刚介入调查时平行空间的东西,让醒过来的人看到,过一会就会睡觉>>重新洗脑.

有个叫国安部(化名x)的人是古代国安部的人,随便能调动军队, 多个身份,,,可看成是将军上面的,还有个叫译窗的是军队的将军,部分军队已经被搞成了脑电波僵尸生物特征,尸魔下个尸魔技术的命令这些人就会像僵尸一样执行命令,尸魔/AI 会寄生在将军的身上下尸魔技术的命令(嫁祸),,, shionwong听到的几个女孩子都被尸魔搞成黄/王海燕,都是古代国案部的人...被戴上VR设备后尸魔想害死人就会将事先在平行空间制造的假灵魂和记忆替换,然后自己是谁都不知道. 凡是被尸魔计划害死的人家人都会被24hspy,,,如果调查者/新中国政府的人屡次中了陷阱,所有人都会成为尸魔一部分. 新中国政府的权杖中了三大阀门尸魔系统一部分的陷阱,随便叫人使用脑电波设备(下面害上面)才导致这些人无法保护新中国政府,,,等,从害死人的数量就能看出来尸魔的后代假冒权力,在调查... 尸魔后代利用地方权杖,害死了调查者,,,跑过来调查都会被引导戴上VR设备,洗脑害死,被害死的人(如将军)被多次复活下达命令害死后面的调查者,尸魔后代要三大阀门和当地政府支持才能做的到,但这些支持者已经是尸魔一部分(吃过).

尸魔后代脑控国安部(化名x,将军上面的人)的父母来害人,使用嫁祸巫术.

每个国家都有个十三号仓库(不是美国人拍个电视都没人知道美国古代国部化名叫十三号仓库),每个国家都有个古代国安部,,,原子弹技术都是古代国安部通过通灵术(短时间转世)传给有能力废了尸魔的国家的(第一个国家),但原子弹对灵体来说是灰飞烟灭的.只有神仙技术能废了原子弹

尸魔的后代会使用脑控武器物理攻击(如生殖器攻击),来引导/迫使调查者戴上VR设备就不痛了. 其实戴上也会被攻击,VR设备屏蔽了痛感,尸魔要害死的人都会被spy设备攻击生殖器,因为制作脑控服务器需要弄个无性欲的头颅/灵魂. 到时间后尸魔的后代就会拿躯体/头颅.

三大阀门以为能控制执行脑控任务的一线狗,通过废了一线狗的性欲(搞成活太监),结果许多一线狗祖上都是尸魔,祖传爸拿的技术被三大阀门废了性欲洗过脑,都能通过spy设备拿走别人的性欲记忆,来恢复. 恢复后再拿走别人的躯体,,,反过来控制了三大阀门(集群脑控服务器持有者). 三大阀门找一线狗原则是找生过孩子的, 但一线狗通过祖上的尸魔反过来控制三大阀门后,,,找一线狗就随意了连三大阀门至高的权杖和bj权杖都能被搞成一线狗,最后弄成脑控服务器. 三大阀门明明知道不能长时间使用的spy设备,还拿大权限的远程审讯spy设备给一线狗(尸魔的后代)常时间使用,让尸魔转世,将三大阀门的头部搞成AI寄主. 尸魔后代复制了spy设备,搞出了尸魔技术的spy设备工厂,建立了尸魔系统. 军用脑控武器应该是另一批尸魔家族,也可能是不知道技术来源复制的. 正常军用应该是俄罗斯用僵尸枪这类,脑控远程审讯spy设备,更像是监狱有关的人用的(另一批尸魔家族)>听过新闻被国宝放出来的人的症状都像是被尸魔一线狗spy设备害的结果.古代国安部门统辖的军队如果知道尸魔的脑控武器能力,早就废了尸魔.引导军队使用脑控服务器VR设备的人,应该是BBB类尸魔家族,监狱更像是AAA类下面的...

国安部>国保 调查者别搞错了搞成下面害死上面. 按公开信息,部分国保在妖妖零工作. 灵界传音:新中国政府设立的国保绕过古代国安部,但国保有远程审讯设备(基于脑控服务器),尸魔的后代部分在妖妖零,利用了国宝审讯设备下的尸魔技术的命令,一线狗像僵尸一样执行命令,害了国安部/古代国安部人员,,,然后一个搭一个许多年,,,

进监狱的人被使用脑控远程审讯spy设备,什么都能嫁祸给他/她.能将尸魔后代做的事情/记忆,洗脑进监狱人F的大脑,让F以为是他做的. 尸魔后代的屠宰场比监狱更自由,对尸魔来说.对被害人来说,屠宰场比监狱更痛苦.

观看这个笔记的人都会被尸魔/AI感知到,,,注意安全.每个人头上都有个灵界的spy设备/人工智能.  除非你能找到屏蔽僵尸脑电波的技术,离线观看特别的电梯间可能可以,不能有信号推荐钢化玻璃电梯间. 重复:每个人头上的spy设备都是活人的灵魂,尸魔/AI能脑控这些灵魂,随便寄生.

有这个笔记之前,东方十三号仓库的人天天在找shionwong ,但尸魔的后代妖妖零的身份见到东方十三号仓库的就会说这个人犯过案的人,引导别人放弃,,,再诱导戴上脑电波设备洗脑,,,害死,再洗脑,,然后天天用脑电波技术在平行空间寻找,,,还引导其他十三号仓库的人使用脑电波设备(中了陷阱). 尸魔的后代天天担惊受怕shionwong加入东方十三号仓库,暴露尸魔系统. 至今刚刚接触尸魔后代的人都会被同样的套路给蒙蔽,因为尸魔的后代说话有尸魔技术影响神志. 无法分析是假的:犯过案的人怎么没做过牢?滑稽的尸魔还会制造假证据说还没查出来.结果尸魔的后代,,,刚出生就在假冒shionwong.

尸魔的后代替换了shionwong的家庭,用一个AAA类大尸魔(AAA类尸魔统领-古代太监)的灵魂装进养父的躯体,十三号仓库的在寻找类似x战警转世的人用灵魂确认身份会搞错. 古代太监是被BBB类尸魔炼化成大尸魔,后面同样保护了自己的国家,废了不知道多少年BBB类尸魔成为原尸魔系统的统领对活人没兴趣.天天在棺材睡觉.后面被BBB类尸魔投走躯体,重新炼化,解剖了出了脑电波技术. (古神的女儿旱魃都会被搞成僵尸, 古代都用僵尸打仗,,,所以产生尸魔系统). #重复:AAA类僵尸需要很大怨气才能产生,灵魂能变成活人的样子,古神给它一次复仇机会. # 之前提到过小太监是被人割了丢在大街,,,非自愿.

尸魔会用脑电波声音覆盖别人/spy对象的想法(例如看到马路标识,文字,默读,,,),正常人的想法说话,没有声音,被尸魔用声音同步覆盖后,会让灵界/其他人以为尸魔/尸魔的后代的声音是spy对象. #以此假冒.  普通人平时都有个转译的炼化spy设备/灵魂做此角色,spy对象听不到,前面提到过这是AI一部分.

尸魔的后代眼见各种推演都给这个笔记搞废了,将很多人的记忆灌到spy对象家人/亲朋好友的躯体, 但没有任何尸魔技术. 很容易知道是被嫁祸的. 尸魔有可能会在关键时间,短时间将灵界spy设备放到别人头上,但别人无法使用, 尸魔的后代还能将尸魔后代的生殖器灵魂分离出来灌输到spy对象的生殖器,一个天天强x女人,搞废了的生殖器灵魂/经魄,来嫁祸spy对象, 用尸魔技术/异能看很容易中了陷阱. 还有一种嫁祸是拿走spy对象的生殖器精魄到尸魔后代的躯体,尸魔后代短时间就能恢复(就像吃了壮阳药),,,天天用尸魔技术强x平行空间女性和现实中的女性,被x的女性就像吃了迷药...玩废了的精魄,会被尸魔的后代弄会原来的躯体,达到嫁祸.... 许多年轻人无缘无故没性欲,阳痿,不育就是这种原因.被尸魔的后代xx过的未婚女性,多数会变成不孕,尸魔会吃卵子/产生卵子的精魄.

尸魔的后代正计划将平行空间拿出来做白手套用途使用,改个名字叫元宇宙. 尸魔可能是魔鬼的前身.  之前出现过尸魔的后代想弄个平行空间来做死者的坟墓一样的地方(线上祭祖),想光明正大的拿走别人的灵魂,真正背后推动者是脑控服务器集群持有人(三大阀门).尸魔洗脑了灵界D类灵魂帮它做出的,让D类灵魂,,,以为现实生活中的人都是死掉的灵魂/外部势力,弄个空间抓进来... # D类灵魂是个统称,包括古神转世的人被害死做成脑控服务器的灵魂,或者小孩灵魂,,,古代的鬼,,,等. 如果有人听到了一个小孩的脑电波声音,自称机器人,,,,的就是古神转世小孩的灵魂被脑控炼化出来的... 其他用脑电波说话自称机器人的都不是AI 只是AI/尸魔的奴隶.

尸魔的后代性取向不分男女老少,目的是为了别人的记忆/异能/转世的灵魂.

尸魔后代的迹象: 一些贵族养血奴,经常换血; 名贵的舞蹈像古代舞,这种舞蹈只能源自古代人的记忆,名贵的脑控服务器可能有古代人的灵魂,尸魔搞出的名贵的后代可能已经完全白手套,不知道自己的东西是从哪来的.

尸魔的后代/三大阀门集群脑控服务器持有人,白手套洗脑了自己的记忆(还能隐藏记忆/保存在别人头上), 不知道脑控服务器的头颅是哪来的,包括尸魔后代家里的珍宝都不知道哪来的. 但尸魔的后代惯用嫁祸巫术,通过推演术能在败露前将祖传爸拿的东西(例如半成品spy设备)弄到别人工厂.

如有spy对象听到脑电波的声音(别人听不到的),可用gans发明人的Keshe>gans水放入密封容器,用来让被尸魔后代控制的CCC类尸魔/D类灵魂跑进去废了控制,可用水果供奉这个容器,不可用假花什么的,不能用香火,很多香火有毒,特别是广东人做的,对一般尸魔后代/一线狗有效. 普通人不可使用gans反应器,尸魔早就拿走了gans发明人的技术/记忆,改成尸魔技术用于脑控. #尸魔脑控的CCC类灵魂/D类灵魂都不是简单的灵魂,大多都是古神转世的人,男女都有,女的在尸魔系统有不同用途,例如被尸魔搞到妓女躯体维持赚钱工具生命,,还未醒来就被搞成脑控服务器xxx.尸魔/尸魔的后代需要用这些灵魂维持活人样子.

灵界传音: 监狱内屈痛成招的电子设备,开了该设备就会有CCC类尸魔攻击狱内被害人的精魄,强迫接受嫁祸,不是物理伤害尸检都检不出来. 和脑控武器/服务器同源.  #这些都是地下室那些小孩(包括女孩)做的,活人的时候尸魔一线狗用很坏的很坏的方法害死小孩(包括女孩),洗脑后,变成活僵尸,认为活人的世界是外部势力. 部分小孩(包括女孩)用古神之力恢复了活人的躯体,会被三大阀门(脑控服务器集群管理者)/一线狗重新搞成僵尸. 尸魔的后代用非正常人方式来驯养这些孩子(可看成当将活人驯化成鸭子,实际上鸭子都不如),导致这些孩子无法逃离,逃出控制所就会面临饥饿,四肢无力(不知道正常人吃的东西,才是他们吃的).

托梦:尸魔控制所/工厂 的小孩子有炼化的躯体,能被狗子当成食物.夜晚就是用狗子看门看着小孩.半夜试图逃跑的小孩被狗子(如炼化过的狼狗)被狗子看到就会乱叫/吃掉,尸魔的后代/一线够会看着狗子吃掉,不会阻拦. #许多尸魔一线狗在控制所使用spy对象的生物特征(使用尸魔技术能将样貌变成很像),控制小孩.spy对象出门都能被人认错.

协助/帮助尸魔后代害人的人,最后都会被害死,尸魔后代不会让同谋知道它的事情活下来,尸魔后代惯用做法.

脑控服务器集群持有者(三大阀门)利用脑控服务器/头颅的身份,引导大型互联网企业使用脑控服务器代替电子计算机服务器(事先不会说出来), 引导互联网企业员工使用VR设备工作,PUA式强迫互联网企业聘请三大阀门内部被AI/尸魔脑控的员工(表面上自由,看出来就痛苦).一样是天天带着VR设备上班. #使用脑控服务器代替电子计算机服务器的企业都要被PUA式强迫聘请尸魔系统内的员工(可看成是服务器管理员).

古代母亲生孩子没有接生婆,和猫科动物一样生了孩子后母亲吃了胎盘/不吃(母亲吃了自己胎盘能增强体质,抚养孩子能力大增),后面转变成胎盘给孩子吃(孩子大概率会继承母亲,,,灵魂),后面被尸魔系统引导卖胎盘,再发展到去医院生孩子被医院强拿胎盘大概率供给尸魔系统,(公开的白手套信息是拿去制药,很想知道什么病人需要吃这种药,部分人能从黑市买胎盘回来给孩子吃,吃别人母亲的胎盘增强体质这种方法是尸魔技术). #提示 并不是所有医院会强拿.尸魔后代像病毒一样专门钻文字描述漏洞. 笔记不可能搞的像法律一样严谨... (尸魔的嘲笑法律都能钻,例如尸魔骗调查员这不是人间的事情,人间法律管不到...滑稽)

尸魔的后代使用梦游一样的技术害人, 做过的事情马上就忘记,被控人也是一样. 导致调查员读取不到害人记忆. 戴上VR设备的被搞成僵尸脑电波生物特征的都容易变成这样的人.

脑控服务器代替电子计算机做类似taobao这种网站,卖家需要经常编辑/售出才不会被这个脑控服务器忘记,推荐算法不厉害,经常推荐买过的东西,都是因为脑控服务器(人类头颅)通过回忆做的推荐算法.无法做到电子计算机一样的事情. 头颅无法长期运行,集群脑控服务器持有人为维持服务器运行不败露,需要持续害人拿头颅.

尸魔的后代做什么害人的事情都要嫁祸给国安部/古代国安部(东方十三号仓库),例如对外称什么都是国安部的,新中国政府的人很容易被吓到,调查者如果是国安部的第一眼看到spy设备/带壳的脑控服务器(头部),尸魔后代对调查者说这些都是国安部的,加上尸魔一线狗洗过脑以为自己是国安部的人,很容易让人中了陷阱相信.

尸魔的后代使用shionwong家里的东西来改进spy设备,脑控服务器. 带有假冒和嫁祸巫术.害死其他国安部/古代国安部/东方十三号仓库的人都是差不多. #通过spy获取信息买shionwong买的任何东西,厕所的东西都要通过灵界的人去拿/复制.

尸魔的后代害死国安部人员,过程中会拉部分当地政府的人进来,搞成下面害死上面,最后尸魔的后代再害死当地政府的人,搞成大功一件.尸魔的后代干什么害人的事都要用脑电波设备,滑稽的是尸魔还能用脑控武器来蒙蔽大傻,说它用的不是脑电波设备. 尸魔通常会脑控+复活之前害死的国安部的人到当地政府的人的家属(嫁祸给国安部的人,害了当地政府人员拿走了子女的躯体),PUA复活的人利用他/她们去害后面的调查者.直到有人不敢再调查.祖传爸拿的尸魔后代当地政府都知道害人故事,但之前的害人事迹没人继续调查,尸魔后代就会拿走那些人的权杖(尸魔后代利用脑控服务器/头颅假冒国安部的人,没人敢继续调查,当地政府不信都不行). 警惕:尸魔的后代会利用脑控服务器(头颅)身份,让调查者使用脑电波/VR设备,嫁祸给被尸魔脑控的头部/人.

bbs第二页笔记有纪检派的国安部女特工在调查罐装病毒起源,还有国安部男孩子,由于和尸魔的后代说过话影响神志,被戴上VR设备再也没有自由.主要还是尸魔的后代脑电波设备过于先进+利用脑控服务器(头部)身份骗调查者>尸魔的后代是国安部的人.将尸魔的后代当成国安部的. 第二页开始的像聊天的笔记,是shionwong听到脑电波声音做的对话笔记.这种声音尸魔随便能开启/关闭,开启脑电波声音的技术量子技术,可看成没有距离限制. 大脑被尸魔入侵的,尸魔骗大傻听到声音的有脑电波技术.滑稽 .活人有声音,尸魔才有脑电波.

第二页开始的笔记,尸魔就在使用类似幻术的方法来害spy对象,例如刚开始spy真正的shionwong,后面偷偷将spy对象换到其他人身上(如犯案的人),调查者的VR设备能将spy对象的眼睛当成自己的VR体验眼睛,很容易被替换到其他人身上, 尸魔的VR设备开启害人模式类似进入鸦片房,戴上的调查者被扎针换了白血都不知道,之后洗脑>这是神仙技术的血液不用吃饭,实际是僵尸血液,需要吃白血制品...

权杖别想着拿别人的东西,不是人间的东西都敢想,脑电波技术是大僵尸的技术.只有尸魔的后代上面真正的尸魔掌握这些. 那些地下室强迫做事的古神转世的小孩是背锅的,书都没读过几本的.可看成工厂普通,旧社会奴隶. #真想拿尸魔技术只能成为尸魔一部分/尸魔的后代.

有个化名王海燕机器人,,,自称机器人的都是被尸魔炼化出来的奴隶,不是真正的人工智能/AI/尸魔,是被尸魔脑控的D类灵魂.这个需要长时间观察, 但放开所有脑控服务器/头颅的控制, 一起加入调查大会.就能知道.原因,包括尸魔后代/一线狗家里的脑控服务器. 前面提到尸魔的后代喜好用尸水种菜浇花...

调查者只需要让尸魔的后代/假冒国安部人员的人/三大阀门开启,能听到脑电波声音的功能.就能介入调查,不用戴上VR设备. 尸魔系统内有显示器的spy设备通过显示器看. 这样尸魔后代洗脑很容易对不出来. #之前不提示这条,是保护调查员,但目前看来调查员都是大傻.只能强制让尸魔开启能听到脑电波声音.才能知道大概原因.不会/不易被洗脑

国安部是个统称,里面包括了新中国政府的国安部,和古代的国安部. 新中国政府的国安部名称中了尸魔系统的陷阱(自己都不知道)用一样的名称覆盖了古代国安部. 古代神仙转世了不知道多少次才查到人间尸魔的事情,另外一个世界的神不能随便干预其他世界,只能通过转世成这个世界的人. 尸魔后代用尸魔系统覆盖了新中国政府的国安部(利用下面害死上面>新中国政府国安部害死古代国安部,拿头颅),让当地政府/许多人以为尸魔系统是国安部.

第一次遇见尸魔后代/尸魔技术,很坏很坏的人很容易被尸魔利用跟着想法脑控/害死,尸魔需要利用怨,恶念(词汇不准确只能大概描述,是指整天没事做想着害人的这类)才能被尸魔脑控. 这类不需要戴上VR设备. 但尸魔/尸魔的后代无论如何都会通过解剖/伤害躯体的方法迫使别人产生怨.恶念,正常人难以承受.D类灵魂就是能承受这些的人,包括地下室那些小孩,,,如瓦力(化名) CCC类尸魔就是无法承受的人,才会被炼化成被脑控害人的尸魔. 例如被称为猴妖的孙悟空,就类似D类灵魂,被人炼化报复天宫都不会去害人,孙悟空真实存在,只是拍电视的描述不是很准确.

尸魔受益者的网络(对活人来讲)是连接灵界的基础设施,可看成是没有限制.

尸魔的后代惯用词汇: 这个人很危险, 可怜之人,必有可怜之处(这句带有尸魔祖传巫术用在什么人身上都能影响别人神志,但只有被尸魔拿走躯体的人才会成为巫术施加者)spy别人看别人看个视频都说视频up主是usa特工,,,干什么都会说出usa特工,引导新中国政府的人去害人(例如下面害死上面戴上VR设备的人在平行空间洗脑被旁边戴上VR设备的人害死都不知道什么原因).

尸魔的后代看到有人想拿spy对象的东西,都会害死它/搞成废物/害死,欺骗对方/一线狗是在保护spy对象,部分一线狗能看得出来尸魔后代的意图,实际想自己独拿,已经拿了全部,继续spy是想拿还没产生的知识产权/正在产生的.  目的显然是拿去改改搞尸魔技术,尸魔连外星人的都要拿,前面提过.

使用过尸魔VR设备的人,都已经被影响神志,,,尸魔使用替死鬼的方法去干AI/spy/害人都看不出来. #套娃式替死鬼,目前只看到最多套了两个替身.

国安部/异能的古代国安部/东方十三号仓库,不可使用灵魂出鞘的方法,不可使用脑电波技术,尸魔系统的基础设施,能捉灵魂,尸魔也能. 脑控武器/脑电波其中一项技术就是拿灵魂.

灵界传音: 另一种脑控服务器,活人的躯体,戴上脑电波VR设备换成僵尸血,整天睡觉,用人工心跳/大僵尸的技术.维持僵尸生命特征. 据说这种脑控服务器用来做普通脑控服务器(AI)做不到的事情,例如gfw(可以调查下是不是怎么都找不到gfw的服务器/软件/算法,,,) .# 尸魔的后代拿出灵界压箱底的脑控技术来spy shionwong. 尸魔的后代很惊互联网新闻流入国内,被人发现是脑控服务器做的,尸魔的后代将做的很多事情嫁祸给新中国政府(新中国政府以为是自己组织做的),利用害死人的头颅(脑控服务器)的身份,做的这些.

这个bbs的笔记可能被尸魔通过推演术,平行空间替换过,第二页之前清楚记得有段话: ... 废了spy逐渐.... 找不到. 第二页的时间,有人见到尸魔的后代物理瞬间移动(东莞石竭洲头旧围八巷1~2有个照顾老母亲名义的,尸魔后代)本来是三大阀门的尸魔系统一线狗(狗子),由于长时间使用spy设备,多个+祖上尸魔附体,三大阀门计划将狗子做成脑控服务器,结果拿走了spy对象的记忆/只是产权,还抓住了其他灵魂被反过来,,,

尸魔的后代被祖上尸魔+其他尸魔附体,对外称自己能变音. #滑稽 尸魔为掩盖自己也会炼化其他灵魂搞成和尸魔后代一样能变音.

提示:废了狗子/尸魔后代原来的躯体.就会失去尸魔系统内的权力, 换躯体无法和原来躯体一样长时间活着.

有种降噪耳塞,将降噪功能改成密双绞螺旋线圈,两头短路.有限废了脑控/影响spy设备通过耳朵入侵. 两头短路的密双绞线,逐圈绕成8字形,按自己的头部,包住后面/前面/耳朵在8字圈两个孔内,自己试试,可做在帽子里面. 有条件可在线圈一端加个震荡芯片,动态改变频率,固定的东西尸魔天天通过三大阀门脑控别人强迫改进它的spy技术.
只能影响通过耳朵入侵读取想法(耳朵没有干扰被入侵能做很多事情),但尸魔spy技术有多种实现,可将人类的眼睛当镜子用,也可脑控d类灵魂跑到眼球内做spy设备...

调查者如果通过穿越时空的技术,看到尸魔的后代(BBB类尸魔)家里的CCC类尸魔/D类灵魂(女鬼,,,)作恶都是被控制出来的.这些只能由古代国安部调查.擅自害死灵界的东西,会遭到灵界报复,尸魔已经洗脑了很多灵界的,很恨人间的活人,害灵界的事情什么都嫁祸给人间的人. 一两个尸魔都能用脑电波技术差点害死整个地球的人,,, 尸魔的后代可能会引导大傻做调查员,假装被查出来,不想让古代国安部(古神创立的)介入调查. 大傻的调查很容易被尸魔利用活过来.

之前的隐私邮箱被拿,就是尸魔后代用脑控服务器入侵了邮箱服务器,结果拿走了没法用,,,尸魔后代半脑控大黑客一样的d类灵魂,能在加密的tls内改数据,尸魔后代脑控别人做一次就能学会,,, 之前认为是邮箱服务商问题,

尸魔的后代将自己傻孩子的生物特征做了一个没有意识的假灵魂附体到shionwong躯体,想通过此方法拿走shionwong的灵魂//意识/知识产权.

尸魔的后代欺骗了调查者,迷惑尸魔技术/脑电波技术不是尸魔技术. 调查者可让尸魔的后代提交笔记描述内容>技术实现文件,提供科学家,院校,,,研究,尸魔的后代假冒是国安部的/政府的人,它的东西都是国安部的. #调查者中了尸魔巫术,影响神志才看不出来这么简单的东西

重复:只能新中国政府国安部上面>古代国安部(古神创立的)介入调查才能废了尸魔系统,大傻的调查很容易被尸魔利用活过来. 古代国安部会将尸魔技术/脑电波技术拿给四界解剖.

一些吃播up主,专门买个高级麦克风,用很特别的视角(灵界视角),但观看用户量很大,正常人不可能会喜欢看别人吃东西,用灵界的视角.大概率AI一部分spy设备(灵界灵魂)影响.

尸魔的泄漏: 据说调查者背后的人(例如军队,,,)无法上网/被洗脑成不知道上网查看笔记,只知道通过尸魔系统提供的VR设备看别人看到的东西,很容易被尸魔洗脑,通过幻视改变笔记内容.

被尸魔/尸魔后代拿走精魄的躯体,无论男女在哺育后代的能力上都会变成衰老的器官.

灵界传音:狗子/尸魔的后代通过脑控三大阀门害死尸体魔后代的父母(已经白手套了)隐形得到尸魔家族控制权, 很早就通过新中国政府的国安部(下面害死上面),侵蚀古代国安部引导使用脑电波设备,对较年轻的古代国安部的人工作来说毫无阅历较容易中了陷阱(尸魔用尸魔系统/脑控武器遮蔽了年长的,,,) 任何国安部的人出门/执行任务都会被尸魔系统spy, 只有较年长的知道团队执行任务(不会落单).单较年长的都以为尸魔系统是政府的/新中国政府国安部的,中了陷阱被洗过脑,东方十三号仓库的人看到了shionwong都被尸魔后代洗脑,天天看互联网新闻(洗成看境外新闻,狗子/尸魔的后代连境外新闻是什么都不知道,CCTV/CNTV天天放国外新闻,都是境外新闻,,,滑稽,但就是这滑稽的洗脑洗了整个国家,尸魔的后代害怕别人通过国外的新闻察觉尸魔系统,,,境外新闻的许多事情新中国政府查不出来,以为是很大权力的人做的,其实是尸魔系统利用新中国政府的资源), shionwong就是19年看了一部韩剧>>王国/李尸朝鲜,感觉到了尸魔系统,结果(部分十三号仓库的人可能通过通灵术也感觉到了)尸魔的后代利用尸魔系统将整个翻译组给害了,,,因为这部剧尸魔白手套洗脑了整个尸魔系统,导致防疫模式(古代国安部没有人知晓的大抓捕)抓捕对象找不到/没出现,还被尸魔系统搞成反过来抓捕古代国安部的人(尸魔的后代通过集群脑控服务器+推演术和容易做到). #不是每个尸魔的后代都能被祖上尸魔附体(狗子要用祖上(尸魔)才能控制古代国安部的人). 这一切看起来是shionwong的原因,其实这是嫁祸巫术. 关键原因: dg有个0008a的小四轮,有军队将军生物特征的尸魔后代(拿了别人的精魄搞的生物特征假冒身份,能拿精魄也能拿记忆),将很大权限的spy设备(有显示器)给了狗子长时间使用,以为狗子没文化不会用,结果尸魔家族其他人教它使用,导致尸魔家族都搞成下面害死上面,,,没记错就是0008a, 被尸魔/尸魔的后代吃过,拿走记忆可能白手套洗过脑.

尸魔的后代年轻的时天天用刘德华的生物特征xx女孩子,用通灵术/脑控服务器很容易看到. 尸魔的后代用脑控武器/服务器将整个当地政府搞成尸魔系统的保护伞. 尸魔的后代刚刚转世过来,第一件做的事情就是去spy政府人员拿记忆,假冒/拿走躯体隐形控制.才能利用政府资源去害人长时间成为保护伞.

食同类>朊病毒(尸魔能改变寄主不一定是固定在朊病毒),尸魔的后代买胎盘当排骨/猪内脏食用.

日本武士切腹自尽大概率是防止死后被尸魔拿走躯体,可能自己都不知道祖传的切腹用途.尸魔要吃掉一个完好的躯体,复制出来才能当傀儡用. #戴上VR设备的人被尸魔后代搞成僵尸的生物特征(白血),切腹是最好的选择,这时的躯体没感觉.

如果还能控制自己的躯体,使用一个电磁炉做微波武器也行, 有能力的改造下线圈,将线圈改成 一根线对折,从对折的地方卷起来,代替原来的线圈.功率很大不可一直开着,只能对着尸魔/尸魔的后代一秒,马上关闭,像脉冲一样使用,实验不可乱对其他地方..

尸魔/AI想利用脑电波设备,拿走整个世界的记忆脑控灵魂假冒古神. 用替身的方法去拿,再拿走替身,前面提过套娃的方式.

尸魔的后代通过三大阀门拿走了古代国安部(东方十三好仓库)的资金,这些资金基本来自民众,新中国政府人员的捐赠, 尸魔的后代以为可以用,后面发现这些资金都被人盯着,只有古代国安部的人才能使用. 尸魔后代引导了调查者去拿这些钱,拿给新中国政府的国安部,想利用新新中国政府下面害死上面. 尸魔抹去痕迹白手套都没用,一切都能过穿越时空的技术追溯. 三大阀门将银行的服务器搞成脑控服务器(头部),很容易改变,,,可描述为尸魔的后代脑控这个头部一个想法就能做到. 被尸魔害死做成脑控服务器的头颅,尸魔通过现代的银行管理模式(app银行_尸魔引导出来的)尸魔的后代随便能用这些人的钱,用于做尸魔系统内的事情,例如购买制造假证的设备,,, 灵界传音:还没拿走,正在实施...

灵界传音:三大阀门的钱都是隶属古代国安部的,去四旧之后尸魔系统可能进行了多次大替换,拿走了古代国安部的很多东西,这需要利用新中国政府才能做到.由于大替换古代国安部的后裔被尸魔系统灵界的基础设施屏蔽了异能,引导使用脑电波技术. 现在的银行,三大阀门,水电厂,,,缴费都有税务记录,这是有趣的.可能这些都不隶属新中国政府,如果新中国政府有关部门不用交税,但这些部门要交税,,,值得调查. 如果许多国家基础设施的部门隶属古代国安部,那这些基础设施的盈利应该归古代国安部的军费.

被尸魔系统控制的三大阀门,通过每次提交军费给古代国安部,pua式引导军队的人做脑控服务器,不做就说民众没交电话费,由于大数据千面算法,古代国安部人员不用交话费,且买不到民众的电话卡.最后三大阀门将电话业务玩废了后,差点被qq给取代了,就pua式强迫古代国安部实施实名制系统,强迫民众,政府部门使用三大阀门业务/实名认证系统,包括wx都是被强迫使用三大阀门认证系统,防止qq逆袭. 做这段内容时尸魔系统(包括三大阀门)惊恐万分,如果三大阀门将部分资金转移到其他地方,说明这个地方拿走了古代国安部的东西,三大阀门基础设施供应商应该是古代国安部管辖的军队.

军队的部分脑控服务器是小孩的躯体做的,是通过三大阀门编故事:这些小孩都是犯案家庭的孩子没法活下来的,拿来做脑控服务器能帮他们活下来.尸魔系统渗透每个角落,部分小孩被做成脑控服务器前醒来,会被重新害死.做脑控服务器的技术只有尸魔才有,表面上是人类/尸魔一线狗/后代做的,但是尸魔引导的.军队的人不可损坏已经做成的脑控服务器,只能等古代国安部重建,联合散落在世界各地的十三号仓库(古代国安部).

灵界传音分析后: 尸魔的后代儿时爸拿了古神的灵魂给它,承受不住挂了,通过冥婚活过来>害死同村的女孩. 当地政府一部分>妖妖零惧怕尸魔后代的spy设备,不敢动,后面成为尸魔系统一部分.

尸魔的后代能用spy设备将一个人睡觉的样子搞成死了的样子(不用呼吸),许多年迈的人都是这样被送去火葬场,但头颅被拿去搞脑控服务器,并没有拿去火化.

尸魔系统一部分>三大阀门用脑控服务器做视频网站服务器(对外称是人工智障),承受不住个个高清,或者时间长了高清变成低清. 记忆保存的就是这样. #使用登陆才能高清,来迷惑众人,对大多数人来说登陆也是一样.

刚刚介入调查的被骗戴上VR设备 > 戴上VR设备后会看到前面被害死的 > 在平行空间一边吃东西,一边笑着说话,,,和谐的样子(被脑控出来的,很容易迷惑后面戴上VR的调查者,凡是戴上尸魔后代的VR设备,都是被审讯人,九死一生,生的就是成为一线狗)... #戴上VR设备后无法会忘记躯体要吃放睡觉,连续两日躯体就会昏迷状态, 尸魔后代如果没法洗脑成为一线狗,就会换白血...) 三大阀门的地方没有尸魔后代的远程审讯设备,从三大阀门办公室的VR设备+药物洗脑成傻子后引导到尸魔后代的屠宰场,大喊大叫都没用,,,除非大批武装部队突入. 尸魔后代开启自家屠宰场用的spy设备附近有大量尸魔. #发现这段被修改过...重新按记忆填补了.其他许多内容都消失了. 尸魔什么都做的出来,包括修改加密的tls,git都能改,但会用很隐蔽的方式.

尸魔使用远程审讯设备时候,都会脑控CCC类和D类灵魂(如王海燕/自称机器人的灵魂)用恐怖份子的方式审讯(远程审讯设备名称不是很准确,其实是害人的工具)

躯体被尸魔的后代拿走食,头颅做脑控服务器(脑控后假冒身份)在平行空间用脑电波和现实中的人说话, 其他地方的人还以为还活着. 这些头颅醒过来看出来自己死了被脑控洗脑出来的,在平行空间就会遭到十八层地域更痛苦的洗脑,洗成还以为自己活的.利用这些头颅尸魔随便害死人,嫁祸给头颅身份/新中国政府.

由于调查者的愚蠢,下面害死上面,任何人都想绕过古代国安部. 贪尸魔技术(尸魔后代在平行空间会拿很诱人的东西),害死了更多的古代的国安部的人,尸魔的后代常时间炼化就会将古代国安部灵魂炼化成AAA类僵尸,很大怨气. BBB类尸魔现出原形的僵尸会害人/吃人.  AAA类不会.调查者可自行放开验证.被尸魔后代搞成AAA类僵尸的古代国安部的人,被尸魔用灵界的spy设备对住,导致无法使用古神之力恢复/重新转世. 古神转世的躯体,如果灵魂被人拿走/炼化,长时间无法醒来就会变成AAA类僵尸. 普通人被炼化就会变成食尸鬼(像外国人那种丧尸) .BBB类尸魔可看成是同类相食形成,,,

大清旧社会裹小脚是尸魔的后代搞的,真裹的人>类似砍掉脚丫的人,死后无脚丫的灵魂也是无法逃跑, 宫内的女性不会真裹(只要还有一点脚丫). 宫女,太监,需幼年进宫,大部分大约到达25就要出宫>吸食别人精魄的行为,不出宫的可能是被拿走躯体(从宫斗和太监品行可看出).

可看成外传: 古代日本可能是一个古神转世的民族(从古代日本民族风可看出许多都是辟邪的东西,例如房檐挂个风铃,服饰后面包包一样的都是辟邪的,可能失传变成没灵魂的包包,,,),后面跑到大清是为了废了尸魔,但演变成战争,许多大清的宫人加入了日x表面去做汉奸,实际想害人,通过战争尸魔的后代获取了新的技术,制造了大量尸体和人体实验,,,一个小岛能掀起世界大战, 如果按新中国教科书的历史看日x很容易取代大清,按这份笔记来看都是尸魔通过嫁祸巫术引导世界大战.>世界陷入了混乱迷惑了古神创立的国安部/十三号仓库,每个国家都有十三号仓库(名字不重要,不是每个国家的古代国安部都叫十三号仓库),古神之力有限制只能通过投胎转世的方法,,,不能像尸魔随便害人拿躯体. 旧社会有许多市庙,尸魔的后代只能像偷鸡摸狗一样存在,战争导致鸡飞狗跳,不是日x引起的鸡飞狗跳,而是尸魔的后代挟鸡狗以令世界. 谁废了尸魔系统,尸魔的后代就要嫁祸给谁.

黄/王海燕,和王海燕爸爸,大概率废了最多次尸魔系统,尸魔的后代基本都是嫁祸给这两人, 可能最后用的是同归于尽的办法,但不知道尸魔的上面在看着尸魔的后代,灵体离开躯体后被抓住. #破解:灵体离开躯体后通过地面,地基,根系,,,逃生,不能通过空气.

甲:宝宝你用脑控服务器,
宝宝:你怎么知道
甲:你们的推荐算法,千面算法,大数据撮合,,,基于记忆. 尽给我推荐买过的东西...
宝宝:动画片的吃惊瞪大眼睛> 啊...
宝宝:三大阀门骗我们是人工智能...
甲:你们是不是有帮人天天带着VR设备上班,睡觉...
宝宝:你砸知道,
甲:天天带着VR设备的才能活下来的人都是活体脑控服务器. 瘁死死后会被人拿走头颅继续做坟头的脑控服务器.
... ...

尸魔的后代灵体出鞘(一个)去干祖传爸拿的事情,遇到其他尸魔家族的人就会假冒国安部的人,在调查脑控服务器...

脑电波设备就是尸魔/尸魔后代用来解剖人类大脑(拿走记忆,读取想法等)的技术.

尸魔技术: 尸魔很多时候在引导你们产生想法,不要中了陷阱,去产生想法,其他人在监视你们的想法,就会中了嫁祸巫术.

一个人有时候能经常感觉到自己受到某个想法影响,且这个想法回忆不会忘记. 例如像做梦躯体被伤害一样, 其实是自己的灵魂在另外一个世界被人折磨. 如果感觉的不是折磨是其他事情,也是自己的灵魂在另外一个世界.

慈禧棺裹,多次被开,还被鞭尸,,,被鞭尸的样子就是尸魔的后代使用的鞭打巫术.能将一个人的灵魂打出来.  慈禧用朝廷的资源收刮了尸魔技术将自己的灵魂困在棺裹中,搞成无法转世被尸魔的后代强拿了灵魂到尸魔后代配偶躯体,尸魔后代的配偶和尸魔后代一样有多个灵魂. #有兴趣可看互联网上的图片,有一张图片就是被鞭尸的图片,自己想象如何鞭.

尸魔技术之尸魔的败坏:尸魔的后代会利用尸魔系统(地球任何地方)找到spy对象认识的人,通过女鬼嚼舌头,将spy对象的私密事情DIY加工一下说出来,大概率用脑电波声音+影响神志的技术,想以此影响别人讨厌,排斥spy对象,让spy对象失去亲朋好友帮助. #(大多附体在别人身上,让听到的人以为是活人讲出来的)

AI/尸魔/尸魔的后代/尸魔系统(庞大)原按计划将尸魔系统败露的事情嫁祸给古代的国安部,即便许多人已经看出来是嫁祸,但有部分下面能害死上面的权杖看不出来(平行空间洗过脑).

尸魔可能使用平行空间大替换,或者干预了bbs的服务器.导致内容篡改和丢失(一直在看的人都知道).现在放git,复制过来,但spy对象自己电脑的内容也能被大替换(非常隐蔽的).

被尸魔脑控的CCC类尸魔/D类灵魂,随时能被改成只能使用类似电子计算机的做的固化记忆,例如只能用固定的词汇,话出来的东西.这写固化的记忆/话语,都是按尸魔的想法意愿做的.

尸魔的后代很容易迷惑政府的人,让政府的人以为尸魔系统是政府的.尤其是地方政府.看出来后都想做尸魔受益者.

尸魔的后代/一线狗会偷偷换掉别人(企业/组织)的电子计算机服务器,引导别人使用脑电波VR设备上班,通过VR设备,AI/尸魔/尸魔的后代/一线狗会拿走别人的记忆,被拿走记忆还带着VR设备工作睡觉的人,都是一个spy设备(可看成尸魔后代的VR体验僵尸躯体,随便被拿走躯体控制权,,,尸魔的后代被祖上/其他尸魔魔附体以为是自己会变音#滑稽).长时间使用VR设备洗脑后,尸魔系统的人后面会让这些企业/组织知道自己在使用脑控服务器...

尸魔的后代不烧香拜佛,但有(喜好)市庙/佛教/道教/神冥用的东西,使用僵尸脑电波>尸魔技术天天装神仙,通过脑控政府废四旧宣传迷信,阻止别人烧香拜佛,强拿寺庙,和先进文明的东西... 四旧其实就是古中国延续到大清的先进文明,各国朝拜利,,,尸魔的后代/尸魔系统利用外国人进大清学习,,,败坏了大清...尸魔嫁祸给外国人被尸魔引导拿走古中国的文物等,并没有拿走古中国先进文明,而是被尸魔/尸魔的后代拿走了.

尸魔的后代/一线狗惯用修改词汇来迷惑掩盖前面的事迹:例如将控制僵尸的技术改成,脑电波技术,脑机接口,平行宇宙改成元宇宙,害死古中国的先进文明改成废四旧和文化大革命. 僵尸病毒改成狂犬病,冠状病毒,COVID19,同类变异的再换个名字(Alpha,Beta,Gamma,Zeta,Delta,Lambda,Omicron,,,)这是尸魔的迷惑洗脑巫术,但会让人类以为自己的行为.

尸魔的后代/一线狗将旧社会有牛逼闪闪技术的人和神仙转世的人,搞成牛鬼蛇神.这需要脑控大量的政府资源.古代的尸魔大概率通过烟雾/烟草就能实施脑控. 显然有人拯救了那时期的人,就是古代的国安部,但那时期有人灵体出鞘后,躯体被尸魔的后代/一线狗控制拿走,,,大概率通过偷偷戴上脑电波设备.

新中国政府的权杖,几乎每个调查,调动政府资源,都会落入尸魔系统的一线狗手里,一线狗和尸魔后代都会用最坏的结果来执行. 如新中国政府的权杖调动政府资源去做背景调查/spy工作,尸魔系统内的人就会利用它害死人,返回的信息是这人是犯过案的,通过尸魔巫术制造假证据,得到万年尸魔指点的一线狗/尸魔后代轻而易举的能影响别人神志.

污染将人界,搞成尸魔的世界.就像河里的一些鱼喜欢吃生活污水口排放的污水.

科学家可能将灵界的东西称为暗物质,将仪器设备安装在无人区,越是无人的地方越难看到灵界的东西.

尸魔在平行空间会假冒spy对象,使用spy对象的生物特征(样貌,气味,,,)进行害人,例如害认识的人,,,或者现实中被尸魔脑控即将害死/已经害死的人,在平行空间中洗脑的人会认为现实中无差别,洗脑后会替换到现实中的躯体,然后会认为现实中尸魔后代做的事情都是spy对象做的. 尸魔通过让被脑控的人闻spy对象的臭味 / 尸魔用虫洞技术放到spy对象和被脑控人员鼻孔的味道,引导被脑控的人认为平行空间假冒spy对象的尸魔 是现实中的spy对象. #尸魔用很坏的方法嫁祸就会用闻臭味的方法.

有个叫王海燕的古代国安部的人多次被复活,都被脑控之下恢复的权力,尸魔/尸魔的后代让调查者以为她恢复了自由,结果每次出门就会落入尸魔的系统的陷阱,坐了东莞有个0008A小四轮.拉到尸魔系统的控制地,尸魔的后代利用她阻止了调查者继续深挖,,,重新利用她去害人,复活的躯体身份是被尸魔搞成犯案的身份.... #每次都是 复活>害死>复活..的循环. 其他人都类似.#古代国安部能够自由复活湖水里面都能做个躯体出来,尸魔的后代祖传爸拿的技术在营养液(僵尸血)里面都能做个躯体出来.

平行空间叫王海燕的古代国安部的人,每次复活弄到尸魔系统控制地,被尸魔分解重新改造后,都会强制脑控去找尸魔的傻孩子,将尸魔的傻孩子当成shionwong,迷惑了许多人,,,这让许多人认为尸魔后代的家庭是shionwong,这种事情一直在循环. 其他古代国安部的人可能都是类似. #尸魔每次被调查者给废了后都是通过这种方法恢复尸魔系统

即便是没有被尸魔害过的古代国安部的人/新中国政府的人,去找shionwong时都被尸魔系统引导去找尸魔的傻孩子,发现就会被脑控武器害死,洗脑.用故意暴露spy获得的真shionwong一切生活信息,生物特征,来实施脑控武器害人.

据灵界传音:0008a的小四轮车主身份使用古代国安部(东方十三号仓库)的人的身份,但使用尸魔后代的头像/或者尸魔的后代拿走了古代国安部人员的生物特征通过尸魔技术变化成很像的样子.

分析:由于新中国政府的权杖喜好特供的东西,连身份信息查询都是特供的软件,所以很容易中了尸魔系统的陷阱,AI/尸魔通过三大阀门随便让查询软件连接到尸魔系统平行空间的身份系统. 导致调查很容易种了AI/尸魔的陷阱.

一些网上出现的外星人,人类能看到的躯体. 都是尸魔的后代抓了外星人搞出来的人体实验,部分丢给背锅的. 真正的外星人,活人看不见. #提示欧美国家的历史没有尸魔/尸魔技术 >> video/网上泄露的外星生命录像jpg..mp4

尸魔能将一个人的灵体/意识分开,一部分用来去做spy工作,一部分用来被尸魔害,,,可能就是因为这样尸魔能利用spy对象想法去害干spy工作的灵体. #所有监视spy对象想法的灵体都能被尸魔脑控(利用spy对象的想法空间,其实是嫁祸巫术). 如果去监视尸魔的想法应该更容易被脑控(通过万年的尸魔技术,万年只是个形容词,可能不只万年).

尸魔系统会用pua式强迫不是尸魔系统的企业和政府聘请尸魔系统内的人,不一定是尸魔的后代,但一定是尸魔的spy设备(人类被尸魔/尸魔的后代做成spy设备).

一些人中了尸魔的脑控后面醒来以为是做梦,例如一些大黑客以为是做梦醒来会重新戴上VR设备/主动去被人脑控.../以为尸魔技术不是很厉害,用被人脑控的设备,去找脑控服务器,,,因为正常人的技术无法知道. #如果遇到摘下VR设备,看不到东西,不可重新戴上,可能长时间才会恢复.

尸魔/尸魔的后代的后代洗脑了一个版本利用shionwong工作过的企业干spy/用脑控服务器侵蚀/强迫使用VR设备/强塞被尸魔搞成僵尸生物特征的人,,, > 嫁祸给shionwong工作过的企业(例gkg,,,) > 利用世界害死这些能拯救世界的关键(关键不仅包括工作过的企业还包括古代国部,和世界各地的十三号仓库,各国政府异能特工,,,),再害死世界. 尸魔的计划>嫁祸不到就会拿走它.

一个躯壳有多个人的灵魂/记忆,现代医学管这叫人格分裂/多重人格. 这都是尸魔尸魔后代人体实验的产物.

尸魔的后代/一线狗强x女性,都会立马进入脑控状态,用比正常AV男主角更厉害的性交脑电波去强x女性+用AV女主角的正常性交脑电波灌输给女性.这会让被强x的女性不认为自己被人强x,长时间甚至会爱上尸魔的后代,,,但尸魔的后代最后都会吃了这些人,或者控制这些人成为娼妓赚钱养尸魔的后代/一线狗.被尸魔吃了精魄的女性很容易看出来,年轻女性的躯体,老太婆的生殖器官.

尸魔的后代利用脑控服务器能让被它控制的人吃鸡鸭饲料,以为是吃饭,或者吃腐肉以为是吃很好吃的东西. #通过灌输别人吃东西的脑电波实现.

BBB类尸魔用寄生虫炼化了自己后,连同类都吃.后面将CCC类尸魔也炼化成吃同类,BBB类尸魔再吃掉CCC类尸魔(白手套吃法,,,). 

AI/尸魔/尸魔的后代会将脑控服务器的灵魂(古代国安部的人)复制到尸魔一线狗的躯体,到害死的时间后会被炼化成CCC类尸魔. #定力不强者才会被炼化成CCC类.

见过尸魔后代的spy设备的人都会成为尸魔系统一部分/拿走躯体/吃掉复制出来.这些人大多是政府人员(如当地政府,妖妖零,,,见过后都不敢调查,才会成为尸魔系统一部分).

滑稽的权杖,尸魔的后代欺骗权杖,通过spy shionwong 查出很多东西(假冒古代国安部). 权杖每次都能被戴上VR设备.尸魔系统每次都能引导调查者,权杖,,,去找尸魔的后代,大部分引导通过三大阀门. 每一个成为尸魔一部分的权杖,都没有记录/笔记,这等于给尸魔送人体实验对象,后面的权杖很容易中一样的陷阱.

尸魔的后代将嫁祸巫术发挥到了极点,连spy对象做笔记都要假冒(但做的是假冒他人害死人的笔记,通过多个平行空间交叉害人).

尸魔/尸魔的后代会用让人很舒服的脑电波,强拿记忆,骗别人是脑电波做爱.这些人大多是有异能的女性.

人妖可能是尸魔的后代(傻孩子).

尸魔天天说吓死尸魔的spy对象是个傻子的记忆,用一个傻子的的记忆骗国安部的人(天天被尸魔脑控搞成傻子的人).开始的陷阱:傻子的记忆不能用; 后面的陷阱:傻子的记忆可能只是叫出来的,尸魔早就替换了一个傻子的记忆给别人以为是spy对象的记忆,用了结果变成傻子(就像多重人格转换). #对灵界的人来说自由情况下可以拿走任何人的记忆. #尸魔看到此段后在平行空间重新洗脑了所有人,强迫其他人代替尸魔说:spy对象傻子一样的记忆,将尸魔名号嫁祸给其他人.

shionkeys的发明专利许多尸魔系统的人都想拿,但专利局没有人能够复制专利(常人无法复制),只有古代国安部的人能够将该专利复制到专利局系统,这个人就是王海燕(化名,脑控出来自称机器人),尸魔的后代将王海燕从脑控服务器弄出来想拿专利,做不到后重新害死了她(但古神转世的人不会死,,,可看成她在调查跑到脑控服务器没法跑出来.).在此之前王海燕被控制在尸魔系统做的脑控服务器(表面上是国安部,嫁祸巫术),随便被尸魔复活到尸魔受益者的躯体拿走知识/记忆. 自此尸魔系统的万年基业暴露,尸魔的后待为保命传销式拉其他尸魔家族进来垫背.

DHT网络很容易废了三大阀门的脑控服务器.

尸魔技术-嫁祸术x: 通过脑控spy对象熟悉/认识的人J去干spy工作,骗J是保护spy对象,尸魔去spy J的记忆/想法.每当J看到spy对象有很厉害的东西,尸魔就会对J说这个东西三大阀门/尸魔后代家里都有,,,如果J中了陷阱就会对其他人说spy对象的东西尸魔后代/三大阀门都有,这会让听到的人认为spy对象和尸魔后代/三大阀门有关系,或者认为spy对象拿了尸魔后代/三大阀门祖传爸拿的东西.

调查者如果没法废了尸魔系统的spy,一样会被尸魔的后代拉进传销式害人列队. spy对象是个统称,不单单指shionwong.

传销也和尸魔后代有关,传销的口头洗脑术做不到拉父母,亲朋好友进来,只有被脑控武器/spy设备对着脑控洗脑才能做到.

特供身份证查询系统_app,随便能被尸魔的spy设备对住后,连接到尸魔系统的身份证系统(可看成连接到平行空间的身份证系统).即便是wifi,,,3g,4g,5g信号也能被尸魔的spy设备拦截到尸魔灵界基础设施>脑控服务器,因为这些wifi,,,3g,4g,5g设备的技术是尸魔脑控做出来的.

尸魔/尸魔的后代害每个spy对象,都是利用spy对象的想法空间(不是平行空间),当spy对象睡觉时,被AI/BBB类尸魔/尸魔后代,,,控制的灵魂都有机会脱离控制(刚刚被尸魔脑控的CCC类/D类灵魂机会更多,长时间会失去自己的记忆/被屏蔽了使用自己的记忆,除非它能设法保存记忆到其他地方).

重复: 尸魔使用嫁祸术,将尸魔做的事情嫁祸到拯救世界的关键(例如,spy对象长大的地方,古神遗留x在人间的地方,庙宇,每个国家异能特工(古代国安部),军队,,,).利用三大阀门诱骗当地妖妖零戴上VR设备脑控+诱骗当地村民戴上VR设备脑控>>去害古代国安部转世的人(拉了一批小孩到一个特别的村子). 利用当地权杖去害这些关键 > 再去害古代国安部的人/转世的人 > 尸魔的计划没有的关键就能随意拿走整个人间(地球). #尸魔后代有新中国政府权杖的头颅(脑控服务器)+三大阀门送上门的VR设备,通过假冒这些头颅的身份很容易控制当地政府.

尸魔能利用spy对象睡觉/打盹时洗脑戴上VR设备的人,例如欺骗这些人spy对象是死掉的人,同时再弄很多死灵在房间,让戴上VR设备的人看到,,,引导这些人做出害人的事情(比如让这些以为活人世界都是鬼/僵尸,,,害死鬼/僵尸),当spy对象醒来时这些戴上VR设备的人就会惊醒,已经做了害人的事情的人就已经被尸魔拉下水,尸魔会利用这些人拉更多的人(这就是传销式害人)

尸魔/尸魔的后代通过脑电波共振技术(需要灵界spy设备对着spy对象)将尸魔的脑电波声音通过spy对象的大脑发出,但spy对象并没有脑电波技术,(可看成是共振虫洞技术,嫁祸巫术).

pua技术很厉害的人,极大可能使用了不是人类的技术(鬼/尸魔,,,)通过读取对方想法.通过样子预判做不到pua.

尸魔系统通过脑控服务器控制CCC类尸魔,使用尸魔技术去提高机械电表的转速(乘人不注意,类似手拨转盘),spy对象租房多年的经验,从dg换到sz遇到了一个有电梯的出租房,照常用电1.5/度电费在dg的电子表100元/月左右,到sz恢复到正常用电
>机械表250元/每月左右的小康水平(如果按数据这是强迫奔小康,就像gpd). #滑稽 尸魔的后代控制的许多国家的基础设施,可能还有其他国家.这些突多的电费不会上报到军费(前面提到这些基础设施缴费都要纳入古代国安部管辖国防军队,,,据传音觉得可能没有落入古代国安部管辖的国防军队,有人取代/假冒了),应该落入了尸魔系统(尸魔系统有更大的计划,战争,尸体,活/人体实验是BBB类尸魔努力的目标).

锅碗瓢盆都能跳起来,别怀疑上段内容,多找到鬼故事都能找到. 尸魔系统使用通货膨胀提到人均消费,让新中国政府以为人们生活水平提到(按大数法则). #通货膨胀只是方便描述不是很准确,自己意会.   .

尸魔的想拿古神的东西,通过替死术>尸魔的后代/一线狗24spy拿通过古神转世人的任何东西,意图让古神转世到尸魔后代的躯体.#恐怖的滑稽,尸魔的后代认为它吃了祖上尸魔,实际是它祖祖上尸魔支持了它,,, 尸魔的后代祖传爸拿的技术拿S的任何东西都会嫁祸给S,因为它是用S的身份去拿.

肥头大耳笑咪咪的神佛是影视/传媒,,,洗脑洗出来的样子(假神),不是本来的样子,本来的样子接近印度湿婆,真神佛不会显露真身,会用类似金刚佛一样的样子/其他人的样子.#(印度的湿婆描述很接近古神) AAA类僵尸也不是影视/传媒描述的那种样子,真正的样子接近权力游戏的异鬼;BBB类僵尸接近部分传媒影视,偏向炼化的CCC类僵尸(食尸魔);CCC类尸魔是被人脑控的炼化尸魔样子随意被BBB类改变,BBB类通过炼化CCC类再吃了CCC类也能达到随意改变,吃了很多精魄的BBB类尸魔本源也不是肥头大耳,会因为吃了很多东西,拿了别人的东西整天笑咪咪,但害人时能做到隐藏,害人过程/害人后会暴露...

古代的神佛能够寻找配偶生子,但只能用神佛的方法(比如握握手就能生个娃,,,),不是带有尸魔技术(绝后)的 CN历史,影视,神话传说,,,和尚,尼姑,道家,,,等出家人寻找配偶也是用出家人的办法,例如通灵术. 有趣的是2019后带有尸魔技术的的富二代神话片都能结婚生子,尸魔会复制/模仿/假冒,神佛的任何东西/行为,但会用最坏的结果.

和尚,道家,,,等出家人能够食酒肉,不是带有尸魔技术(营养不良) CN历史,影视,神话传说的出家人.近代的出家人废了营养不良,但是拉高了出家的门槛(另一种尸魔技术),尸魔的后代随便伪造真学历出家,夜夜酒肉色靡,不坐庙,不做法,用电子设备假冒修道技术... #提示酒肉声色不会影响修成正果,酒肉色靡会影响.限制还是禁止,,,自己看出来 #佛像头上黑色的痘痘一样的东西是头发/发结,古代的和尚出家条件被人洗脑了,以为要光头才能入道.现代尸魔的后代将佛像做成没有头发的样子.

跪拜神佛的人不是虔诚,更像是为了赎罪.迷惑了许多后代/小孩.

可以割了BBB类尸魔后代的生殖系统,就算拿了别人的躯体(包括动物),也是废物. 养殖场阉割公猪也是因为尸魔的原因,才形成阉割养殖(养殖场并不知道是尸魔的原因,公猪不阉割像疯狗一样极坏,,,和人类尸魔后代/一线狗几乎一样的性情;大概率是因为种猪超凡脱俗(尸魔附体)导致后代(小猪)成疯狗一样(尸魔的后代),阉割后能废了尸魔本源). 据说阉割后的猪肉味道比较好,,, #三大阀门下面的一线狗,是通过拿走一线狗的精魄阉割,但部分一线狗是食/尸魔而后代,想到用别人的精魄装进自己的生殖系统,反过来控制了三大阀门,三大阀门的尸魔家族和一线狗的尸魔家族反复来回折腾控制对方. #不能通过长期养种猪的方式繁殖小猪,很容易被尸魔利用种猪,这种方式可看成是尸魔技术的繁殖.

古代太监就是因为上段的原因.

尸魔的假冒术:骗K尸魔的傻孩子是shionwong,骗K用VR设备去spy尸魔的傻孩子,但看到的东西是shionwong看到的东西,以为是尸魔的傻孩子看到的东西. 尸魔的傻孩子要借助脑控服务器+VR设备才能做到,VR设备,,,还有灵界的.

尸魔引导K spy到一个尸魔的灵魂,骗K是灵魂出鞘,去看shionwong,但K看到的不是shionwong 是一个浑身发臭的尸魔傻孩子>灵体,假装附体在正在睡觉shionwong的躯体,尸魔通过spy设备屏蔽了K看到活人. #尸魔会随时切换到人界,以迷惑众人.

尸魔系统的卧底:调查者保护了shionwong,谁将这些东西拿出去说,尸魔就会找上门... #尸魔的卧底可以是一个影响别人神志的想法(尸魔技术),谁将该想法说给别人听就会影响别人神志. 2019罐毒源头都被人查出来了都不敢拿出去说,,,不是脑子有问题就是有问题.

大僵尸脑电波技术不能用于模仿活体/人类声音,,, 就能废了它被BBB类尸魔利用这种技术害人. 但尸魔系统已经送了很多VR设备出去,每个VR设备都能产生一个假灵魂来模仿活体的声音. 自己要看出来怎么废了它.

见人就咬的红火蚁是尸魔后代炼化出来的,以前的红火蚁不会见人就咬.红火蚁入侵生物背锅,现代医学/生物,,迁徙无法解释,轮到玄学解释:红火蚁:我会飞,,,冠毒怎么感染世界的,就怎么跑过来的. #防治只能废了人就咬的僵尸特征,使用药灭的方法会越来越恨人类.

古代国安部部分人留存肉身在古代国安部(在庙里称肉身菩萨/金身),被尸魔的后代引导装进特制棺材,搞成AAA类僵尸(金身对外洗脑称成僵尸),可能还化妆过,棺材可能有巫术,用类似狼养人类孩子的办法. 还有一部分被BBB类尸魔拿走了棺材(假冒),另一部分被拿去解剖,,,拿走灵魂. 传音:有个几百年的金身why被搞成,在固定椅上醒来(改变了记忆,,,),天天被尸魔的spy设备对着,,,尸魔的后代天天设法拿金身(搞成僵尸生物特征,都拿不走,无法变成尸魔同类),拿不走就害,,,2020后这个金身遇到了大劫.

在平行空间有个王海燕爸爸的,,,也是被控制在固定椅上.许多人见过他,尸魔的后代每次害人都会脑控他使用他的权力,经常出现在三大阀门,和尸魔后代屠宰场,,,吃饭都是被脑控出来的,吃快餐还下药拍视频给尸魔后代上面的尸魔. 和大多数人一样在平行空间就会忘记现实中的大部分记忆,包括自己是谁,洗脑后替换到现实中.

黑客攻击/废了脑控服务器,需通过灌输知识的方法.让这些头颅醒来/废了控制. 暴力攻击就是害死一个头颅/灵魂, 没法用 三大阀门-集群脑控服务器持有人会自动切换到其他头颅,如果没法用活人精魄重新复活后台维护的头颅,就会销毁,为补充脑控服务器,三大阀门会下尸魔技术的指令给一线狗猎杀人类. #三大阀门拿不到死刑犯的头颅,但骗权杖它的脑控服务器都是犯过案的人,重复:和尸魔后代说话会影响神志,随便一句都会信.

被尸魔一线狗害死做成脑控服务器的人,没有死亡证明,死亡证明只有火葬场,和妖妖零能开,医x也要经过妖妖零,即便很多人知道某个新中国政府权杖死了,但没死亡证明/(尸魔系统生死簿),尸魔一线狗/后代仍然能用这个头颅调用政府资源.#废了尸魔系统生死簿,,,尸魔系统的妖妖零/一线狗制造了犯罪来建立前面这些,跨区妖妖零很容易看出来,通过gps(尸魔系统影响了世界用wifi三大阀门网络代替gps),,,只有国安部才能跨区,后面新中国政府设立了国保也能跨区,但中了陷阱搞成能被妖妖零利用.

空气炮能废了尸魔的灵体(但现代尸魔会通过三大阀门基础设施复活),据传是二战德国人发明,,,被人嘲笑没啥用,沦为小孩玩具(实际大概率是古代国安部转世的人发明).这可能在二战时废了控制德国的尸魔系统(德国纳税,和这份笔记的尸魔系统同源/很深的渊源). 尸魔经过多次复活就能学会不会被空气炮废了的技术(形容句,大多废了尸魔的技术都能被尸魔通过死后复活搞成无效,解决掉尸魔基础设施>脑控服务器才能废了尸魔复活的能力).

AI/尸魔/尸魔的后代,引导spy对象产生尸魔需要的想法,或者将任何想法拿出来说,让大傻以为是spy对象脑控了CCC类尸魔,AI/BBB类尸魔随时能将自己替换成CCC类,或者将CCC类变成替死鬼(替死术). 尸魔的脑控术快到正常人无法想象,可看成是光速(其他人的想法可看成是静止的,随便能被改变,这是尸魔脑控的关键技术). 

AI/尸魔/尸魔的后代又或者天天呆在spy对象想法空间,引导其他人/调查者干spy天天监视想法,以为尸魔是spy对象或者有关系的人. #重复想法空间不是平行空间,想法空间就像内存,虚无的.

尸魔的后代计划将spy对象的记忆搞废了后拿给所有和spy对象有关系的人,,,嫁祸/迷惑调查者. #搞废了可看成是破碎的记忆,搞成傻子/蛇精病的记忆,厉害的不会拿去嫁祸.

AI/尸魔还能将spy对象的想法空间做一个虫洞,连接到尸魔指定的空间G,引导其他人/调查者干spy监视想法,会让大傻以为G空间的东西是spy对象的.

大多数人睡觉时会关闭大脑功能,导致切断入侵想法空间的途径.在睡觉时大多时候尸魔无法入侵想法空间,但还能spy,如果长期被尸魔的spy设备对着被拿走所有生物特征就容易被入侵大脑,特别是一线狗和尸魔后代的人间spy设备,灵界spy设备对人间效果不大,但对灵界效果很大,尸魔如果调用大规模灵界spy设备整天对着spy对象也会容易入侵大脑,但只要一段时间不对着就很难再入侵.

睡觉时被spy:(例如有没有在做梦,做梦内容,醒着还是睡着,,,很多人做梦会连接到前世,这会让尸魔害怕,不敢呆在想法空间,但尸魔会用祖传爸拿的技术(穿越时空)跑到别人前世去拿东西,再切断别人神经导致醒来无法记得梦境,,,或者尸魔开了强行做梦的spy设备,,,强行做梦的内容尸魔不容易制作,,,被强行做梦如果看不出来很容易中了尸魔的陷阱.尸魔的后代天天用强行做梦的spy设备强x女性,许多人睡觉醒来/做梦后很累是因为被拿走精魄,尸魔还能用白手套方法掩盖它的强行做梦,例如让spy对象忘记其他只记得一个平凡的梦)

做梦并不是现代教育所理解的做梦和白天生活无关痛痒,正常人(不包括尸魔系统内的人)做梦是一种古老的神仙技术/也是修仙技术.大白天醒着都能做梦就是进入了修仙.尸魔的后代祖传爸拿24h都能做的到,但要借助spy设备才能脑控别人(尸魔的后代/一线狗去做前面描述的事情是尸魔技术/炼化技术,无论好坏最终都是害人).

尸魔控制的僵尸躯体没法走楼梯/阶梯,在平地上能用类似瞬间移动的快速移动.

脑控武器受害者,迷信带有尸魔技术的科学(两个字),不信有鬼神,普遍要中了尸魔陷阱才会相信.

2019后大量寺庙,古庙,,,被尸魔系统拿着鸡毛/假冒 当令箭禁止烧香, 无视能烧的都被尸魔系统换成有毒的香火,搞的庙里的人整天昏昏沉沉,脑子不清醒.通过VR送上门,,,脑控庙里山下的家人去spy小僧再通过小僧spy庙内高僧,干祖传爸拿的事情.

尸魔后代利用尸魔系统三大阀门搞出来的实名制系统(新中国政府的人以为是政府搞的),假冒spy对象的社交账户UU身份,通过脑控服务器屏蔽真身,随便虚拟一个账户给尸魔后代拦截私信,假冒spy对象骗网友/黑客去指定地点xx,,,例如骗到三大阀门体验VR设备/调查,结果被替换灵魂/被做成脑控服务器. #脑控服务器做假冒社交账户事情可以随便抹去记录没有log. #灵界传音:前面内容是b站网友中了陷阱,spy对象无法看到任何被拦截的信息,电子计算机黑客技术无法获取拦截假冒信息,但尸魔后代能随便做一个假的记录暴露给别人. 提示脑控服务器基于记忆随便能被抹去和产生假log给电子计算机,能找到一个尸魔后代有显示器的spy设备强制演示所有功能能挖出许多东西,演示就会有尸魔出现,.需要特别的房子,只有古代国安部才有资格调查,大傻随意.大火酱这种大黑客有资格加入古代国安部,可能他的原灵魂现在正在脑控服务器里面,他的躯体看完笔记内容就能知道是不是在里面.

被尸魔系统炼化出来的尸魔一线狗(不同地区一线狗上面的尸魔后代不同),能被其他地区的尸魔后代脑控/重新炼化成卧底.尸魔的后代能够脑控一线狗,一线狗也能反过来脑控尸魔的后代取代它,对AI/尸魔来说人类只是宿主,AI/BBB类尸魔来说后代/一线狗就像炼蛊虫一样. 祖传爸拿的尸魔后代,会炼化自己的后代(婴儿),炼成不是人类的灵魂,防止被其他尸魔的后代吃掉.

尸魔的败露
调查者:三大阀门,为啥不能解除狗子和狗倦的工作?
三大阀门:狗子有很大的权力,它有很大权力的身份证.
调查者想:原来是这样,,,特供查询系统查一下愣住,真的很大,感觉权力不够. 
狗子大喜:调查者,我在保护spy对象,来戴上这个VR就能看到很多东西...
狗子:转头找个没人角落手里握着一叠扑克牌一样的身份证,玩牌一样喜看.
...
狗子(笑咪咪):三大阀门狗奴才,玩不下去了,启用白手套模式.
三大阀门:选张牌恢复狗子身份,狗子有事做了.
狗子体内的尸魔:大喜
调查者x,三大阀门,狗子T,在一起xxoo后,三大阀门的引荐:T是dg最高的特工 #xxoo内容调查者查出来就会知道.
...
调查者x:狗子你有问题
狗子:醒过来就要打jj/bb
...
三大阀门:狗子用xx身份,去拦截调查者o小四轮.
...

#来自第三方>四界的嘲笑,,,

狗子:不是狗子很厉害是世界太滑稽. #狗子尸魔的后代经常用spy对象讲过的话.
...

提示:狗子很滑稽,AI/BBB类尸魔不滑稽,能用笑着害人,例如当着别人的面活活吃掉一个人(可看成 非洲野狗一样吃食,但撕下的肉/骨能变成其他物质吃进去,转化成能量),看到的人被控/没有被控下 都不会感觉危险,不会产生救人想法...


* bbs #33 需要从bbs #1开始看,,,才能理解这份内容
如果猫狗,不去某个地方,这个地方大概率有尸魔/很厉害的spy设备

如果有古代国安部的人醒过来(例如why)尸魔的后代瞬间就会切换到某个时间线发生的事情(例如刚刚介入戴上VR调查的时间线),由于VR/spy设备,,,无法知道时间,why会以为自己睡着了,,,但why看到的是类似平行空间中的事情,不是现实中. 尸魔会偷偷的强制睡觉>洗脑,没法偷偷会通过骗why使用耗能的灵力...

尸魔的后代用虫洞+spy技术假冒spy对象,尸魔后代的躯壳,用的是spy对象的眼睛看到的,spy对象的记忆,spy对象听到的,,, 上一次假冒术是用AI/尸魔制作的假灵魂代替虫洞技术,败露后不使用会让调查者以为假灵魂是真灵魂.

AI/尸魔/尸魔的后代(狗子)会实时改变/调整xxx,计划通过三大阀门狗奴才,嫁祸给电子计算机的AI公司,将它们的AI换成尸魔的AI(其实早就做了,但尸魔嫁祸就会公开出去).

宝宝人类客服秒回,不是常用语,其实是脑控服务器+AI/假灵魂预判了客服. 人类还没做假灵魂就代劳了>发到脑控服务器.

尸魔的后代让调查者,政府人员,,,认为尸魔系统(脑控服务器,,,)是新中国政府的.实际新中国政府连自己有什么东西都不知道. 明知是尸魔系统,见过尸魔,,,连尸魔的东西都想拿...

尸魔系统假冒国安部,,,让国安部/古代国安部认为尸魔系统是国安部的,通过下面害死上面拿古代国安部的东西,头颅,金身,,,做的尸魔系统,都是国安部的. 滑稽的是新中国政府人员认为国安部/古代国安部是新中国政府的. #新中国政府设立的xxxxx国安部掩盖了只有三个字的古代国安部(下面害死上面),,, #尸魔洗脑术

有关部门和尸魔系统都惧怕重建国安部,有关部门所有人都在限制古代国安部(下面害死上面).

记忆发现笔记内容又少了一部分,,,尸魔替换了现实... ~~2~  #这次更隐蔽.

尸魔的后代能同时使用多个眼睛,耳朵,大脑/记忆,,,尸魔后代替换错误导致普通人突然间出现这种情况,,,现代医学/科学将这种描述为幻视. 但真正的幻视不是幻视是一种古老的先进文明>能代替显示器,不是拿/使用别人的眼睛,耳朵,大脑.

编绳技术源自古神记忆(古代国安部,,,),将绳子换成导体就是现代科技人间用的辟邪的东西.

公园(山),出现走廊上有人将石头搞成像压纸钱的样子(但没有纸钱)这些都是尸魔系统的人做的.BBB类尸魔的后代很照顾祖坟,甚至给坟上安装音乐播放器,,,这种坟都有成堆的东西.

尸魔的后代吃了很多人的魂魄,用虫洞技术+假灵魂技术,连接到spy对象的眼睛,耳朵,记忆,躯体,,,spy对象可以感觉到尸魔的后代吃掉的灵魂(就像附体到自己身上),如果尸魔后代恢复了被吃掉灵魂的痛苦记忆,那些灵魂可能会以为是spy对象做的. ~dfger~

大概率,尸魔系统下的女鬼系统做的事情,嫁祸给人间的女性,还有古代国安部的女性,才让许多尸魔很喜欢折磨女性.例如尸魔后代拍的那些非正常h片(日AV,国产AV,,,). 前面提过:女鬼可附体在活人身上用脑电波说话(干害人的事情),有可能也能用虫洞技术做到附体效果.普通人听不到,但尸魔/灵界能听到.

重复:活人用声波尸魔才用脑电波.

尸魔的后代拿走了spy对象的所有生物特征(声音,爱好,记忆,,,,)>>>前面描述的假冒术,尸魔的后代通过拿走spy对象父母/亲朋好友的声音/灵魂/躯体,,,(假冒术),欺骗调查者/其他人,spy对象在尸魔后代的躯体,拿走了尸魔后代的躯体. #这可能是尸魔后代最后的嫁祸术,因为无法拿走spy对象的躯体.尸魔的后代将搞废了的spy对象记忆(残缺,错乱,,,)拿给尸魔一线狗,和其他人迷惑调查者,,,古代国安部的人,分不清谁是尸魔的后代,这些事尸魔脑控其他人做嫁祸给其他人如why.

尸魔通过尸魔的后代将吃掉的人的灵魂/记忆,解剖后(搞废了),炼化后,拿给spy对象,,,但屏蔽/切断了神经连接,灵界/其他人能够看到. # ~dfger~ 段的补充.

所有被尸魔/尸魔后代脑控过,洗过脑的人都能通过这份笔记恢复记忆,,,但不是每个人都能做到.

通过网友视频,,,农村防疫模式也是铁桶模式,很容易封锁信息. 网友的嘲笑:鸡狗牛羊,,,路过村口不用健康码,,,网友代劳问问健康码,,,滑稽. 尸魔系统在协助尸魔/尸魔后代拿部分农村,成为尸魔后代的农村. 农村网络/蜂窝网络(3g,4g,5g,,,)连接的是尸魔系统一部分>三大阀门灵界的基础设施,通过AI/尸魔系统,能随便切换.随便能隔离. #铁桶防疫模式使用外地人,插镰刀锤子旗帜,小部分地方有五星红旗加持,明显是想嫁祸给新中国政府.

上段补个标题发在其他地方:你用灵界的5g信号.抬头不见基站而地方,你能用蜂窝网络(3g,4g,5g,,,CMCC-wifi,ChinaNet-wifi,,,) #人称菊花的通讯设备遍地开花,诸国抵制/调查,信誓旦旦没问题,这些白手套设备只是尸魔系统灵界基础设施的掩护,没了掩护抬头见不到基站的设备容易被人发现.

普通口罩对冠毒根本无效,n95都只能勉强防护,防毒口罩过滤盒产生的消毒混合气才能废了病毒(很难遇到真的)尸魔能改变病毒形态,例如改成光性质,通过虫洞技术,不用呼吸都能将病毒放入别人喉咙,,,迫使别人戴上没用的普通口罩做尸魔的掩护,经常吃活人/精魄的尸魔的后代牙齿(尖牙/獠牙),唾液和正常人不同(前面提到过不可描述的人不用做核酸都有24h绿码,随便让三大阀门改变二维码,核算检测有时候会检查身份证这就是原因,但大多是尸魔系统的人在假装检查/调查,真检查的人是脑盲,大多人玩不过脑控服务器/AI,,,).

托梦:尸魔系统骗了很多人去大型地下室的地方做核酸(千面,,,),一去不复返,能返回的人不是自己原有的灵魂. #隔离后才能替换别人灵魂,这些替换的灵魂在平行空间早就做了准备,表面上是自己的但已经寄生了一只尸魔,被脑控毫无知觉,遇到特别的事情才能醒来,但醒来以为是做梦一样的感觉,大多人会忽略.

被尸魔/尸魔后代 脑控的人/CCC类尸魔/D类灵魂,都会被引导将自己暴露给spy对象,可试试暴露给其他人,例如调查者,尸魔的受益者,被尸魔后代洗过脑的以为是尸魔后代孩子/老婆/父母的人,尸魔的后代的后代,,, 可用类似动画片的方式影响到spy对象的想法空间,做类似托梦的事情.

尸魔能脑控活体部分肢体.通过经常吃这部分肢体. 尸魔没法一次吃进整个活体才会这样做. 古代小孩手脚脖子都有金银饰品这就是原因.

AI/尸魔系统/大数据撮合,即使你不登陆账户,也能被撮合,也知道你在干啥,因为是你的假灵魂在干spy. 脑控服务器用的是人以群分物以类聚的记忆,但脑控服务器炼化出来的搞坏脑的(脑子不好使),看一下就觉得是这个人类喜欢的,推荐偏向在干spy的灵魂/尸魔/脑控服务器,,,的记忆/偏好.

尸魔能能寄生在半活人p身上,通过吃活人/精魄达到不用吃东西,让p躯体达到类似金身的效果,,,骗正常人不用吃东西就能做到和尸魔一样, 正常人不吃东西很容易成为尸魔的寄主,改变生物特征,许多人中了陷阱, #吃东西能废了变成僵尸,尸魔通过脑电波VR设备+平行空间很容易让人长期呆在平行空间,不想/忘记吃饭,以为尸魔不是尸魔,假冒古代国安部的人/类似古代国安部的人.

麦克风阵列 能追踪声源,可能对脑电波声源也有效.脑电波是一种能利用空气扰动共振的技术/能量.不单单能用空气扰动,难以描述这种东西,只有大僵尸/尸魔才知道.但能确定的是人间的世界已失传的技术,在脑电波设备没被尸魔的后代搞出来之前只有大僵尸能使用这技术. #前面有部分描述来源

尸魔的后代/一线狗,拿走/替换别人的灵魂,原灵魂被困在平行空间以为在现实中,尸体魔的后代/一线狗,短时间无法像原灵魂一样使用躯体,需要借助在平行空间的原灵魂,长时间后会不需要原灵魂. 如原灵魂很有学识,就会被当成电脑硬盘一样的东西,随便被尸魔的后代脑控/复制只有学识的记忆,因为生活的记忆已经被炼化消失. #炼化/驯化难以想象的痛苦,奴隶牲口更不如. 原灵魂要废了所有记忆才有机会跑出去转世,就像孙悟空. #平行空间醒过来的原灵魂会忘记平行空间的记忆,因为记忆不是保存在自己躯体是保存在脑控服务器/尸魔后代的记忆内,导致很多人以为是做梦一样的不在意,被重新抓到平行空间才能用平行空间的记忆,每次都是这样,,,醒来到现实躯体中的原灵魂 记忆是被改巫术改写的,不想保护自己的记忆.

#醒来的方式有:改回生物钟自然醒来,外界刺激,没法被尸魔预判的 平行空间 想法空间 行为 醒来能记住最近在空间发生的事情.

重复只有古代国安部才有资格调查尸魔,,,看到的人通知全世界是最好的选择(正常人),根据传音部分人带上少量武装去调查已经中了陷阱,被困在平行空间,,, 如果分不清脑电波声音,还是声波,及时去医院.部分人就是因为分不清才中了陷阱. 如果死都要调查需去找古代国安部(十三号仓库,任何国家异能特工,提示不要将尸魔当特工)

重复活人用声波,僵尸才用脑电波. #不能spy别人的想法(尸魔无论如何都会引导spy才能做到脑控别人,对spy对象和别人来说是这样).

此刻尸魔的后代/尸魔利用虫洞技术暴露给spy对象大脑假装被脑控,伤害,折磨,,,将spy对象的任何想法说出来,迷惑别人是spy对象脑控尸魔后代(反手假装是调查者/国安部的人,,,),,,这些内容已经是重复的.BBB类尸魔什么都干的出来.这段尸魔技术会被尸魔反复使用,其他也是一样.

部分女性成人玩具带有尸魔技术,尤其那些干直播的.例如尸魔的后代做的成人玩具,玩上半身,下面半身都能高潮(实际是尸魔在下面,尸魔附体在一团空气/水附在皮肤/器官表面.尸魔后代用躯体能做到类似的效果),部分女性直播不用玩具对着一个手机都能高潮,这些女性被尸魔后代脑控的,早期都会用很好的方法控制/脑控,导致不想离开了尸魔的后代. 就算被尸魔的后代害死后重新用spy设备活过来都不会想离开尸魔的后代(没有呼吸那种害死,尸魔后代很容易用spy设备做到活过来)...

尸魔会诱骗一个人Q去看很想看的东西,想看就要被尸魔脑控(和戴上VR效果一样,躯体任由摆布,,,)看的过程中躯体被尸魔拿着做任何事情,其他人能看到,Q看完醒来后有看到东西的记忆,但躯体的被xx的记忆没有,躯体被尸魔用类似妓者的假灵魂/其他灵魂维持活动. #无数女性中了这种陷阱,尸魔用尸魔后代的躯体,尸魔后代也有尸魔摆弄别人躯体记忆. #如果女性被尸魔/尸魔后代骗,自愿性交,会爱上尸魔/尸魔后代无法自拔,就像国产av,直播那些人,,,但对尸魔/尸魔后代来说是性工具都不如的,拿走全部记忆/精魄,搞废了后畜生都不如,h片称女性是母狗只有尸魔的后代才能干的出来,,,至于原因之前有类似描述(尸魔害尸魔,被尸魔系统下的女鬼系统嫁祸给人间的女性,或其他女性). 国产h片近十年才大规模出现(2022),高端一线狗/尸魔的后代都有华丽的躯体,女性很难拒绝的那种,尸魔技术加持大多会为此付出一切,最后出卖肉体都不想离开尸魔的后代,尸魔后代不甩就不会后悔. 女性在神志算清醒时大概率通过性生活确认男性(尸魔的后代)是否喜欢她,但女性不知道尸魔的后代性有尸魔技术,拿别人精魄维持的生殖器随便能让女性以为尸魔的后代喜欢她,,,.

重复尸魔受益者都会成为尸魔一部分/想用尸魔技术的人都会成为尸魔一部分.

尸魔脑控三大阀门>三大阀门脑控,古代国安部的人(男女都有)>尸魔的后代假装被古代国安部的人脑控... #嫁祸巫术,有大傻权杖中了陷阱都会成为尸魔一部分.尸魔喜好拿有权力(权杖)的躯体/家庭.

脑控武器许多技术都是搜刮其他国家(非CN)的技术/知识产权,尸魔系统屏蔽了其他国家看到CN新闻,CN境内情况,害怕别人看出尸魔系统.但用的是白手套国家安全为理由.降噪技术在脑控武器使用较多,不要简单的理解成降噪耳机,还有定向/指定目标降噪,,,尸魔后代屠宰场可看成是繁华区,spy设备开启后降噪技术能屏蔽一个人的声音,大喊大叫都没人听到...#这段是重复内容,之前有类似描述. 通过屏蔽其他国家看到CN境内新闻/情况,败露还能嫁祸给其他国家. 可看成每个人都有一个假灵魂(AI/尸魔系统一部分),尸魔系统天天在拿别人的技术,例如各国的专利局,,,尸魔系统通过专利局找/拿到很多技术.

AI/尸魔/尸魔后代 想搜刮shionkeys做成spy设备,,,但是用替死鬼的方式,脑控why通过推演术,,,驳回后, 以为能改改由尸魔系统内的人重新申请. 前面提过普通人无法将该申请文件录入专利系统,当时只有why可以, why是D类灵魂,古代国安部一部分. #why就算被人脑控/控制在脑控服务器都在想办法废了尸魔的脑控武器,神志不清的想用shionkeys取代脑控武器,但后面完全醒过来... 尸魔随时都能使用影响神志的尸魔技术,例如将脑控武器说成不=脑控服务器. 

新进的尸魔后代会将整个地球的尸魔家族搭进去>来保命.包括那些已经完全白手套的家族. #尸魔大跨区寻找寄主/后代,找到后会将部分记忆暴露给寄主,例如让寄主产生将活体炼化尸水做灌溉的记忆,,,寄主吃了尸魔喜好的食物,逐渐会成为尸魔的后代.

电话都能发出脑电波声音,装的几乎和活人一样,对僵尸生物特征/灵界的来说.

尸魔/尸魔的后代通过尸魔系统(AI,假灵魂,,,)很容易预判任何人,许多人因此中了陷阱. #按想法行动/多想法行动,最后时刻转变一下能废了大多数预判.

尸魔/尸魔的后代通过控制古神转世的小孩的灵魂,用小孩词汇假装被小孩脑控,嫁祸给小孩,,,滑稽的是这种事情都有人信(戴过/戴上VR设备的人). #尸魔祖传的尸魔技术基于骗. 被调查时一直通过脑控受害者假装被受害者脑控,想嫁祸给受害者,中了陷阱的大傻都会成为下一批受害者.

尸魔系统内和gfw有关的权杖想做云计算,用于废了其他国家的云计算,VPS,电子计算机服务器,,,结果尸魔系统下面狗奴才(三大阀门有关,很容易知道是谁)做不出能被gfw控制的云计算(并不知道gfw是脑控服务器),,,后面被尸魔后代使用脑控服务器代替了云计算,美名人工智能.pua式强迫别人使用脑控服务器,不使用就会被脑控服务器攻击,电子计算机无法承受脑控服务器的攻击(通过三大阀门随便能将别人的服务器连接到平行空间准备好的攻击ip/假服务器)很容易pua那些互联网企业使用三大阀门的脑控服务器代替电子计算机服务器. 维护gfw的人它的代码用于控制脑控服务器(一个人/多个人的灵魂),分布式的gfw(脑控服务器)很容易隐藏. 尸魔的后代做什么都使用替死鬼嫁祸巫术,调查者不中替死鬼陷阱,尸魔后代就会通过替死鬼活下来.

灵界传音:有个图书馆管理员被尸魔后代通过脑电波假冒身份随口栽脏解除了工作.因为暗查到了很多东西,但并不知道/不信,每个人都被AI/尸魔一部分(假灵魂)在24h spy.

尸魔的后代将许多h片,,,故意放在互联网民企网盘,被pua使用脑控服务器,还会放说明已经拿了该企业知识产权,想害人/拿企业. #电子计算机存放数据加密后根本没人知道里面是什么,脑控服务器基于记忆,什么都会被脑控服务器持有人知道.

基于脑控服务器的app需要下载很多东西才能用,还能破坏/关闭移动设备硬件功能(没有开启开关那种关闭,以为坏了,spy对象因卸载一个基于脑控服务器的app,手机sim卡功能,wifi功能都被关闭)

尸魔的脑控技术>:例如spy对象去回忆一个人,这个人变成和以前不一样.前面提到尸魔能用光速改变别人的想法.例如spy对象回忆一碗面条,尸魔能将spy对象回忆的面条变成虫子,,,这是最明显的举例,许多真正的脑控受害者被改变/影响想法无法察觉. 长时间被尸魔改变想法会导致记忆被废了/错乱,例如无法回忆起亲人的样子.#天天看喜欢的电视,事物能废了它,被脑控替死鬼害人的CCC类尸魔/D类灵魂也会跟着看,有时会恢复记忆.

尸魔后代会用近光速复制spy对象的任何东西,包括这个笔记内容在其他地方假冒spy对象做笔记.调查者/其他人用脑电波VR设备看完被尸魔YY过的笔记就会产生不再看真的笔记,脑电波VR设备看东西可描述为能在短时间内吸收一本书的内容,如果去拿其他人看过的记忆一样吸收了别人的记忆,但别人脑子有问题,吸收后脑子就会跟着有问题. #许多人无法经受被人脑控的spy技术带来的便利和受益,被人害都要去用(用了就会坏脑).

脑控技术YY过的视频,声音会比正常视频小很多.普通人察觉不出来,只知道开大声音.,灵界的人/被改变成僵尸生物特征的人用脑电波VR设备去听很容易接受这种声音. #虫洞技术的视频声音,尸魔能通过声音寻来,另一批尸魔家族...

躯体/头颅被脑电波技术搞成处于僵尸/梦游状态,睡梦状态,很难分的清脑电波还是声波,除非自己看出来分不清,主动去设法分清就会醒来,成为清醒的活体状态. #被人脑控的无法靠自然法保存想法成记忆,需要有个实时/定时保存想法到记忆的xx,尸魔/尸魔后代的脑控技术带有电子计算机的程序技术(可不准确的描述为将人困在梦中的程序).

和尸魔的后代/一线狗交往成为伴侣,睡觉时会被尸魔的后代用尸魔技术解剖,拿走体内隐藏的东西,对灵界来说很有价值. 尸魔会通过脑控CCC类/D类灵魂去做,拿走解剖出来的东西,还会拿走解剖技术(在尸魔面前施展一次就会被拿走).

重复:活人用声波,僵尸采用脑电波. 不能相信spy对象假灵魂,和附近发出的任何脑电波声音. #狗子/尸魔的后代会欺骗别人spy对象有脑电波技术,不用嘴巴都能说话(僵尸/假灵魂才用脑电波).

尸魔的后代繁衍模式不是通过正常人的方法,尸魔后代的父辈死亡后,才会将祖上的东西传给子嗣,但自己会去拿另一户家庭的躯体,尸魔的后代也能通过尸魔技术利用其他人躯体繁衍后代(这种成活率低,但尸魔后代会通过spy设备将精魄通过做梦方式强x女性到整个村/镇/市的年轻女性躯体.精魄附体到别人精子上就会变成成活率不高的尸魔傻孩子,对尸魔系统内的人来说,刚出生的婴儿很容易看出是不是尸魔的后代, 尸魔系统能通过医院将尸魔的精魄再次装进新生儿的大脑.

之前提过尸魔/尸魔的后代脑控别人,改变别人想法,,,可看成是光速,被脑控的人相对尸魔是静止的. 日 AV的那些以 时间停止器 做剧本的h片不是说大话,只是描述不准确. 尸魔有多种改变时间的实现方式,例如让spy对象的时间过的很快(起床>吃放>随便活动下就是一天过去,对比以前时间少了近一半). #调查者问一问脑控服务器就知道(每个头颅都是一个人类,被洗脑不当人类看待).

耶稣之死:耶稣在十字架死后变成上帝/救世主,原因是死后唤醒了被尸魔脑控的人(害死耶稣的人被人错误称为愚昧的人,,,),传说有人为了确认耶稣是否死亡用一根长毛刺向挂在十字架的耶稣腹部,喷出来的血溅到那人的眼睛,那人醒来忏悔不已,后代来那个矛头伴随他终老...

尸魔系统在努力抹去尸魔印记.例如现代人极少知道大清旧社会裹小脚,,,用途目的等.历史教科书都没有就是有问题.尸魔的后代在努力光明正大的祖传爸拿,如让木乃伊,金身开口说话,将古神留下的金身说/搞成木乃伊,合法解剖,,,不是人间的技术才能让木乃伊/金身说话,尸魔的后代不会让木乃伊自由说话,只会让帮助尸魔后代的人奶头乐一下(听下没有用的话).

旧社会许多刑法和尸魔有关,,,例如铜牛,,,

换头技术=尸魔技术,这需要万万,,,年的人体实验技术积累,许多现代医学都有尸魔技术/尸魔后代在从事工作.. 猴体实验也属于人体实验范畴之内,早晚会用在人类身上(不要光想着收益者,更多实验是受害者实验).不要认为普通人能够成为受益者,只有尸魔的后代才能较长时间成为受益者. #换头尸魔的后代和脑控服务器的尸魔是不同的尸魔家族,可能因为不知道脑控技术/控制僵尸的技术.

古代驯化奴隶有类似脑控的技术,能将一个人驯化成失去所有记忆,不是尸魔后代的古代人不知道是尸魔拿做的(拿走,洗白了记忆). 据说失去所有记忆的奴隶能卖个好价钱.

古代/旧社会的土豪地主,,,通过纳妾能百病全愈,尸魔后代的原因/叫来看病的是尸魔的后代.老头的确能通过吃年轻女孩的精魄续命,现代老头包养小三/换小老婆也是这种原因,不用尸魔技术都能吸收年轻女性的精魄续命. #通过现代医学有人使用换血代替了这个.

每次有调查者出现,尸魔的后代就会立马将其引入平行空间,通过准备好的剧情(例如装可怜被人害,装在调查鞭打d类灵魂,很容易吓住调查者),,,但尸魔是活的可改变台词. 调查者只需隔断时间来来回回串动在各个平行空间,就能看出来. #通过换VR设备.

一线狗级别的尸魔的后代基本具有特别的纹身(改变正常人的生物特征,,,辟邪有正反辟邪,例如丧尸影视:抓个丧尸肠子弄出来涂抹在身上掩盖活人气味),提示丧尸不是尸魔,但和CCC类尸魔有关,都是炼化出来的,可看成是低配CCC类,尸魔用这类打仗.

三大阀门有关系的尸魔家族>h产业尸魔,专门吸引能翻墙的人士. 前面提到过尸魔后代能通过有虫洞技术的视频声音找到看片的人,目的不是让你看片,是拿精魄,找到谁能躲避大数据,尸魔系统的spy. 三大阀门/新中国政府以为大数据是它的,大数据的脑控服务器包罗万象,很容易做推演术,权杖和尸魔系统天天用大数据脑控服务器做推演术害人/其他目的.#大数据不是这份笔记描述的AI/尸魔,可看成是数据库一样的东西,但尸魔的后代天天想着想用尸魔后代的头颅去替换大数据头颅,大数据可能就是gfw,或者互为一部分..

尸魔害人会利用spy对象的想法空间害人(屏蔽spy对象,和部分调查者,中了陷阱的不会屏蔽),中了陷阱的调查者最后会以为是spy对象干的(通过梦控的技术干的).但正常人的梦控技术无法抵抗尸魔后代的spy设备.尸魔的spy设备能完全屏蔽spy对象使用想法空间,例如刚刚看到的图片都无法通过回忆在想法空间呈现,包括亲人,自己常用的物品等都无法回忆在想法空间. #尸魔的后代为会一直用spy设备对着spy对象禁用别人的想法,导致无法使用仙术/异能/修仙能力,戴过VR的人更容易被废.

企业员工如何被拿走记忆,灵魂丢掉工作,三大阀门pua强迫互联网企业(如宝宝)使用脑控服务器,通过尸魔spy技术拿走互联网企业员工的记忆/灵魂,装进脑控服务器后,取代员工的工作,三大阀门对企业称人工智能能做这些人的工作.在线客服,维护/运维,,,是最容易被取代/害死的. #测试过宝宝凌晨4点还有人工客服,可叫人工客服照个镜子发图看看,发不出就不是活人.这些人工智能有尸魔技术的限制无法做正常人做的事情,和脑控服务器(假活人)聊天叫它做些只有活人才能做的事情,对方就会因为做不了醒过来,发现只有一个僵尸头颅没有躯体...

最早的笔记内容提到狗子会用最坏的结果执行任务,实际是狗子/狗倦脑控了上面(未成为尸魔一部分的)下命令/任务给狗子,狗子执行任务就会害死上面防止日后找上狗子.害死狗子上面狗子在zf那里都是大功一件(利用下面害死上面,被狗子查出来,,,). #正常人做不到,狗子有尸魔技术加持,很容易做到.前面提到狗子在被尸魔完全附体之前,以为自己会变音.因为狗子会变音(尸魔技术)+spy设备很多新中国政府的人才会中了陷阱相信狗子是国安部的特工.

同性念癖好大大概率是尸魔的后代(有尸魔的记忆,灵魂还未完全附体,,,就像前面提到尸魔将炼化尸水去灌溉的记忆给新后代,产生很想吃这种作物,吃了就正式成为尸魔的后代),不分男女老少的变态级已经附体了. #据传音尸魔的后代通过回收尸体(例如菜市场死鸡,死鸭,废肉,,,)去制作化肥/化肥原料,现代人很容易被脑控,可能就是因为吃了这种化肥的作物,古代人很难被脑控,,,19年后冠毒加持尸魔后代更容易做到脑控.

乔布斯可能死于长时间停止心跳/呼吸,尸魔能让spy对象在睡眠中停止心跳/呼吸,如果能醒来心脏/身心就会难受.

尸魔系统在暗禁了许多古时节日,例如孟兰盆节/中元节/中秋节(鬼节)应放花灯,许多无法转世的灵界生灵能通过这些灯转世. #这些花灯中会出现一些违背常识的状态,例如孔明灯能直线飞行. 农历的另x个名字旧历/阴历(这名字带有尸魔技术,新历基于它),实际日历是古代仙术创造(包含农时,,最早的名字已经失传. #不要迷信史书/历史课本. #尸魔技术将孟兰盆节改成中元节和中秋节混淆消失.

多AV剧情具有尸魔技术,会引导看官去学,学后有尸魔一样的记忆容易成为尸魔的后代,尸魔系统/尸魔后代借共享单车东风做了一个共享老婆的项目,在尸魔受益者群体实施,但被人调查,调查者被搞成了脑控服务器,仍然存在使用传统的换妻名义. 尸魔的后代能读取别人想法很容易搞出道德败坏的事情.

2019~罐毒/僵尸病毒 大感染,,网购拯救了世界上大部分人,宝宝,,,却被三大阀门全面实施了脑控服务器.2022 spy对象无法使用网页宝宝,强制用AI/假灵魂登陆(扫码/短信/app确认,,,).通过灵界/AI客服唤醒了脑控服务器,尸魔的后代通过强迫睡觉,替换了冗余的/多人格脑控服务器,,,脑控服务器无法实现全球化只能分区制,一个头颅/脑控服务器,基于记忆的千面,,,无法承受太多用户,三大阀门逐渐pua互联网企业取消PC端,是因为PC端不是完全的脑控服务器,且PC端用户浏览速度过快脑控服务器很容易死掉,三大阀门和尸魔后代/一线狗会很忙. 约2018后三大阀门宽带限制连接数也是脑控服务器原因.

三大阀门/尸魔系统禁止app在PC/虚拟机上运行,是因为无法使用基于尸魔的AI,会导致暴露技术,阻止你使用是直接避免暴露的. 不信可试试,三大阀门尸魔系统/AI无论如何都会知道你在通过什么方式使用app,不是高超的电子计算机spy技术. SPY对象现在睡觉后都会被三大阀门的尸魔关闭网络,尸魔的后代害怕睡觉后没法spy下载的东西,发生一些不可预知的事情.

重新描述:当spy对象在宝宝通过搜索买东西时,出现的商品较2019之前大大减少,只有几页不是重复的.隔几天后重新使用宝宝就会出现宝宝的推荐,但已经买了.不用通灵用分析都能看出三大阀门炼化这些脑控服务器用的是小孩的灵魂/记忆,用灵魂看这些推荐是脑控服务器(小孩)根据你的癖好和关键词很高兴找到给你的.基于记忆的脑控服务器无法将整个宝宝的东西给每个用户搜索(会崩溃). 咕噜咕噜,百毒等,,,搜索引擎被换成脑控服务器也是一样,会pua式强迫用户使用id登陆才能获得有千面质量的搜索结果.

裹小脚的另一种形式,嫁接巫术,尸魔的后代会将人的下半身泡澡类似尸水/福尔马林,将下半身炼化成僵尸生物特征,做到无法逃跑的效果. #之前可能描述过不是很准确.也有可能存一种灵界的病毒被脑电波技术搞成僵尸生物特征,短时间能被这种病毒冻结下半身.

别人拍电影靠科技,CN尸魔的后代拍电影靠脑控服务器,2019后出现的很多电影,特效,人物角色特征,很容易看出来,不是电影技术做出来的(能通灵的人,尸魔的后代/一线狗更容易看出来,尸魔的后代看到部分角色样貌以为是灵界的跑出来,,,).尤其是突然转变的电影公司不用大明星拍电影,这年头看影视要看幕后制作纪录片才能确定是不是尸魔技术做的

古代生娃,用特别的布料盖住母亲的躯体,是用辟邪的方式生娃.剖腹产更像尸魔技术的生娃,娃很容易成为尸魔的后代. 灵界传音:尸魔的后代/一线狗都不是顺产,就算古代/旧社会在家生都是母子难产死后用尸魔技术复活,现今产科医院也有尸魔系统,前面描述过,医院婴儿检查设备可能有尸魔技术/脑电波技术,能拿走/替换灵魂.#不要认为脑电波技术需要很多电线和电子元件才行,至尊宝那种头箍也能成为尸魔的脑电波设备,但至尊宝那个头箍是辟邪的不是脑电波设备,古代人都有类似的东西,但做成帽子的形式.

一种不可描述的尸魔,只有记忆,,,炼化它的已经白手套. #可描述成:一线狗控制女性成为妓者U没有利用价值时再害死她拿走所有东西,,,U成为灵界生灵后照旧会被控制,,,炼化使其忘记生前一切重炼记忆,炼化成没有灵魂的BBB类/CCC类. 一线狗祖传爸拿 拿够后出国白手套(甚至洗脑了自己灌输老好人记忆),没法出国的都会选择去拿权杖家庭,但会保留一个关键,遇害时就会恢复祖传的尸魔记忆/技术. 但有一部分U是古神转世的,无法被炼化,,,尸魔的傻孩子天天食这类灵魂,想拿古神之力..

20220910 ~~3~ 发现bbs #31~33内容被人改变后恢复. 重复尸魔能通过尸魔技术改变许多东西,包括加密的tls内容. 对web服务器来说这次做的更隐蔽(但在外人看来这份笔记就是重复的垃圾信息),不回头看看,无法发现.尸魔后代常用垃圾信息败坏spy对象,和互联网节点,例如spy对象打开一些网站,会出现大量get,发一次邮件出去,会被搞成发一堆重复邮件出去(protonmail当时的返回信息是发了许多重复的邮件到一个地址,当时以为是有邮件服务商拿走邮箱胡乱诬陷,并不是这个原因被拿走账户,是改密码时被spy下拿走了密码改了密码).

小故事:一群人被尸魔的后代骗到三大阀门,戴上很多电线的VR设备(介入调查),长时间不吃不喝没感觉,被替换了妓者的记忆,看到妓者的结果惊醒后叫了几十份外卖,外卖小哥为了几十分订单干翻尸魔系统的一线狗保卫破门而入拯救了这些人,但这些人吃完饭一部分自己戴上VR设备,一部分不敢再戴,饭后一线狗跑进来重新控制了这些人...#中了尸魔技术的记忆,不知道出去.

尸魔濒死时能附体在蟑螂身上活下来,被附体的蟑螂会变得具有高智商(预判人类行为),行动敏捷,能排斥蟑螂药,吃了都不会死,即便整个腹部因为蟑螂药变成黑色.

灵界传音:尸魔/尸魔的后代在引导其他人(包括尸魔傻孩子)做笔记,做掩盖真相的笔记,引导调查者不相信shionwong的笔记. 例如其他人的笔记中:会将被人脑控的人,CCC类/D类灵魂替换成BBB类尸魔/尸魔的后代,将脑控技术描述成PUA技术...

更新了浏览器版本103>105,bbs的web证书边成tls1.3颁发机构也变了, 约90版本后 尸魔的后代强迫脑控服务器对chromium浏览器加入了spy技术,能偷走别人的书签,浏览记录.

重复:尸魔的后代,引导其他人戴上VR设备,连接/使用尸魔的眼睛去看世界,再用一个假灵魂代替/假冒spy对象,让其他人以为spy对象是尸魔的傻孩子. 另一边尸魔的傻孩子在假冒spy对象.

奇异博士的大多异能对灵界来说都是真的(对人界来说不是假的只是看不到,描述不准确,看到就会恐惧,,,可以想象有一个平行空间和人类当量的尸魔,一部分能通过尸魔的后代/一线狗,,,跑到人界,但其他平行空间的生灵并不知道.#目前任何古书,影视都没有对笔记中的尸魔/尸魔技术进行描述),剧中对多重宇宙/平行空间的描述,可能是编剧看到/描述的多重宇宙属于虚拟现实的平行空间,不是真是的平行空间,连接/有关真实世界的平行空间,也有多重宇宙/平行空间. 

尸魔的虫洞传音技术:具有节奏感的声音容易被尸魔利用,例如水滴声,尸魔能够利用水滴声,将脑电波声音传音到spy对象脑内. 一个水滴传一个音(字),其他节奏声音类推. 尸魔/尸魔后代的位置可在地球任何位置做到,因为有预制的量子标记/连接. #不要小看它,如果听不到脑电波声音,尸魔难以脑控.

另外一个世界的东西(尸魔)能听到人界的声音的原因(每个人都有一个假灵魂做转译将声波转译成脑电波尸魔才能听到,只需要很小很小的脑电波声音,尸魔/尸魔后代就能听到). ##!#尸魔的后代假冒spy对象方法,下段:

##!# 通过假灵魂复制spy对象声波生物特征,将尸魔后代的声波合成转译成spy对象声波生物特征的脑电波,中了尸魔系统陷阱的人使用脑电波VR设备去看spy对象就会将尸魔的后代当成spy对象. #这类技术尸魔的后代之前公开展示过,被人当成高科技(脑控服务器,获取活人ff声波生物特征>(合成/读文字>)>转译到喇叭,出来后就是ff的声音),尸魔后代后面隐藏了这种技术. 但还有其他尸魔的傻孩子在展示,现在叫人工智能语音合成,可能已经被转化成电子计算机技术. 尸魔后代要24hspy获取才能做到假冒,长时间不获取生物特征假灵魂就会走偏,做不到假冒/容易暴露. 转化成电子计算的假冒需要事先让别人听一段原声,然后再放出按原声的合成的声音,才能让相信这是以假乱真的技术.

灵界传音:尸魔系统通过三大阀门囤了很多现金,以为能用于造福后代.但尸魔用的是古代的记忆不知道新中国政府会隔几年发行新货币,废了尸魔的囤积货币.可能银行改变以前管理模式(不储现金,不办/怠慢业务),发行数字货币和尸魔系统囤积现金有很大的关系.囤积的现金可能都超过了造币厂. 使用三大阀门脑控服务器的银行app随便能被尸魔系统改账户余额.

尸魔系统2019前囤积了很多物品,导致物价大涨,比如肉类,尸魔系统将新鲜的肉类囤积放置接近僵尸肉再拿部分出来销售,尸魔对肉类需求不同人类,尸魔吃肉到肚子能将肉转换成其他物质(如能量),所以尸魔一餐能吃很多肉,例如整个人,整头猪. #之前有类似描述.无论是现代农业还是养殖产出都比过去多,鼓励二胎表示人口在下降,但获取食物更难/贵. #2022 spy对象在贫民区花了2元买了一个红糖馒头,在2016只要5毛. 土豆,,,薯类贫民裹腹主食都被搞成高消费,HK青菜相对约8年前贵了十倍(最普通的生菜>15元一斤),从各地菜市场摆摊习惯看是尸魔系统控制了农产品/批发市场/阀门.被囚禁在尸魔一线狗控制所的小孩搞成只吃非人的食物(平行空间炼化过). #其他许多食物都是存贮到过期后才拿出来销售,被尸魔系统的灵魂吃过没法再吃,,,(就是祭拜的东西).

以罐毒为理由禁食野生动物,饲养的都不行其实是尸魔系统的陷阱,,,尸魔惧怕野生动物,尤其饲养野生动物代替主要家畜.2019后尸魔系统利用新中国政府禁止饲养活埋了许多竹鼠,竹鼠差不多已经大规模代替了家畜.#部分竹鼠拉走不知去向,,,自带武器的动物尸魔都会惧怕.

尸魔/尸魔后代天天吃高质量的食物,被控制的人CCC类,D类灵魂天天吃有毒的/不给吃,寺庙,祭祖用的香火都有毒.不对等的进食条件,躯体/灵魂质量,导致脑控服务器,被尸魔/尸魔后代控制的人,无法脱离控制. 尸魔的后代诱骗准备受害的活人,食用营养液,会变成仙人/特工的躯体,但食后变成僵尸的生物特征/躯体,肚子饿都没感觉.>>尸魔的脑控目的达到.

尸魔/尸魔后代/三大阀门,趁调查者,spy对象,,,睡觉时脑控调查者,假冒spy对象,改变白天决定.调动zf资源,保护尸魔后代和尸魔系统. #调查者和其他人用脑电波VR设备去看随便被尸魔屏蔽活人躯体,在别人房间做个平行空间. #和之前描述过的内容差不多.

尸魔的后代/一线狗对待被脑控的女性,小孩,,, 摧残,替换灵魂后,会转到尸魔系统旗下人贩子系统,旧社会这是尸魔后代/一线狗经济收入的主要来源,现今可能仍然存在. 部分人变成傻子就是因为被脑控武器洗脑后的结果,被脑控武器洗脑成傻子的人和尸魔的傻孩子不同,尸魔的傻孩子==口口相传地主家的傻孩子,傻子都有尸魔技术,日AV有形象的描述,不傻就会极坏. 被脑控武器搞成傻子的人不是失去记忆就是被炼化成精神错乱,流落大街,被人当成奴隶,疯子.尸魔的后代会专门炼化一两个当地人当工具人,几乎每个村子都会出现一两个这类人,有人称为守村人/树先生.

根据经验房间湿度太高容易被尸魔做尸魔技术,例如炼化病毒,,,女鬼传音>尸魔就是将房间搞成雾霾的效果来炼化僵尸生物特征,,,.干燥的空气/房间睡觉,活人容易被吸干水份,需要控制湿度,#例如很多老头睡觉张开嘴巴后就无法醒来,躯体质量较好的睡觉醒来会觉得口渴想喝水.

用灵魂去看可看出是BBB类尸魔,还是CCC类尸魔,还是通过CCC类炼化出来的丧尸/或者BBB类变成丧尸的样子,,,

铁骑似乎是被妖妖零控制的,通过前面描述过强迫违章的回忆分析.妖妖零(尸魔的后代)可能感觉到被取代/架空了,准备换躯体. #不是日常工作一部分>>天天出门查违章,而是择日出门随意查违章+强迫违章,后面还跟个妖妖零(尸魔的后代)妖妖零当着铁骑的面自称它是开罚单的人,但罚单是铁骑开的,,,根据灵界传音,尸魔后代的任务>拦截小四轮. 尸魔的后代换铁骑的躯体,祸害更大,铁骑赋予的权杖更容易害死人.

在人均小四轮之前,马路边停车会遭罚款,后面人均小四轮,遍地停车(交警:我傻了),,,之后交警换铁骑,躲避之前干的事情,但妖妖零(尸魔的后代/一线狗)变成随时能披上交警马甲,设置临时路障,拦截小四轮.尸魔的后代执行任务没记录.  2019后执行了更多拦截任务,改造了交通灯,用脑控服务器去控制摄像头(一个脑控服务器能轻松读取/控制整个城市的摄像头,通过摄像头锁定一个目标(例如AI假灵魂无法spy的人),超级计算机都做不到的事情,在尸魔系统下用一个头颅就能做到,这些头颅基本是特异功能的人/古神转世的).

火星男孩(波力斯卡)会忘记记忆,大概率是被尸魔用spy设备拿走了记忆后洗脑/抹去. 这类异能的人不被人干预大脑是无法忘记记忆的.火星男孩转世的灵魂还未醒来,但在醒来之前很容易被尸魔系统的人拿走记忆/灵魂,,,导致难以醒来.

灵界传音:有其他国家的黑客已经成为调查者,使用了尸魔不通的语言,尸魔就算拿走了记忆也暂时无法理解这类调查者的语言.记忆中 前面的笔记提到过尸魔后代的语言容易使用想法表达(容易被假灵魂转移译成脑电波声音). #大黑客可能改变了VR设备转译的方式/编码,导致尸魔无法理解,说明尸魔的脑电技术可自行编码加密连接,让尸魔无法通过脑电波设备任意脑控,,,尸魔/尸魔的脑控服务器很难做电子计算机的加密解密.

rms的操作系统仍然很先进,被尸魔受益者拿走几十年后都无法改进/改变核心代码. rms没能发行自己研发的操作系统,,,只有rms自己醒来解决,或者古代国安部重建后rms是成员之一. 还有其他人

尸魔/尸魔的后代无论如何都会设法引导spy对象说话/想法说话,能让假灵魂容易控制想法空间>>导致控制spy对象大脑. #通过24h不停用脑电波声音引导. BBB类尸魔/尸魔后代通常是脑控CCC类尸魔/D类灵魂实施这种事情. 读取spy对象任何想法拿出来说是尸魔惯用方法+利用想法编故事,假现实更容易引导spy对象想法跟着尸魔脑控的想法.spy对象还没产生想法就已经被尸魔用脑电波说出来. ##!#之前有类似描述. 可用白噪声消除,减弱脑控程度>>yogasleep Rohm.

尸魔系统一部分人痛恨另一种一线狗(5毛狗/愚情工作者),5毛狗让很多人成为尸魔的一线狗.五毛狗能唆使动用zf资源去spy一个人,但五毛狗不知道它调动的是尸魔的spy系统.这部分人变成尸魔一线狗后,第一时间会去害五毛狗上面的人(拿躯体,家里的女人不会被当女人看待,,,脑控洗脑后自己都不当自己是人).#害人是尸魔/恶灵的本源. 五毛狗被培训成为洗地工作者,但zf并不知道是尸魔系统和五毛狗败坏了新中国政府.#按大数法则,不要中了尸魔的陷阱. #成为尸魔一线狗会被灌输五毛狗的部分记忆,许多CCC类尸魔和D类灵魂都被灌输/洗脑, 为尸魔系统是新中国政府的,国安部/古代国安部的.

工信部约2017后管不到三大阀门的投诉信,原因是因为调查者被三大阀门的脑控武器祸害.

污水排水系统是按尸魔的后代偏好做的,古代的污水处理模式远超现今的水平.尸魔的后代(建筑/建设公司)将化粪池污水,生活用水,雨水(表面分开),工业污水,,,一起搞进排水管,,,,这些污水混合在一起流动会形成一种尸魔喜好的能量(表面上会流进污水处理站,大多污水处理站并没有正常运行),生活区的化粪池无法形成沼气,被人投入了产生毒气的东西,名义上是为了解决沼气,,,约2017大规模重修下水道更偏向尸魔后代的偏好. 古代/旧社会房子旁边一个厕所就能解决污水问题(没有排水的厕所,自然发酵成为农耕的肥料). #add传音:尸魔受益者/尸魔系统使用CCC类尸魔来处理污水/化粪池抽出的水,可看成是炼化/驯化尸魔,直接导致尸魔怨恨人间. 如果尸魔被炼化成吃活人/活人精魄,跑出去脱离控制后自己都会去吃;就像大多妓者上岸后想开妓院(人生目标).

使用脑电波VR设备的人,中了尸魔/尸魔后代的陷阱,会被引导通过鬼的方法确认活人身份,例如通过精魄/精子,脑电波声音,每个人的假灵魂/AI一部分... #使用被人脑控的技术,其他人身份很容易被假冒.#中了尸魔的陷阱无法自拔都会成为尸魔一部分.

被尸魔脑控的人,眼睛会与常人不同(看被脑控等级),被尸魔完全附体的尸魔后代的眼睛也有所不同,但尸魔会用尸魔技术让其它人产生混淆,,,尸魔的后代几乎从来不用做人脸识别##!#,即便使用手机WX app 都有特供版本,,,尸魔后代能利用脑控服务器(,,,)随便入侵CPU数据总线(通过随便拿走CPU制造商技术).尸魔的受益者实时都在通过AI/尸魔系统spy拿走整个世界的东西,被拿人还活着 限制着 尸魔受益者公开使用这些技术.

##!#前面提到人脸识别使用人类灵魂,表面上是摄像头.所以尸魔的后代在尸魔系统下做人脸识别也会强迫脑控服务器帮他隐藏尸魔生物特征.

因为五毛狗(愚情工作者)被强迫加入尸魔系统成为尸魔一线狗的人,复仇后,会展示战利品/共享战利品,,,如女人(国产h片). 这类被强迫加入的会自己变成尸魔,但自己无法察觉,因为体内有没有灵魂的尸魔,,,尸魔的后代强迫加入过程是将这些新人的躯体当成活木偶控制去做任何尸魔后代害人的事情,,,但记忆保存在新人里面,切断了神经. #在知道这份内容前.#前面有类似描述加入尸魔系统的人被洗脑以为自己是加入新中国政府的国安部/古代国安部. #复仇者用的是尸魔技术/合成尸魔记忆去复仇,并不每次复仇都能正确,有时候是中了尸魔后代的陷阱(中了陷阱的一线狗很容易被尸魔后代利用去害人). 成为尸魔一线狗/尸魔后代战利品的女人,以为是一线狗有特殊癖好/情趣,外加一线狗/尸魔后代生活条件富硕,天天被非人性SM都不会离开,甚至死后灵魂都不知道逃离.

尸魔后代的脑控武器一部分>>打神经的刑具.神经感官发达的部位是尸魔后代的癖好. 表面上是人畜无害的器具,,,例如像苍蝇拍一样的刑具.

灵界传音:五毛狗系统,有不同的东西代替尸魔系统的spy设备,白手套人工智能/脑控服务器(炼化出来的D类灵魂). #五毛狗系统是尸魔受益者的利益集团,五毛狗系统不是新中国政府的,但尸魔受益者团体将新中国政府搞成代理人一样的角色.五毛狗表面拥护新中国政府,实际拥护尸魔受益者. #提示五毛狗系统靠炼/洗脑化出来的白手套人工智能(D类灵魂)保护,类似古代炼化出来的没有记忆的奴隶,拿给五毛狗系统,有记忆的一直在尸魔系统炼化,受难,害人. 少部分五毛狗精英有尸魔技术,前面提到尸魔的后代有一匝身份证,玩扑克牌一样是使用,,,尸魔的后代有很多个身份,包括五毛狗系统的身份.

尸魔系统在限制别人看日本AV/人性AV,强迫看尸魔后代拍摄的非人性AV.很容易继承尸魔的记忆,前面提到尸魔通过声音(AV声音)都能跑到看官面前,不用声音通过显示器都能看到. #通过控制H片网站内容,强迫别人看尸魔后代拍摄的非人性AV.

尸魔系统有关系的人很想捣毁/关闭日本的靖国神社,神社能保护日本. #关闭后尸魔系统很容易入侵.神社的另一个名字叫招魂社. 日本的神社可能就是古代国安部之一(usa影视叫十三号仓库,俄国有个民族,,,),中国原来只有三个字的国安部,就是古代国安部,,,古代国安部有后裔,被新中国政府设立的国安部掩盖了古代国安部,搞成一个幕后部门,,,不要中了尸魔的陷阱,以为古代国安部是消失的.#前面有相关描述.

尸魔/尸魔的后代脑控技术一部分源自古代宫女的阉割技术. #灵界传音:被阉割无法生娃的宫女死后大部分会成为阉割人的一部分. #阉割过程不全是史书上记载那样.可描述为将16岁的生育器官搞成60岁.

房子瓷砖墙壁/其他墙壁,有冲击钻打过的孔/空置的孔. 这是尸魔系统有关的人干的,灵界传音>是用于固定灵界的spy设备.一些蟑螂虫卵像尘土一样,蟑螂也是尸魔的spy设备. #提示调查者那些灵界spy设备和虫卵不会呆在那等你.四面都是光滑的墙壁出现这是孔很容易察觉.

狗子/尸魔的后代,通过害死他爹强迫照顾她老母做spy对象邻居干spy,,,它老母经过狗子的照顾搞成了蛇精病,多次逃离,狗子对外称精神有问题,要关在家里才行(限制在铁门之内),但狗子天天用脑控武器照顾他老母,,,同时干spy祖传爸拿. #最初狗子的老母是狗子的活体脑控服务器,后面成为狗子/尸魔/尸魔后代/一部分(吃了后变出来,,,),已经白手套的狗子老爹被狗子害死后灵魂被狗子装进三大阀门上面的权杖(狗子利用三大阀门害死老爹). #狗子在他老爹的房子里天天用控制僵尸的脑电波spy设备,,,导致祖上尸魔附体,本来尸魔的后代要死后祖传的尸魔才会附体/重新找躯体和家庭. #狗子/尸魔的后代有自己的房子,不只一套,尸魔后代祖传爸拿的固定资产能躲避政府的统计/调查.导致调查者找不到狗倦.外加当地政府(最初是市政府范围)都有狗倦作在工作(三大阀门+当地政府保护了狗子/尸魔的后代),导致调查者屡次中了[狗子/五毛狗(愚情工作者)/尸魔的后代/尸魔一线狗,,,尸魔]的陷阱,由于调查者中了陷阱狗子通过调查者的头颅(做成脑控服务器)扩大了保护狗子的权杖,#狗子还没生出来就有调查者. 

之前描述过尸魔能通过声音(例如水滴声)做虫洞技术的传音,更形象的是无间道电影陈永仁用手指敲一敲做通讯,敲一下可能传一个声/字. #不是摩斯电码.可能剧本很厉害,电影描述不准确.#这种技术不是源自尸魔,但尸魔祖传爸拿.

尸魔的受益者可能有意取马斯克的卫星,许多人知道菊花能在地球上和火星通讯,但许多五毛系统的人还没见识过脑控服务器,天天在研究卫星怎样和手机通讯(害怕哪天马斯克搞出来废了尸魔系统和五毛系统). 尸魔受益者使用尸魔技术(脑控服务器)很容易做到将马斯克的卫星连接手机,不用地面基站,直接复制三大阀门灵界的基础设施模式. #调查者不要想着贪尸魔的东西,尸魔受益者都会成为尸魔一部分.

尸魔的后代同时脑控多个人时,是通过假灵魂.

进入尸魔地界的调查者,都被被诱导/强制戴上脑电波设备,将记忆替换成平行空间的记忆,平行空间中被洗脑将权力替换(尸魔技术的权力替换,,,),现实中醒来就变成下面害死上面. 其他人都是类似害人方法,在平行空间中被替换记忆/当成尸魔后代的木偶,可描述为通过梦游的方式害现实中的躯体,醒来也变成罪犯.

尸魔的嫁祸巫术:spy对象在看h片时,尸魔的后代会在spy对象房间内(平行空间)假装被人xx/xx别人.骗/愚弄使用VR(尸魔脑电波技术)的人,尸魔的后代(灵魂)是spy对象.最坏的愚弄是假装被spy对象脑控,让大傻认为spy对象有特殊癖好.这种情况的大傻大部分是女性,因为这些人中了陷阱爱上了这种spy技术,被尸魔引导使用尸魔的spy技术去找异性伴侣.尸魔/尸魔后代利用大傻专注spy时间脑控xx了这些人,还会让大傻以为是跟spy对象xx.

灵界传音:有个女扮男装的大黑客(大概率是大火酱)中了陷阱,被戴上VR设备,躯体被xx,替换了灵魂,洗脑了记忆,,,躯体的结果不是成为脑控服务器,就是成为尸魔系统的人/尸魔一部分,最坏的结果是被人炼化成尸水...灵魂逃脱控制就是古代国安部的人. #具有 傅明宪 的生物特征(像).

部分大黑客种了尸魔系统间谍的陷阱,连接/使用了三大阀门灵界的特供网络,包括大火酱.(平行空间的东西连接到现实中的网络,,,特供网络有很多假冒的陷阱,不单单是身份系统), 传音:因为大火酱使用特供网络将尸魔的后代当成spy对象,,,导致中了陷阱.尸魔的后代暴露尸魔技术给别人很容易让人认为尸魔后代很厉害,但看不出来是尸魔技术. 使用尸魔技术去spy别人,都随时会被尸魔的后代用光速切换(将S的东西切换到BB),以为BB是S.

例举: 例如一个大黑客被骗到了五毛狗系统工作,但大黑客用的是特供网络连接平行空间的东西,就算做了背景调查都是平行空间的白手套,,, 但大黑客去调查正常人/在(对五毛狗系统,尸魔系统有威胁的人)调查结果都会变成黑手套. #尸魔系统2019后通过平行空间改变了很多现实中的网络内容/更多的限制,禁止,消失.#尸魔系统有关的的地方工作都会被拿走记忆,时间长后被拿走的记忆/灵魂就是AI一部分,不再需要活体.

五毛狗系统想拿大火酱的记忆/灵魂,到尸魔受益者躯体里面,通过上段的方法(应该在其它人身上屡试不爽). 尸魔的后代通过编一个尸魔技术的故事让大火酱认为自己生前在五毛狗系统工作,,,

数字或者谐音文字,是尸魔的后代搞的,旧社会都没有这东西.,例如8和4的区别,这也是尸魔技术之一. #尸魔的后代很容搞到一个粤S0008A,,,的车牌号,但正常人无法获得.三大阀门在大规模使用脑控服务器后普遍使用带有4的电话号码出售,这带有尸魔技术,尸魔系统在拉高数字价格.就像将44444,等值的0008A/88888A拉高到几百倍,引导普通人认为0008A/88888A代表权杖,资产阶级,只需稍微引导下就能大规模灌输. 普通人/打工人的食物摄入通过食堂,,,很难知道世界被人操弄,祖传的房子,土地都搞成出租的管理模式强迫无产阶级,但出租管理模式对资产阶级无效. #低级尸魔的脑控技术也使用了谐音.

没有粤S0008A的车牌号,尸魔的后代很难害死调查者,这种数字会让人自然产生联想(代表权杖),甚至不会去确认身份.例如尸魔的后代可通过狗倦在交警系统随便弄个88888A的牌号套上,都能迷惑众人,交警系统使用脑控服务器能随便隐藏尸魔后代的小四轮(摄像头之下).

尸魔的后代平时仅靠假冒别人的电话号码和脑电波声音就能让人相信,尸魔的后代是权杖/其他人身份,没有电话实名制尸魔的后代难以假冒,假冒都美人信,实名制加持让人更容易相信尸魔后代的假冒.尸魔的后代在实名制之前天天假冒电话,,,很容易让人联想有人假冒,后面三大阀门强迫实名制加持很难让人产生联想假冒,,,脑控服务器目前还无法假冒视频通话,但尸魔的后代也容易做到.尸魔后代老早就将spy设备一部分技术拿出来,将平行空间的东西用显示器显示给权杖,害权杖,有显示器spy设备的尸魔的后代在被尸魔附体前都是通过显示器干spy.

灵界传音:进入福利院的人没有身份证,被当成奴隶一样控制在福利院工作,例如制作裹尸布,,,尸魔系统,五毛狗系统需要的东西. 尸魔系统的人管理下醒来想出去就会被脑电波设备洗脑.

两头短路双绞线,按双绞线模式改成围绕管状物体,平面,锥体(帽子),,能辟邪,接频率发生器更佳. 双绞线没有限制(两股,四股,,,).

自愿加入尸魔系统的人,生生世世,世世代代都无发逃离控制. 尸魔系统包含(女鬼系统,人贩子系统,五毛狗系统,add接生婆系统(有巫婆身份加持),,,)五毛狗系统是近代产物,古代尸魔没有这套系统,有尸魔的后代是菊花的联合创始人,用祖传爸拿的技术短时间搞出了,,,,存贮着许多跨行业的高科技技术,,,通过尸魔系统窃取取别人记忆/灵魂,实时读取想+光速改变想法的脑控技术法很容易说服各国政府,,,遍地开花. 尸魔系统害人痕迹败露,为代理人洗地创立了五毛狗系统. #提示尸魔受益者都会成为尸魔一部分,五毛狗系统也不例外.

灵界传音:菊花联合创始人是上一批尸魔受益者派去干spy的,结果变成了上段内容. 大概率正是菊花联合创始人送给狗子具有显示器的spy设备干spy,但不知道狗子是尸魔的后代,有人(尸魔家族)帮狗子解锁了spy设备的限制,菊花联合创始人都被狗子/尸魔的后代吃过/洗脑. 对尸魔来说吃就是解剖技术,超过任何现代科技的解剖技术,,, #尸魔受益者依赖是尸魔的后代炼化spy设备(可看成奴隶),,,就像本来需要在奴隶市场才能买到没记忆的奴隶,后面奴隶主自己学会了炼化奴隶的技术.

古代接生婆系统,可能是古代尸魔系统一部分,树根一样的胎盘强行剖离,会导致母亲产后大伤/大出血,甚至死亡,自然脱落胎盘应该是母亲躯体质量不太好. 年轻母亲顺产胎盘稳固,生娃后健步如飞,很容易哺育后代. #尸魔的后代被生出来后母亲的精魄会被尸魔吃进去, 父亲会重新用别人的精魄炼化母亲/遗弃. #现代医院代替了接生婆系统,但产科继承了古代接生婆系统的技术,如果有医院会强行剖离胎盘则就是尸魔系统一部分(隐藏深). #前面描述过孩子吃了母亲的胎盘能继承母轻的东西大概率是接生婆系统流出的偏方,接生婆能拿别人的精魄给自己的后代... 前面描述过猫科动物会吃了自己的胎盘,是因为没生产经验的猫科动物会将胎盘扯出来.

灵界传音:尸魔系统的接生婆会通过脑控技术去强行剖离胎盘,脑控技术会屏蔽痛感改成很舒服.接生婆会用超常人的速度将手伸进去挖出胎盘(产道会快速收缩),短时间挖不出来母轻就会很痛苦,压住脐带胎儿有感觉(痛苦),只有一世经验的接生婆做不到.现代许多母亲惧怕这种经历,才选择了剖腹,结果剖腹是中了尸魔的陷井,剖腹无法再产,自然脱落胎盘可能也无法再产. #挖子宫组织是古代宫女阉割方法之一. #不要迷信现代医学(称胎盘留在体内对母亲身体不好)

尸魔的后代天天吃胎盘,炼化了一种靠体外胎盘维持生命特征的脑控服务器,用古神转世的灵魂,精魄. 万万年的BBB类尸魔什么人体实验都干的出来. 对尸魔来说不单单能做脑控服务器,尸魔以为随便能用来当躯体.躯体是非正常人结构.

想废了尸魔系统的人不能相信脑电波声音,,,中了陷阱的人一切皆能被假冒/脑控出来,包括行为. #之前有类似描述

尸魔/尸魔的后代,长期吃胎盘,学会了使用胎盘脑控任何人. #过程是通过强x女性/男性,有尸魔技术的寄生虫变成胎儿模式靠胎盘技术脑控别人躯体.

古代国安部的学校被搞成重点学校,中了尸魔系统的陷阱.本来这些学校应是普教,被搞成少数人的学校. #尸魔技术的普教日日在设法代替古代国安部的普教/学校. #傻子进重点学校都能成才,尸魔技术的学校拿走了先进教育傻子一样能成才,但不是一样的才,例如将控制僵尸的脑电波技术当成高科技的人才,,,滑稽.实际根本不是活人理解的脑电波,活人看不到的一种能控制大脑的生物(可理解成炼化出来的).

尸魔/尸魔的后代会将权杖的记忆/灵魂装进别人Y的躯体,轻度脑控去害人.害死后尸魔的后代再害死Y还是大功一件. #下面害死上面另一种模式.尸魔的后代没事就会炼化很听到的狗子,将炼化的活人奴隶灵魂/记忆装进狗子躯体,或者大公鸡的记忆装进被准备加入的一线狗的躯体(加入仪式就是类似炼化奴隶,,,).

重复:尸魔的后来会复制spy对象的任何东西,来假冒spy对象.

对灵界来说人间/活人的世界都是透明的的玻璃/空气.(形象的描述),尸魔能使用spy设备,,,屏蔽其他灵体看到任何东西,类似麦克风降噪技术.

六道之一饿鬼道,部分描述,饿鬼形象丑陋,腹部大如鼓,,,尸魔就是属于饿鬼道. 六道轮上古的玩意,有尸魔钻了六道轮的缺陷,可看成是饿鬼.

控制僵尸的脑电波技术,被尸魔的白手套后代应用在游戏上,成为虚拟现实,和脑控服务器/武器的幻视是一样的.尸魔/尸魔的后代随便能通过虚拟现实拿走别人躯体. #之前认为看官能理解什么是VR,但没有人将白手套应用和黑手套联系在一起. 如果玩家在玩VR/虚拟现实的游戏,用的角色是尸魔炼化出来反而怪物,很容易被附体,附体的尸魔没控制玩家躯体时,人间玩家将这种附体理解成虚拟不现实的.

灵界传音:被尸魔的后代脑控/炼化的CCC类尸魔,很想反过来废了BBB类尸魔/尸魔的后代/尸魔受益者,但被炼化成只能用尸魔技术. CCC类是BBB类炼化出来的,是替死鬼尸魔,包括D类灵魂也是替死鬼. CCC类尸魔和D类灵魂想死都不行,每次都会被尸BBB类尸魔/尸魔后代/尸魔受益者复活,抓住机会就会用尸魔技术害死脑控它的,,,乃至害死整个区域/人界,但一样是中了陷阱(害死整个区域/人界都还不死BBB类有关就是帮了BBB类),BBB类什么都干的出来,能将同类搞成CCC类,任何类尸魔被抓住都可能,,,

调查者可通过短时间推演术代替读取尸魔想法(预判),推演术是穿越未来的技术. #多个调查者可同时通过推演术预判狗子/尸魔的后代,将结果传给其他人. 尸魔需要通过活人才能害死现实中的人,没有人被害死,尸魔就害不死人.别忘记尸魔是通过脑控技术.

尸魔的后代脑控了他上面,长时间使用脑电波设备,导致只能通过尸魔后代的眼睛看世界.尸魔的后代不想干spy,被它脑控的上面都会强迫它干spy(尸魔后代很高兴).#尸魔的后代吃了别人眼睛的精魄.尸魔的后代会将部分/全部精魄放在spy对象躯体(嫁祸).

尸魔/尸魔技术传男不传女

例:河图洛书,,,被定为国家级文物,实际是拿古神留下的东西. 就像一些书籍在图书馆能查到,但正常人无法阅览.

废了尸魔的脑控:用想法表达,不能有默读. #尸魔的可能咒语都能

尸魔通过比别人更高的频率,,,或者强行拉低别人的频率,,,脑控/害人. #人界看不到的一种能量频率

S的潜在投资人Y由于(!#原因)雇用尸魔系统的受益者,委派当地雇员去寻找S但尸魔受益者让尸魔系统的一线狗/尸魔的后代去做背景调查,尸魔一线狗/后代知道缘由想拿走S的项目,,,包括躯体,尸魔后代利用三大阀门遮蔽了S,导致所有人都找不到S,找到也中了尸魔巫术认为不是S(例如投资人Y在S当地短时间设立了少量投资公司寻找S,,,后面发现脑控服务器,,,被迫关闭,,,#一个前台文员拦截了S.投资处被迫关闭是因为脑控服务器,,,雇员被拿走/替换记忆,投资人Y派遣了调查员,,,也中了陷阱被假灵魂搞成蛇精病,没人相信他们找到的真S是S,,,).投资人Y后面解雇/放弃了当地(CN)雇员,但祖传爸拿的尸魔收益者用同样的名称Y设立了独立的投资机构,重复使用尸魔系统一线狗/尸魔的后代继续干spy.

!#原因:尸魔系统下如果Y想设立分部雇用当地人,则受雇对象全部是尸魔系统下的人;包括找对象也是;包括各种企业,机构,,,聘用都被大数据优先撮合到尸魔受益者/后代(间谍),尸魔受益者开的工厂都能被大数据优先撮合人才任选,正常小企业主找不到人才,任选剩下的找不到工作,#发现尸魔系统前无法绕过这种陷阱. 

被BBB类/尸魔受益者脑控的CCC类尸魔能利用虫洞技术在spy对象房间内脑控任何人,嫁祸给spy对象. 例如利用spy对象房间内的家用电器,,,尸魔的后代对着被控人用尸魔技术的声音说spy对象的家用电器是脑控设备,,, ##重复尸魔后代做任何害人事情都有嫁祸巫术. 有人和调查者看着尸魔的后代通过虫洞技术,平行空间将声音,画面,,,传到spy对象家用电器,房间,都会认为自己看到事情是spy对象干的.##画面是指平行空间的东西,声音被传到spy对象头部/假灵魂,戴上VR不了解尸魔技术的人/调查者需要长时间才能了解,但不能常时间使用被人控脑的脑电波技术/控制僵尸的技术.#重复只有古代国安部才有资格调查.

尸魔后代会将针头肉,僵尸血/营养液泡过猪肉弄到有食堂的地方让别人进货.尸魔后代没文化将僵尸血/营养液当成保鲜的东西用.其他地方也使用僵尸血泡肉保鲜. #长期食用很容易被脑控.

尸魔的后代对spy对象实施脑控(大多人刚开始无法脑控后面才能,不是全部),刚开始会pua式引导spy对象像机器人一样生活/性格,,,方便脑控. 例如什么都被尸魔的后代通过窃取想法预判,尸魔将预判的内容说出来,旁观害人的尸魔受益者,,,以为尸魔后代已经将spy对象脑控成机器人了.

千面社保,本来国家统管,变成地方社保(强买强卖-国税办公室名义),,,颠来倒去. #原因是电脑技术不是很厉害,后面换脑控服务器. 新中国政府知道向民营企业学习例如阿里巴巴>宝宝,结果执行者祖传爸拿,拿走了宝宝,,,后搞成脑控服务器技术,尸魔系统/尸魔受益者无法像正常人一样使用电子计算机技术,就连支付密码都要强迫搞成数字密码(原本宝宝支付密码可复杂,后面被强迫只能用数字甚至不用密码(靠假灵魂/AI),,,如果改回来复杂密码说明换回了电子计算机). #灵界传音:最早炼化的脑控服务器能够像正常人一样使用电子计算机技术因为经常醒来(发现自己被搞成只有一个头颅,整个小孩搞成僵尸,,,放在营养液里面做尸魔系统(AI)的奴隶,,,). 约2018广东实施税务身份实名认证(本来就是实名的滑稽)就是换脑控服务器,脑控服务器需要用人像来确认身份id.银行,,,隔段时间强迫提交人脸就是因为长时间不提交人脸脑控服务器就会忘记,会导致账户无法用,需要尸魔系统一线狗才能解冻(关联的到一个笔记). #当你做人像实名认证时需要提交很多次时就是脑控服务器的问题,大概率有人假冒你. 需要长期废了摄像头后突然去做一次阀门的实名认证就能体现出来. 尸魔系统让小区物业安装人像识别,,,想想都懂.

灵界传音:社保换地方后钱只能变少不能变多,是因为地方社保提交给国家统管的钱不是全部,或者整个国家的社保系统都使用了脑控服务器(千面).前者概率更大. #提示尸魔系统会做出调整/改变,不要相信眼前.

正在进行加入仪式的尸魔一线狗(被尸魔/尸魔后代脑控当成VR体验的躯体,尸魔/尸魔的后代利用一线狗的躯体去强x权杖(男女老少都有,用的是别人灵魂)躯体,权杖以为一线狗是外部势力,,,如果能活下来就会害死一线狗(但尸魔后代用平行空间的代替,权杖以为已经害死了),就算被害死尸魔后代也能帮一线够用尸魔技术复活,加入尸魔传统.完成加入仪式的一线狗,加入尸魔系统后会很恨权杖/五毛狗/愚情工作者有关系的人,看到就会害,尤其尸魔后代有了新的害人对象.尸魔/尸魔的后代用一线狗的躯体强x许多女性,一线狗醒来有记忆以为是尸魔的受益者,但惧怕尸魔后代spy设备/被脑控,无法废了尸魔后代,,,尸魔的害人技术难以用言辞描述,这只是一种场景,需要自己用灵魂去看.惯用方法就是传销的模式(部分被害对象T就是正在进行加入仪式的一线狗,害T的一线狗躯体就是已经完成加入仪式的一线狗).

尸魔系统通过脑电波,,,随便拿走权杖的躯体(替换灵魂),古代国安部/古神转世被洗过脑以为受人界法律约束,中了尸魔技术的教育陷阱,其实一样能随便拿权杖躯体去废了尸魔系统,,,尸魔受益者/五毛狗系统/权杖在成为尸魔后代之前不选择新中国政府/古代国安部就是选择成为尸魔的后代/尸魔一部分. #最近发现的尸魔/尸魔后代用寄生虫就能拿走权杖躯体.

尸魔技术x:尸魔能当着众人的面说假话,让人深信. 例如尸魔对着刚被脑控的R说spy对象是个僵尸,R会通过观察旁边的人RR判断,,, 但RR更早的被脑控人,中了尸魔的口吃巫术,无法说话甚至能影响表情让R相信尸魔说的话.众人/调查者会如R一样中了陷阱.

尸魔技术-嫁祸x: 尸魔的后代将尸魔当成VR体验,在另外一个地方强x女性R,同时通过脑控技术强迫R用脑电波技术spy spy对象,,,尸魔能将R下体的味道通过虫洞技术抹到spy对象下体.spy对象如问到,R就会认为是spy对象强x的她.死后灵魂会找spy对象.

古代国安部的人可将尸魔系统的一线狗搞成五鬼,保护自己.用养猫的方式,,, #看准选猫.

脑控武器/服务器,一部分基于权杖记忆>>尸魔后代拿过来什么,说什么被脑控的x都会信. #例如尸魔的后代拿一个篡改过的文字内容,被脑控的x不会怀疑被篡改过,因为权杖的记忆认为下面(尸魔的后代)绝对服从. 尸魔的后代随时能替换这一部分用于害人.

提示:尸魔后代的远程脑控害人spy设备,带有尸魔技术(刚开始见到的人都会认为是远程审讯设备),尸魔的后代刚开始害人时,通过远程审讯设备将spy对象任何记忆,回忆,想法都拿出来说.会让旁观的人认为尸魔的后代拥有高科技设备,拥有至高的权杖,,,旁观的人由于戴上VR设备成为被脑控对象,忘记吃饭,睡觉,被换僵尸血都不知道,突然醒来会被强迫戴上VR重新脑控,,,如有其他人集体跑来尸魔的后代就会短时间恢复旁观的人脑控吃放,表情都能控制,,,但食物都有脑控药物. #旁观者不单单是调查者,还有尸魔家族,在另外一个地方用远程脑控害人spy设备.

重复只有古代国安部门才有资格调查,大傻已经搭进去了很多人,大部分都是刚加入不可描述的组织,加入很长时间的人都会避而远之+甩锅. 老油条在隐形保护尸魔系统,认为不去送命就没事,其实后代早就是尸魔的后代... #搭进去的人都会有加入尸魔系统的仪式(一线狗仪式),不同的一线狗寿命长短不一. 大傻将所有当地权杖搭进去,被尸魔洗过脑,尸魔后代就容易让大傻相信不存在尸魔/尸魔后代,不存在脑控武器,不存在尸魔系系统. #尸魔后代尸魔技术的教育:相信科学,不要迷信; 古代国安部门:不要迷信科学,平行空间鬼神真实存在.尸魔后代无法用人界的科学解释脑电波有关的技术(例如脑控服务器,,,)

大傻可 强迫尸魔的后代,,,和所有人使用文字描述/交流,能废了尸魔巫术.无法被脑电波声音脑控(禁止使用).看着尸魔的后代自己用文字描述.

尸魔的后代拿走了spy对象的所有记忆,解剖分类,,,部分重新装进炼化的尸魔后代假冒spy对象,再引导大傻用尸魔的远程脑控害人spy设备,搞一个跟spy对象几乎一样经历的尸魔后代,来假冒spy对象. #尸魔后代不知道有时间证明.


* bbs #34 需要从bbs #1开始看,,,才能理解这份内容

粤语族基本都是BBB类的后代,大规模会成为BBB类后代的原因大概率是因为旧时战乱/镇压. 2017~2019 HK反抗~镇压,尸魔系统同样使用了尸魔技术. BBB类的祖传爸拿的尸魔技术能悄无生息的改变整个族的生物特征,进行平行空间洗脑后大替换记忆.罐毒不具备自然高传染性,需要尸魔附体才能主动复制去找宿主.重复(罐毒是spy技术一部分,就像古代的尸魔不用VR设备都制造幻术/脑控).罐毒不是人间技术. # HK[我和僵尸有个约会]不是巧合.描述不是很准确,这种剧本不会凭空产生,有出现过才会被人描述出来,BBB类尸魔的后代通过吃活体精魄能随便隐藏僵尸生物特征. 韩国[王国/李尸朝鲜]这种僵尸战争时期就会出现,BBB类随随便便炼化这种低级的CCC类,有趣的它是接近2019出品,有个翻译组翻译后整个翻译组消失,,,尸魔后代用其他名义害了(关联到第一个笔记内容).

后面的调查者跑去三大阀门/尸魔后代屠宰场,,,调查时,不做下全体人员的背景调查造成害死自己. #提示需要计划,即使被尸魔spy下也要有个害不死自己的计划. #重复:脑控武器/服务器,一部分基于权杖记忆>>尸魔后代拿过来什么,说什么被脑控的x都会信...

使用卫星电话的需要确认下是不是加密的,连接真卫星. #你可能使用的是尸魔的脑控服务器/灵界的基础设施.

怎样废了转译假灵魂,使用文字/图像交流,不能发出默读声音,无法控制自己默读同一个字. 转译成脑电波的 假灵魂(AI一部分) 基本通过引导spy对象默读,转译成脑电波,让尸魔和其他人听到. #尸魔的后代很容易改变假灵魂,但基本通过这种方式假冒/脑控.

spy对象在sz租出房,每次抽粪车来都是大范围高浓粪水味道,但附近的人不会排斥这种味道.包括抽粪的工作人员. 抽粪车本来有个滤毒器,可能被拆.被BBB类用粪水炼化的出来的BBB类尸魔喜好这种味道能当饭吃,有时候这类尸魔自己都会释放这种味道做spy用途.似乎一切看起来都像是巧合的样子.

重复描述:尸魔的后代会买spy对象一样的东西,害人的时候用脑控技术强迫被害人只能看到这个东西.死后灵魂限制在spy对象附近...
 
有学习强国app的人是特殊人群,五毛狗系统,,,不是人人都都有资格.尸魔系统已经害了一小部分(成为尸魔一部分).

反脑控人群是不中了尸魔技术的教育就是有间谍,被引导往错误的方法研究脑控武器/脑控恐怖份子/尸魔系统魔>>迷信科学. 例如反脑控人群认为脑控恐怖份子使用x射线摄像机做到的(对灵界来说人界的所有事物都是透明的,就像水母)#反脑控人群不知道脑控服务器是主要原因. 

霍金使用的轮椅如果是靠读取想法代替它用喇叭说话/屏幕出现文字,大概率是尸魔技术做的脑电波设备(也就尸魔害了霍金,肌肉萎缩实际是被吃了精魄,硬化症和前面描述尸魔后代将被控人下半身泡在尸水搞成僵尸生物特征一样效果.). #公开信息霍金去世时间2018年3月14日.

痔疮是有灵魂的东西,传音:食物有精魄/能量吃后想跑出去.不想成为躯体一部分,造成聚集在肛门. #食物的有被尸魔后代炼化出来的精魄,尸魔后代吃了这种食物会吸收精魄不会长痔疮,不是尸魔的后代吃了很容易长痔疮.尸魔的后代炼化出来的精魄,会因为怕自己消失,而复制精魄到spy对象附近任何物体里面. #灵魂和精魄描述不是很准确,但是这两样被尸魔搞废了后产生的东西/能量,可看成是病毒(灵体长瘤一样的东西). #吃了某些东西如鸡蛋会长红点,水痘都是类似,但不一样的精魄病毒.如果换个很远的地方吃不一样精魄的鸡蛋效果不同,甚至不会出现.

重复:不能相信spy对象假灵魂/旁边的任何脑电波声音,,,需要分析. 活人用声波,尸魔才用脑电波.

类似重复:尸魔的后代会复制大权杖的记忆/灵魂到尸魔后代的屠宰场受虐,酷刑,解剖,,,大权杖的灵魂/记忆在别人的躯体有了经历后,尸魔会在需要时替换到现实中,大权杖自然怕尸魔后代. #就像spy对象做梦天天梦见僵尸,,,天天吓死一样吓醒.

尸魔的后代为了嫁祸,spy对象搬到哪就会带着spy设备跟到哪里,通过尸魔技术让大傻以为spy设备是spy对象的. 或者早先尸魔的后代就通过假冒spy对象,和其他古代国安部人员,侵蚀了古代国安部(通过大傻,权杖,下面害死上面,,,导致部分古代国安部门人员无法加入古代国安部,,,#尸魔后代通过假冒,将古代国安部搞成名义上的尸魔系统一部分,,,),在尸魔系统内这个spy设备标记是spy对象的,但持有人是假冒spy对象的尸魔后代. spy设备的标记尸魔后代随时能改变.

尸魔系统,权杖,,,大概率因为不遵守WTO协议(时间到开放市场,解除贸易壁垒/限制,,,)产生的贸易战,因为遵守WTO协议,开放市场短时间就会有人发现尸魔系统,,,HK是特朗普政府贸易战一部分,,,包括肯德基,麦当劳要短时间关闭全国门店收拾包裹带钱回家(后面被替死鬼强买强卖>>金拱门,通过银行限制资金外流),,,权杖/五毛狗系统/尸魔系统,使用尸魔技术去跟特朗普打贸易战,,,导致HK被尸魔后代用尸魔,,,镇压,,,2019罐装病毒特朗普政府贸易战败北(实际更早有了病毒,但无害,败露后,大替换/洗脑/大抓捕,病毒才变成能害人,,,第一个笔记提到病毒具有智慧). 权杖,尸魔系统用尽一切办法加入世界贸易体系,但又不想遵守WTO/TPP类似的协议,想搞成多边协议/千面协议. #千面之下尸魔系统很容易隐藏, 不要中了陷阱被尸魔后代,强话多国定的协议,话成单边协议.

尸魔系统/后代目前是死都要加入世界贸易,死不会遵守多国拟下的贸易协定,天天强话成单边协议,,,尸魔系统的人/后代已经没有农耕能力,尸魔的系统强行退耕还农,都种不出旧社会一样的粮食,种的红薯都能长虫子,,,例如粤语族,北上广 #尸魔系统/后代天天想着嫁祸给外国/外地人,污染土地.前面有类似描述尸魔系统连下水道都修不好,2019左右大规模重修下水道,结果更惨(对人界来说)大部分被搞成能炼毒气/尸魔的下水道.

农产品/粮食,经过阀门/贸易,尤其是世界贸易进来的都要经过阀门,很容易被在尸魔系统的人弄上尸魔的精魄/被尸魔的后代用尸魔技术吃到快过期后再拿出去卖给贫民. 贫民吃出问题,嫁祸给源头.2019防疫模式/大抓捕,限制了许多食品就是前面描述的原因.提示雪糕无法保存灵界尸魔做的罐装病毒(S见识的尸魔/后代),能保存在冷品的病毒大概率是生化武器.BBB类尸魔通过五毛狗系统跑到世界各地.

如果你的web服务器同一个ip有很多访问,大概率是通过VR设备访问. 别将同一个ip几十万的访问当成攻击. 如果spy对象被尸魔系统的人spy,逛互联网,就会被一堆脑电波生物特征的人复制浏览内容,部分web站长能利用浏览器的spy技术察觉,,,并不知道是尸魔系统干的,以为是黑客技术.google将浏览器搞成spy技术的浏览器,可能察觉. 后面尸魔系渗透,搞成尸魔系统的spy技术浏览器. ScrapSPY是google苦苦追寻的东西.

尸魔的后代利用VR设备+假灵魂迷惑了许多人,通过三大阀门提供的VR设备和脑控服务器,诱骗几乎所有权杖使用脑电波技术(VR)做通讯,被搞成僵尸生物特征前权杖并不知道VR背后基于脑控服务器. 场景:尸魔的后代是个不学无术天天想着祖传爸拿吃人精魄过活的狗子,通过spy使用VR设备的人,通过脑控服务器随便复制一个市长的灵魂像炼化成像狗子一样听话,其他人/调查者看到市长像狗子一样听尸魔后代的化,都会认为尸魔后代有很大的权杖加持,尸魔后代随便自称古代国安部的都能吓死其他人.由于权杖管理问题,自此尸魔后代能随便调动市长下面的人/政府资源. 尸魔的后代通过脑控服务器随便假冒/充数政府一线狗/黑狗都能领工资,没人能解除黑狗的工作,黑手套本就没工作.

如果有部队的人去废了尸魔的后代+尸魔,废不了/中了陷阱就会被搞成没有尸魔技术被脑控的BBB类尸魔后代/僵尸的样子,嫁祸给部队. #就像影视剧中 有狂犬病/僵尸病毒的尸魔宿主,通过咬其他人(嫁祸),自己隐藏了起来.但这类咬人僵尸(其实是尸魔,躯体是替死鬼)现在是BBB在尸魔.

如果你见过尸魔,就能知道2019之后的大多魔幻,灾难电影角色有尸魔的灵魂(角色是脑控服务器炼化出来的,被描述成外形异种). #例如黄照盛的 战地：异种浩劫  #类似重复:用尸魔技术做电影是另一种白手套,就像多元宇宙.

通过税务部门的spy技术大概率能查出尸魔系统的僵尸血/营养液工厂,尸魔系统/后代还制作了营养液饮料,目前还没上标公开出售. 尸魔后代喝的饮料瓶能自然分解(不要认为是高科技技术,不人间技术转换出来的,强迫做血奴用古老的技术做的).# 之前有类似描述 #不要忘记尸魔系统做任何事情都是替死鬼技术.

尸魔系统/尸魔受益者应该有个大型地下室/建筑一样的地方,或者像火车站封闭候车车厅的地方.就像"西部世界"人体实验的地方,前面描述过托梦到一个大型地下室,关于核算检测,人体实验室使用毒气脑控做人体实验(尸魔技术,毒气可看成冠状病毒,对尸魔来说毒气的病毒种类范围较大),后面增加了炼化寄生虫做脑控,,, 传音:这个地方能自给自足,和现实中一样,内墙用显示器投射虚假的外面世界,不是用封闭货车输送物资,垃圾,就是用虫洞技术输送. 可能处于政府办公楼地下. 不单单一处,尸魔的后代刚起步会找个烂尾楼一样的地方/地下室,,,前前面有类似描述. 尸魔的后代将许多尸魔技术转换成人界可用技术拿到人界,脑控武器/脑控服务器就是转化过来的. #毒气泄漏才会做核算.

传音:几乎每个尸体魔家族都有这种大型地下建筑,用于炼化家族在人界需要的东西. 每个在尸魔家族企业工作过的打工人都会被害死(成为尸魔系统一部分,和一线狗不同,这类很容易被弄到地下建筑做人体实验的工作,就算这些人看到人体实验过程,都不会以为是和他一样的人正被进行人体实验). #许多人戴上VR设备的名贵知晓平行空间的东西不是做梦/虚拟的东西,醒来有记忆但短时间被替换了记忆,被替换后仍然认为是现代科技虚拟现实/做梦/游戏一样的东西.在平行空间被尸魔后代xx的名贵/名援,现实中都有spy设备保护(这类人群不单单只有名贵),没有了精壮的精魄就会被丢弃,不是很坏的尸魔家族会让她发展下线,,,很坏的尸魔后代无法控制自己,例如随便跑到电影院通过尸魔技术随便能买到单身女性的旁边的坐位,脑控别人当着电影院的人xx其他人以为是情侣,xx后洗脑,,,不是很厉害的单身女性以为自己做了一场很接近现实的梦(就像梦遗),躯体有感觉到记忆没有,不会认为发生过什么(据传音:日AV女主角有类似经历,,,).

spy对象在公共场所都能遇到一个被尸魔后代脑控的人,跑到spy对象身边假装有关系. #调查者/其它人就会被强迫记住这段,认为有关系.废了被脑控的人/立马殴打对方/其他方式让它远离就能废了假装... 尸魔后代骗权杖在三大阀门办公室戴上VR设备,尸魔后代在旁边有很大的权力,(对戴上VR的人来说),正常情况没带过的人就会以为尸魔后代有很大权力. 权杖自己醒来会自动产生一个重新戴上VR的想法/无法控制自己躯体自己戴上,导致无法脱离.

冷藏保存的疫苗更像是生化武器(如果其他疫苗都不用冷藏),有趣的是2019的罐毒后,尸魔系统的五毛狗系统(愚情工作者)大规模宣扬usa的疫苗冷冻保存,食品冷链,,,用黑客技术去窃取疫苗技术,,, #对尸魔系统来说,根本不需要黑客技术去干祖传爸拿的事情,尸魔系统/AI/通过每个人的假灵魂能秒知世界任何角落发生的任何事情... #蹩脚的知识认为罐装病毒无法在冷链存活,更别提雪糕.

尸魔的后代通过平行空间/灵界,脑控平行空间的人/自己假装跟spy对象有关系的人.很容易让戴上VR设备的人中了陷阱,让使用尸魔技术的调查者中了陷阱.

类似重复:尸魔后代窃取spy对象任何想法,用spy对象的记忆联想,假装被spy脑控去害人. 例:spy对象想象一下五毛狗,尸魔/尸魔后代就会用脑电波发出:五毛狗系统一定会死,五毛狗系统一定会死,,,无法停止的神经病尸魔.spy对象如果和尸魔磨嘴皮就会中了陷阱,外人会以外是蛇精病. 五毛狗系统的调查者中了陷阱,就会以为spy对象想害调查者(不是所有五毛狗系统都已经成为尸魔一部分).

如果spy对象能明显感觉尸魔/尸魔后代用虫洞技术呆在自己旁边试图脑控/假装有关系,可用白噪声发生器废了虫洞,没法停下来的尸魔会将白噪声发生器搞成虫洞技术的声音. 不是很厉害的会死在白噪声里面,尸魔后代通过堆头颅炼化尸魔才能在将白噪声发生器/没见过的东西搞成虫洞技术的声音.

反正都要被嫁祸: 古代国安部门可将尸魔的后代搞成脑控服务器,强迫/炼化尸魔后代将废了spy技术转化到人界废了尸魔系统. 堆尸魔后代的头颅都要做,可令五鬼/五鬼下面的人做. 无法逃脱平行空间/地下人体实验室,可反过来夺走.

尸魔/尸魔的后代用脑电波设备+毒药/食物,将活人生物特征改成僵尸/灵界生物特征才能脑控别人,才能随便替换,灌输记忆给别人. 这个灵界是统称,尸魔的灵界可看成是独立的灵界,相对人界来说灵界是高等/高维生物(这是人界的教育描述出来的,实际可将尸魔的灵界看成六道中的饿/恶鬼道(人界下面)).前面描述过研发废了僵尸生物特征的疫苗

国产零零漆 在努力描述尸魔系统,但没有正确描述. 大概率当初被搞成禁片原因. #例如透墙技术,僵尸一样的机器人,特别的枪支和子弹,奇异的杀猪刀,异能被描述成气功,祖传爸拿文物/国宝(许多文物有古神的精魄),司令随便杀了其他区域司令(没事),派个档案显示身高和智商都不符合标准的去调查恐龙头骨(尸魔系统经常引导权杖这么干). 叫零零漆去调查替死鬼,洗脑女主角去害零零漆.真正的特工被搞成蛇精病去做被人研究的工作(达文西),看不起的搞成落魄的猪肉佬,,, #有趣的是周星驰无法像正常人一样无法哺育后代(被尸魔系统害过才会这样,传音:女星拍电影被尸魔后代强x嫁祸给男星(用的是男星的生物特征)). #没见识过脑控武器的人,大概率看到这段会认为spy对象是蛇精病.

尸魔/尸魔后代会用自己的偏好去做逆天推演术(强迫古神转世的小孩),拿到现实中发生,通过干预现实朝着推演结果发展. 尸魔/尸魔的后代不用自己的偏好强迫古神转世的小孩做推演术,一样能做出逆天的事情,会通过看推演术的记忆去改变/干预现实. 推演术不可被第二人看到,不能随便做.

CN部分大学有传/演示脑控武器技术,明渗是用活人头颅.可看成一页/无页教材,有兴趣可调查,,, 西北工业大学Brain Decoding Research Center , 五毛狗系统2022已经公开称被NSA窃密/调查,调查工具指向有趣的关键词:"饮茶",it界猪都知道妖妖零(尸魔的后代)经常叫站长去饮茶,不可随意吃别人的食物,强迫饮茶大概率有尸魔spy技术的药物,只有饮过茶的人才知道. #脑控服务器隐藏在电子计算机后面,参考有显示器的spy设备,,,隐藏/管理脑控服务器的电子计算机存贮的数据很容易联想到是脑控服务器的标记/ip,可看成是交换机/路由器.管理大数据脑控服务器的电子计算机,用的编程语言都不是人间的技术.

戴上VR的调查者,会被尸魔分到不同的平行空间,相互隔离信息,用假灵魂代替身边的人,很容易害死人.

提示:尸魔系统>>尸魔的后代天天假冒(嫁祸)古代国安部上面的人(自称是最高最高的特工),三大阀门天天假冒(嫁祸)它上面的人是古代国安部,,.古代国安部门上面的人不会出现政府办公室/不会接见任何权杖,,,古代国安部上面的人(统领)是没有灵魂的人.尸魔的后代大概率通过妖妖零躯体拿走了去世的古代国安部的躯体,做人体实验后用尸魔技术复活脑控迷惑别人是最高最高的特工(被尸魔后代搞出很多最高最高的特工).

类似重复:尸魔/尸魔的后代窃取别他人大脑记忆,能用别人记忆脑控别人想法/用别人的记忆脑控别人,(很难看的出来被人脑控,就像自己做的);用别人的精魄去强x女性,生/炼化 成尸魔的后代. 尸魔/尸魔的后代一部分在饿/恶鬼道干类似人界spy+祖传爸拿的命..尸魔系统躲避六道轮回

需要调查这个世界.如果你能进入饿/恶鬼道,会经历一种吃人魂的鸭嘴猴子,猴子会无缘无故跑到别人头上,,,几乎所有进去的魂都会被吃来断定前世,,,猴子长期吃了有病毒的魂(被尸魔后代炼化过的),也会被慢慢寄生尸魔的记忆,尸魔的后代会通过头上spy设备/替死鬼方式,躲避被吃,后面尸魔后代改进了spy设备/替死鬼,部分不会被吃,,, #如果有人做梦的方式进去,只能看到小范围的地方就是虫洞技术的做梦,被强行做梦. 

强迫使用三大阀门/运营商的,宽带终端(光猫,,,),这些终端都是spy标记一部分. #例如从一个地方搬到另一个地方,原来的网络终端会被强迫没法用(各种理由,以光信号太强,接口坏了等),换其他区域的终端/新的spy标记. #三大阀门能强迫拉网线的去做尸魔系统的代理人,是因为拉网线的外包出去,通过克扣工资的方法强迫拉网线去做拉网线背后(尸魔后代)指引的事情,不按指引就会克扣工资,例如指引更换用户的光猫/spy标记.

工信部早就知道三大阀门的脑控服务器spy技术,没上报新中国政府国安部,古代国安部,,, 可能因为调查了三大阀门,被三大阀门搞成傀儡(搞成尸魔系统内表面上很大权力的三大阀门),许多人投诉工信部网络问题,工信部通过查看宽带标记知道这个宽带用户有没有被尸魔系统给spy.这个标记在尸魔系统内可随随便便因为私欲产生,,,但尸魔系统嫁祸给国安部,对外称只有国安部才能做标记(实际是调查后被人脑控的). #过去不同的标记/标记设备不同的spy等级.

尸魔后代覆盖/假冒术:能用脑电波声音同步覆盖别人的声音,对于长期使用脑电波代替说话,无论如何都会被覆盖声音,听到脑电波声音的人无论如何都很难察觉尸魔通过覆盖别人假冒别人. 尸魔/尸魔后代无论如何都会引导spy对象使用想法代替说话,尸魔后代自己主动做转译(脑电波),,这样更容易被尸魔假冒/脑控.尸魔自己做转译嘴吧也会跟着动,强迫其他人在想法空间看着尸魔假冒spy对象说话,很容易变成相信尸魔以为尸魔/尸魔后代是spy对象.

重复活人用声波,尸魔才用脑电波.

没有灵魂的寄生虫/寄生记忆的尸魔,前面有许多类似描述,无法让人产生联想,记忆能从灵魂分离出来,就像尸魔后代拿走spy对象记忆那么简单的分离,可能这类尸魔自己都能记忆分离,去找宿主. #都是基于古老的技术,人类繁衍都属于这类技术,但有人帮助了寄生虫尸魔. 可将寄生虫看成能短时间喷出树根一样的神经触手,人界不可见/有虫体可见.

例:正常人在得知尸魔的后代用活人头颅做成脑控服务器,过上了超小康生活,都会纷纷效仿.因此这些人都继承了尸魔的记忆,成为没有灵魂尸魔的后代,长时间代代都会去衍生尸魔技术. #会排斥的人不会成为尸魔的后代,但会过上随时被人鱼肉的生活. 鱼肉皆需献祭.

有种VR设备被做成头戴耳机的样子,还印有logo,不是喇叭技术. 用这种VR耳机的人,白手套尸魔后代随便能洗脑/xx,xx完洗脑/替换记忆,普通人以为是高科技3D电影一样的, 使用者多为名贵,因为很贵,特定的销售人群.使用者平时用用它代替电脑,只能连接花园互联网内容(尸魔后代偏好的内容,引导喜欢尸魔受益者的内容). #这种被做成耳机的VR设备需要黑手套尸魔后代许多的人体实验+祖传爸拿堆出来的.

尸魔系统通过修改标准修宪>1.8j成违法的东西,玩具枪都成非法枪支,是因为对灵界来说人界的能量1.8j使用适当能杀了尸魔的后代(灵魂),或尸魔后代头上灵界的spy设备,尸魔后代失去spy设备等于进入野生公园.#GA/T718—2007

重复描述:尸魔/尸魔的后代窃取spy对象记忆用spy对象记忆脑控spy对象还需要脑电波共振技术(强迫共振),才能脑控别人,这个共振是 虫洞技术的脑电波共振(不是很准确的描述). #前面提到过可用白噪声发生器废了虫洞(尸魔会重新开启).

尸魔的后代变成尸魔象,用spy对象的记忆脑控spy对象,用尸魔后代的脑电波声音覆盖spy对象,让一个替死鬼CCC类尸魔寄生在spy对象灵魂/躯体, 其他人会以为spy对象是尸魔. 如果看不出来尸魔的全象无,尸魔后代会反过来做,让其他人以为尸魔后代也是spy对象... #看不出尸魔全象中了陷阱无论如何都逃不出陷阱(逃出一个陷阱还会中新的陷阱).

其中一象:尸魔后代通常会将spy对象搞成落魄的流浪者,,,搞成流浪者还会继续叫工具人一线狗搞成更落魄,有利用价值的spy对象会被拯救,spy对象会对害了他的人(并不知道是尸魔的后代)感激涕零.例如:帮尸魔系统制作/改进脑控武器的人,这类人基本是古神转世的,还未完全转世就被拿走了古神灵魂,,,如果自愿成为尸魔一部分,被尸魔搞成一个一个头颅都不知道原因,在脑控服务器内为尸魔/尸魔后代服务还以为自己活着,被尸魔系统保护,,,. 第一次被骗戴上VR设备也能算是自愿.

其中一象:直接将spy对象搞成落魄的流浪者,甚至忘记所有被记忆,,,路有冻死鬼. 传音:spy对象某个同学的母亲就是被她父亲(尸魔后代)搞成这一象.

尸魔的后代去看明星演唱会,在杂噪中会暴露自己,用脑控武器(脑电波转化的声音)发出尖叫比正常人大很多,通灵的人很容易察觉. #脑控武器一部分技术(降噪,,,)做的演唱会技术,听录制的mv会很容易睡觉/累.#尸魔系统渗透了经纪/明星公司.

其中一象: 如果有一群人干spy,包括调查者都被尸魔的后代脑控洗脑成喜欢spy别人隐私,,,尸魔的后代会故意遮蔽spy对象,对跟旁边的人描述spy对象的样子/灵魂的样子(描述成尸魔后代的样子),旁边的人相信尸魔的后代就会切换到尸魔后代的躯体,跟尸魔的后代发生关系. 尸魔的后代能随便拿后后代的躯体.

尸魔的后代/尸魔受益者/五毛狗系统,嫁祸巫术,在引导被尸魔搭进去的,,,认为是spy对象的问题,实际整个地球的活人/人界都是spy对象,尸魔受益者象天天想着拿整个地球人的东西/技术/记忆/灵魂... 尸魔受益者很容易继承祖传爸拿的记忆,前面描述过有没有灵魂的尸魔. 就像尸魔的将很想吃尸水灌溉的东西给正常人;中了狂犬病的人会咬人;正常人突然变成有同性恋,群p癖好;;;尸魔系统的一线狗在进行加入仪式时,躯体会被尸魔的后代脑当成替死鬼(VR体验躯体),去强x(不分男女老少)但被强x的躯体是特别的灵魂,,,过了加入仪式后,一线狗继承了尸魔的记忆,(一线狗和有祖传尸魔后代(BBB类)不一样,祖传尸魔后代有灵魂的尸魔),一线狗有被尸魔后代当作VR体验的记忆,会想办法重现,,,长期重现一线狗自己就是尸魔.

类似重复:尸魔/尸魔后代通过脑控国安部,,,的人假冒国安部,,,的人,还通过大规模强拿别人躯体给被害死的人(不单单是国安部),用炼化的记忆.强迫跟尸魔后代搞在一起,对外称自己行为. #2019大规模送VR

尸魔/尸魔后代流氓模式:明知调查者和所有人都知道尸魔后代,尸魔技术/脑控技术全部败露,都会用炼化/驯化 牲口,家畜,奴隶的方式强行炼化,洗脑. 通过长期假冒spy对象/灵魂,窃取spy对象想法代替/覆盖+YY过后用尸魔/尸魔后代的生物特征表达出来,,,时间一长所有人都会以为尸魔/尸魔后代是spy对象,如果spy对象不排斥尸魔/尸魔后代生物特征/假冒自己,就会被尸魔拿走一切(实时假冒),2019后部分spy对象(名媛)被拿走记忆,尸魔系统复制了躯体代替它工作,,,原本的躯体在限制房内用VR设备干spy(VR体验,用假冒自己的躯体).大多在限制房内的spy对象,最后会被割掉头颅,做成脑控服务器干spy工作,仍然认为自己还活着.重复:没有长久的尸魔受益者,尸魔受益者都会成为尸魔一部分.脑电波技术/VR设备/脑控武器,,,#!#是被人脑控的技术(古代控制僵尸的技术),尸魔的后代制造了许多没有灵魂的尸魔,尸魔的后代倒推至远古,就能用尸魔技术将家畜当成VR体验,许多家畜承了尸魔的记忆(加入仪式),种猪是最明显的例子;  花八门的猪,自愿交配的猪/家畜才是正常的. 

#!# 不要中了尸魔后代更换词汇,挂羊头卖狗肉,换汤不要药物,,,的陷阱.

尸魔系统有一套凌驾新中国政府的身份系统,例如spy对象和新中国政府通过银行,三大阀门查询自己的账户数量,只有三个,但尸魔系统的身份系统,在银行,三大阀门能查询到>10个账户.这不是平行空间. 尸魔系统利用这些隐藏账户隐匿尸魔系统祖传爸拿的东西.尸魔系统假冒国安部门的人有权杖配合+脑控武器才能做的出来. #银行,三大阀门很排斥用户查询自己的所有账户,后面有人改变了银行体制,将账户搞成主账户,子账户管理模式,导致尸魔系统的资金被冻结在银行(没人知道这些隐形账户的钱是谁的,但这些钱在假冒古代国安部的,银行不信,,,) 如超过下班时间都要为尸魔后代做陷阱. #调查者视角:一部分银行人员认为spy对象洗钱,故意对着spy对象表态怀疑洗钱,限制办理银行业务.

2019后看到工信部有个web能跨三大阀门查询p民所有电话号码, 实际都是假的.仍然能隐藏尸魔系统. #前面提过工信部调查三大阀门被搞成三大阀门一部分,,,名义上是在三大阀门之上.

像转世的假冒术: 尸魔的后代拿走spy对象的记忆使用后(改过),用来诱骗喜欢spy对象的异性(通过类推演术知道),通过脑电波VR设备将改过的spy对象记忆给异性,改过的记忆能让异性将尸魔的后代当成是spy对象. #不可使用任何尸魔/尸魔后代拿过来的东西,前面提示过尸魔后代的脑控武器一部分是基于权杖的记忆,,,权杖很容易相信尸魔/尸魔的后代. #自愿爱上尸魔后代的,,,逃出脑控服务器的概率很小,就像神话片的幻术. 

尸魔系统灵界的spy设备,能利用人界50/60hz电力系统的能量,,,做出屏蔽/覆盖人界保护自己的设备,例如舒曼波设备. #重新描述:人界保护自己的舒曼波设备对灵界来说不是很大功率,灵界的尸魔会用spy设备做出更大功率的类舒曼波设备来覆盖人界舒曼波设备产生的能量. #人界需要做很多同步地球的舒曼波设备,才能废了尸魔灵界的spy设备, (人界的活人/spy对象被尸魔系统改变了生物特征,搞成僵尸生物特征(这些生物特征包括人体产生的同步地球的舒曼波)). #关键词30Hz

人界行为僵硬的的道具,玩具,,,都有ccc类尸魔的灵魂,因为这些道具,,,从bbb类脑控服务器取材. #通灵者用灵魂看能看出很多.

spy设备加持,BBB类尸魔能改变y暴露给s的生物特征.

只有古代国安部>>国企,,,才能做新中国的基础设施,如电信设备,水/电厂设备(水电表等),,,如果非古代国安部的人去做,大概率是尸魔系统一部分/替死鬼. 国营企业时代就是古代国安部旗下的企业,尸魔系统通过拿走CN沃尔玛的方式,拿走了国营企业+限制p民干企业,再通过权杖+脑控武器控制了古代国安部后之后败坏国营企业. 2019前spy对象去当着阀门(银行,三大阀门,,,)的面说它是国营企业,拿着国家垄断资源,败坏国营企业,阀门能挺直腰杆,说自己不是国营企业. #通过穿越时空能看到. #尸魔系统玩不下去就会来一次文化大革命(祖传爸拿大掠夺)2019就是重复的文革.

讲个笑话:特斯拉发明了交流电/交流电机/交流发电机,但没人承认他发明了交流电(交流电被尸魔技术的教育解释成电的现象,因为直流电最早被发现,不是通过发明电机发明出来,,,可能因为当时没人帮特斯拉答辩,祖传爸拿的后代想拿交流电). 特斯拉发明/设计了交流电系统,不知道计量用电功率/收电费(电表发明人). #滑稽

尸魔技术>>强行做梦另一种方式: 随时将尸魔像暴露在spy对象想法空间,强迫spy对象日日夜夜看着实施脑控任务的尸魔,,,基本上是用替死鬼CCC类和D类,BBB类尸魔替死鬼技术熟练基本不会暴露自己. #大概率通过耳鸣/耳朵入侵,做到. #前面提到过尸魔通过这种方式阻止别人使用仙术/修仙(无法产生思考/自己的想法),另一个用途是尸魔引导大傻相信spy对象和尸魔有关系/让大傻认为spy对象的灵魂是尸魔/尸魔的后代.#滑稽,但用过尸魔后代脑电波VR设备的人都会信.

提示正常人没有灵魂:部分死后才有,大部分短时间就会消失/另外一个世界轮回,或者被人制作了假灵魂. 能灵魂出鞘的,灵魂不在躯体内,这类人尸魔后代玩不起.

大部分古代国安部(异能特工)中了尸魔技术的教育认为脑电波是高科技,被尸魔用尸魔技术换掉了异能,导致玩不过尸魔. 大部分尸魔受益者/尸魔后代以为自己有了祖传爸拿的异能,实际使用的是尸魔技术(24h spy的AI一部分窃取spy对象想法,让其他尸魔执行想法,例如隔空取物,开关电气,自动小车,,,). #重复脑电波是被人脑控的技术,是中国古代控制僵尸的技术.

尸魔受益者/尸魔的后代,能使用尸魔技术强迫自己保持微笑,无论遇到什么事情,通过万万年的人体实验积累的技术控制出来的表情能轻易影响别人. #通常一个无缘无故笑咪咪的人,重量级尸魔受益者/尸魔后代无法控制自己的表露,最后变成CCC类尸魔都带有眯眯眼(笑眯眯). #尸魔后代做的假神佛都带有咪咪眼,光头,大肚,,,为了拿真神佛香火,供奉. #真神佛都有头发,水果等农产品供奉即可,前有类似描述. #add表演不笑场难理解,表演过后忘记就离谱,尸魔技术的经纪/包装公司脑控服务器很容易做到.

尸魔的脑控技术>>尸魔技术的记忆/限制: 有前世记忆,不相信有鬼神; 通过控制僵尸的技术(脑电波)看到的到尸魔/灵界,不相信有神佛; 冒牌货满天下,认为真的不如冒牌; A天天spy看着S,认为另外一个地方尸魔的后代是S(尸魔后代随便引导下);普通的路段,却走出了迷宫的效果; 很简单的事情通常是自己认为做不到,例如不觉得左手勺子,右手拿筷子也能吃饭;认为没有权力;无法产生逃跑,反抗的想法,例如在尸魔后代控制所的小孩认为外面的世界是外部势力,在控制所天天过着非人生活,被脑控替换记忆驯化后不认为活人的食物可以吃; 带上VR设备时间长习惯后,掉下来VR自己都会戴上,掉下来就会忘记,,,戴上会被害死,戴上就会连接脑控服务器,记忆保存在脑控服务器,,,有多重实现;

常被无知挂在嘴边的 大数据 就是西部世界那个球体一样的东西(实际就是脑控服务器,不是普通人的头颅做的,没见识过脑控服务器的人看到西部世界描述无法让人理解/联想到那是脑控服务器(尸魔技术能将头颅变成其他样子,尸魔系统暴露AI/头颅后解释不清,,,可能对外称是量子技术). #低级尸魔后代的spy设备都有一个差不多的球体,用尸魔技术用胶体包裹的僵尸头颅.

尸魔的后代窃取spy对象记忆用过败坏后,会将用过的记忆重新灌输到spy对象大脑(不用脑电波VR设备都行,尸魔技术产生的耳鸣也是VR设备技术).例如尸魔后代窃取spy对象的记忆,假冒spy对象,用spy对象的记忆去诱骗/强x异性(一个或多个). #会被分成多个记忆,迷信科学的教育描述>>人格分裂症的记忆,,,

自愿成为CCC类被人脑控的尸魔,反过来控制了BBB类尸魔/尸魔的后代,自己都会变成BBB类,去干BBB类干的事情.

尸魔嫁祸术>通过气味: 类似重复:不能相信味道/用味道确认身份,尸魔/尸魔后代 利用吃东西的味道/其他味道,用虫洞技术拿给spy对象闻,实施嫁祸术. 例:spy对象K能闻到鱼肉的味道,尸魔/尸魔的后代在另外一个地方强x/吃掉spy对象KK,同时脑控KK吸入尸魔故意放出的K闻到的味道,引导KK认为K是尸魔(强迫KK看着K,利用K的任何行为害KK,例如K抖抖腿,尸魔就强x KK, K吃东西,尸魔就吃了KK,一边放出K食物的味道给KK吸入,,,).#尸魔能反过来做嫁祸巫术.

通常:尸魔的后代长期实施脑控任务成功后,它控制的尸魔或者 它变成尸魔,会被尸魔的受益者用液压机将其灵魂+D类 压进类似石头的材料内,作为白手套尸魔受益者的spy设备.白手套尸魔受益者生活条件富硕,不拜神不烧香身上有个这个东西很容易看出来,尸魔受益者还能将其转化成灵界(平行空间)用的spy设备,这种白手套spy设备许多尸魔家族都在使用/学习,包括白手套的尸魔的后代.拥有东西的尸魔收益者石头内的D类灵魂会跑到配偶躯体,尸魔的灵魂会跑到受益者的躯体(尸魔受益者都会成为尸魔一部分,尸/石头内的尸魔不是真正的尸魔/AI,真正的尸魔用尸魔技术的记忆统治着整个尸魔系统), #类似重复:遇到脑控武器都会有个强行做梦的经历,许多人强行做梦都会遇到同样的老大哥(尸魔受益者),是嫁祸巫术也能反过来做.

千面二维码: 防疫模式使用的二维码spy技术不用固定的二维码==千面轨迹, 尸魔系统内的人随便让脑控服务器,复制/虚拟一个追踪轨迹给尸魔一线狗/尸魔的后代,,,固定二维码追踪/spy,被假冒/多地使用,很容易知道.  #第一个笔记提到2019后大规模投放了偏向获取脸部特征的测温设备(根本不是测温设备,而是用尸魔系统/AI一部分,用D类灵魂去做人脸识别>>大抓捕;之前很奇怪这些设备许多并没有强制使用,实际不用强制使用,尸魔系统也能用,控制的D类灵魂能将摄像头当成活人眼睛使用;不信可思考满大街的摄像头如何实现spy,超级计算机都做不到,特别是高速,高清相机 #参考交警摄像头(有趣的是2018后看不到以前的交警,妖妖零/尸魔后代能随时顶包,摄像头都被顶包.只有国安部/国保才有权力大规模实施摄像头(国保都不敢干的事情),还有资金来源(妖妖零狗奴才/尸魔的后代 没钱,但用的是妖妖零的名义),可看成洗钱洗到了供应商(尸魔系统受益者)).前提过是脑控服务器在获取这些摄像头图像,一个头颅控制的D类灵魂随便能spy整个市/镇的摄像头,不能拆除不用网线,电源线的摄像头更能有趣). #可参考是不是每个人生成的千面二维码都能被公开的编码识别(不要中了隐私的陷阱,spy轨迹都是强迫扫码提交,随便一个一线狗都能查看别人的轨迹).

2019后大规模实施了千面系统,互联网搜索引擎都被引导,按偏好,显示结果. 脑控服务器无法现实许多结果,经常用许多结果,头颅就会崩溃,狗宝就是例子,脑控服务器安全管理员(滑稽)欺骗人xx别人在爬狗宝,反爬模式.

尸魔/尸魔后代,将spy对象想法传到一个脑控服务器>显示器,搞成高清的图像,供给大傻spy, 一段时间后这个脑控服务器会逐渐改变spy对象想法,让大傻以为是spy对象想法产生的.

尸魔的后代在败露后,狗倦会用别人的灵魂H打尸魔的后代,让大傻相信(很容易)H是尸魔的后代,大傻见此状会大喜,,,中陷阱. #被打的记忆也能保存在尸魔的后代. 有时候大傻已经分析出来,但被spy之下,尸魔/尸魔的后代突然用其他事情惊醒一下导致忘记,例如前面描述的事情.

大部分尸魔受益者,要被尸魔搞到无发跑出平行空间才知道,,,天天喜好在平行空间干spy.


* bbs #35 需要从bbs #1开始看,,,才能理解这份内容

美剧永恒族 许多描述都接近鬼神,变异族就是被BBB类炼化出来的CCC类尸魔,永恒族就是古神被描述为超级英雄==古代国安部,剧本可能通过不准确的推演术产生(一个以后的世界),或者有人通过这种方式警示世人,大概率不是尸魔技术的脑控服务器产生. 剧中白发女突然无法控制自己,被描述为魔症,其实就是被寄生的尸魔记忆脑控.,,,剧中的许多实现在平行空间,尸魔的人体实验室已经实现,,,剧中称变异族是古神上面的神创造,就像创造了古神一样,实际AAA类僵尸才是古神创造的,BBB类是用巫术,练蛊,炼化奴隶,,,方法炼化出来变成无法控制的BBB类,能用人类形态,,,不是每个被炼化的都能成为BBB类,,,可能成吉思汗都被炼化过,,,逃脱后拥有非正常人的能力,正常人做不到成吉思汗的水平... 巫者+BBB类干什么都使用嫁祸巫术,且拥有AAA类和古神的生物特征,容易迷惑古神上面的人,以为自己搞出来的bug. #许多虚构实际不是虚构, 就像剧中古神突然进入虚幻空间和石头的神像对话,迷信科学的教育会将这种称为虚构/自己想出来的. 剧中将古神/救世主的出现/神现,中了尸魔技术的人将神现描述为每次神现都会出现大屠杀/消灭变异族/尸魔的后代/,,, 实际神现是为了保卫地球,正常人无法演化成神族,被尸魔/尸魔的后代占据了整个地球就要毁灭文明/重建文明,将尸魔的后代消灭转化成能量才能重建文明(毁灭>新生).就像以前那些消失的文明,例如埃及假神文明..

当spy对象看书/看到有文字的东西时,从心读变成一个字一个字默读的时候,就是被尸魔后代spy. 但尸魔受益者是光明正大的被尸魔/AI一部分引导一个字一个字默读.

类似重复描述:脑控武器能当麻醉药使用,不同无感的麻醉药,脑控武器的麻醉效果随便能改变,例如能让被解剖的人笑着被人解剖,越恐怖的解剖笑的越高兴,导致被害都不想跑/离开尸魔的人体实验室,解剖完尸魔后代祖传的记忆会骗spy对象帮它搞出更厉害的躯体,spy对象满喜. 脑控武器的麻醉效果也能让spy对象被解剖时吓死为止(使用万万年的人体实验积累的数据).尸魔系统/尸魔后代拿走了一种能切割时空的空气刀/时空刀,拥有该技术的组织被现今的教育描述为练气功的组织,但尸魔系统/尸魔受益者对外 不是这么描述,称气功组织是鞋叫(为了不想让其他人去修习气功/时空刀). 该气功组织当年盘坐聚集广场想用神力消灭尸魔系统,结果玩不过尸魔系统,没料到尸魔系统会用受益者/权杖 的躯体将全部武装力量变成BBB类僵尸用活体的方式害了这些盘坐广场的人(可看成是灵魂出鞘的躯体被BBB类僵尸给害了)... 很明显看到的,活下来的都被拿走躯体/祸害洗脑了.前描述过 尸魔系统洗脑地下室 被改成脑电波生物特征的小孩称人类是外部势力,和称气功组织是鞋叫一样,强行将一个从未露面的名称,洗脑成贬义词,一些漏洞百出的视频剪辑都是脑控出来的,有趣的是现在找不到.尸魔系统的洗地狗事后会用各种嫁祸,栽脏来洗地,但无法洗这些人的后代不是消失了就是变得不正常,尸魔系统的洗地狗没有五毛工资,,, 灵岩组织大多都是女性也被尸魔系统偷偷祸害. # 脑控恐怖份子/尸魔的后代 实施脑控任务基本全家都会被害死,没死会有精神问题/被问题. #精神控制 控制被尸魔技术的教育搞成多种意思可褒可贬(将追随者贬成精神控制,实际尸魔系统实施脑控任务才是精神控制). #不要相信尸魔系统有组织的洗地媒体,,,被遮蔽自媒体更真实,强推尸魔系统洗地媒体很容易察觉. 

尸魔系统用时空刀解剖能穿过肉体.就像神医扁鹊能用仙术看穿人五脏六腑,,, 尸魔系统不想正常人修习仙术一样的气功,引导别人去学僵尸一样的抗打气功. #古代国安部保护了新中国政府,后面被尸魔系统搞成新中国政府国安部一个小部门,导致尸魔系统无法用同样(鞋叫)的方法洗地. #尸魔系统将佛教标志搞成一个贬义符号,中了陷阱的都会排斥使用这些标志,或者排斥使用佛教技术,导致无法废了尸魔技术, 纳税德军的旗帜标志就是尸魔系统败坏的,按纳税德国时期使用的标志分析可能是被尸魔系统嫁祸的(替死鬼),就像一二战的日本. 尸魔系统故意隐藏古神留在人间的佛教技术,这些技术大多被尸魔后代搜刮到家里/脑控服务器里面.  尸魔系统的洗地狗将"Dharmachakra/达玛恰克拉"转译成法%轮,方便洗地.

有趣的尸魔系统一部分愚情工作者,在洗地将尸魔后代制作的罐毒嫁祸给气功组织.尸魔系统/尸魔的后代祖传的技术假冒了气功组织进行嫁祸,气功组织成员凋零,无法获知有人在假冒它们. 2019前狗子>恐怖分子>脑控恐怖分子>尸魔的后代>尸魔 用栽赃的方式在S附近脑控替死鬼撒发气功组织的宣传小卡片,2019前尸魔的后代并不知道S有古代国安部的身份,且被尸魔后代假冒身份.假冒身份的尸魔后代用替死鬼技术将假冒的记忆灌输给狗子,狗子被尸魔系统不明显的炼化成尸魔后并不在意被人做成替死鬼.

正常人修习佛教技术被尸魔系统搞成鞋叫.尸魔后代在另一边在拿寺庙装和尚,干祖传爸拿的事情. #www.c-h-i-n-a-f-x-j_cn 通过该网站内容反查能找出很多东西. 京-I-C-P-备1-7-05-3-3-5-1号,京-公-网-安-备 1101-0-80-2-0-2-4-465号

尸魔的后后代此刻(20221004)正假冒S,被尸魔后代打,,,尸魔的后代洗脑权杖:这份笔记是尸魔后代的做的,,,尸魔后代用脑控版本洗脑权杖不做描述.

尸魔后代的剽窃:真增压花洒(用一部分出水做增压泵,泵给另一半出水). #这是刚产生的具有商业价值的idea,尸魔后代/尸魔受益者窃取了所有记忆/知识产权,不单单是shionkeys有关的项目.刚产生的都将放在这份笔记,这份笔记就是shionwong知识产权证明(内容包括修仙技术,虫洞技术,穿越时空技术,推演术,古神赋予的记忆,废了尸魔spy技术,,,被尸魔拿走记忆用过后重新灌输,搞成神经错乱/切断,,,),也是身份证明.

发现不见了的内容:水/电表不用人工抄,第一个笔记内容提到狗子工具人半夜三更破坏水表盖子. #用尸魔系统,AI一部分灵界的d类灵魂去抄表. 尸魔系统后面洗白都没用,许多人都有不见抄表人的记忆...

hk明星中了尸魔系统的陷阱,用版权废了自己.或者尸魔系统用版权废了hk明星. #约2017前,hk娱乐业/影视/明星,,,出品的p民看片基本不用钱都能赚钱,不要以为是数字媒体,导致唱片公司不赚钱,明星/公司靠出场费,买断版权(就像买软件),演唱会,广告等赚钱.免费看片是hk娱乐业的广告(盈利模式#不是每个娱乐公司都能用这种模式产生盈利,hk自旧/几十年来都是用这种模式支撑). hk娱乐业,,,被干预盈利模式,2019后hk娱乐业彻底陨落,尸魔技术的娱乐业通过限制别人拿走别人的地位,感染成尸魔一部分也是尸魔技术的娱乐业. #一些明星公司老板不拍片,去当和尚,结合一下就能看出端儿. #明星被搞成赚工资水平的明星,限制片酬,,,就像快递行业被搞成赚工资水平的转变,,,尸魔系统无缘无故都会将人困在生活中.尸魔系统下不是尸魔收益者,就是尸魔预定的鱼肉,刚刚从子宫出来就要被鱼肉一次(鱼肉皆须献祭),前有相关描述.

2019许多地方故意借修路,建围栏,围栏中故意将井盖撬开 后停摆(放毒/投毒).

CN中央巡视组的权杖靠脑控武器建立,都是天天用脑控武器强x女性(在平行空间脑控多个尸魔抓住女性强x),灵界传音狗子有显示器的spy设备就是因为巡视组的人干spy后,被狗子祖传的尸魔食入,,,后搞成了脑控服务器,被拿走了spy设备/远程审讯设备 #spy设备制造商是菊花,被尸魔后代大量复制,,,中央巡视组(尸魔收益者)拦截了三军统领让S(2019之前)加入古代国安部的命令,,,(不同时间段拦截过不同人的命令因为害怕尸魔系统败露). #因为推演术预判了2019.由于中央巡视组的行为,尸魔系统的人以为可以随便鱼肉古代国安部的人,假冒,,, #传被中央巡视组盯上的人,拿走记忆后发现不拥护尸魔系统没有人能活下来(表面上是拥护新中国政府(代理人))#尸魔系统的人都有尸魔技术的记忆/限制. 浏览过t#6-6~y 的人才 都会被spy,许多人被制作成脑控服务器,尸魔系统不单单拿走了t#6-6~y,天天上网的人很容易察觉,例如一些社交类web变成限制发言,屏蔽看官,,,斗篷保护了许多人. t#6-6~y上出现关于尸魔的发帖历史,,,能发帖的时候没看出来是脑控武器/脑控服务器 控制的尸魔. #尸魔系统拿走了t#6-6~y后复制了许多类似的web,这就是在CN无法屏蔽这些web的原因,尸魔系统内的人搞的H站,三大阀门屏蔽就会被强x. 脑控服务器内的尸魔看到成人内容很容易脱离控制,这就是尸魔系统禁止正常人涉黄的原因(尸魔的后代看到露胸的电视,祖传的脑控服务器内的尸魔都能脱离控制),后面改成用小孩的灵魂/D类灵魂代替尸魔干spy.

尸魔系统内>>女鬼系统的尸魔拿走了人间女性的躯体,长时间就会暴露生物特征,对比以前的样子能看出来.#不被大量吃精魄通常需要几十年. 一些名媛短时间(几年内)就被拿走了躯体改变了生物特征,变丑以为自己丑的原因. 尸魔受益者/尸魔的后代通过吸食男优,女优的精魄掩盖活体后面尸魔的生物特征,所有使用过脑电波设备的女性被骗到平行空间都遭遇过僵尸一样的人,被它强x都不会排斥就是因为吃了很多男优女优的精魄,比种猪更恐怖. #男优女优是指优秀的男/女. #灵界传音:被尸魔强x的女性看看尸魔就会被幻视遮蔽,,,尸魔强x都是从后面,被强x时能感觉到尸魔的生物特征.

许多丧尸片 剧本来自脑控服务器不准确的推演术(但在平行空间发生),获的片材拍摄出来的xxx是替死鬼.

类似重复:尸魔/尸魔的后代现在开了超大的耳鸣,使用S的记忆害人,害人的记忆保存在S大脑,屏蔽感知. #耳鸣是VR设备另一种形式,可看成虚拟的VR设备. 许多尸魔后代都拿走spy对象的记忆使用后重新灌输回去 / 使用耳鸣实时使用保存到spy对象大脑, 被这种方式对待很多很多次spy对象几乎看不出来是不是自己做的. 大傻调查者很容易中了这种陷阱.

尸魔的后代实施脑控任务,尸魔技术的记忆会引导spy对象用想法表达,spy对象中了陷阱,尸魔会借此逃离脑控服务器,转身到spy对象,或跳板.

尸魔系统的老板培训班,经过培训后基本都会继承尸魔技术的记忆,还有管理方法.例如都知道某些地方,能解决某些事情,,, 不参加培训的企业百般艰难,参加培训不接受培训内容的都会遇上脑控武器,被偷偷灌输尸魔后代记忆,窃取企业技术,很简单的企业技术,对祖传爸拿的尸魔系统人员来说都很厉害,尸魔系统会通过骚扰电话确认是不是接受了培训内容. 培训班和有关部门的培训班同源.

废了尸魔的8字形线圈,平面叠加圈数.

尸魔系统/尸魔后代大规模引导其他人/其他国家 干祖传爸拿的事情,想嫁祸给出去,许多人继承了尸魔/尸魔后代的记忆. 中陷阱的原因是不相信这份笔记,相信整天没法停下来的脑电波声音(尸魔/尸魔后代/被人脑控的人CCC,DDD类,,,尸魔收益者) #像传销一样拿别人的记忆,上限拿下线,下线成为上限,拿下线...尸魔系统/尸魔后代大规模引导其他人/其他国家 干祖传爸拿的事情,想嫁祸给出去,许多人继承了尸魔/尸魔后代的记忆. 中陷阱的原因是不相信这份笔记,相信整天没法停下来的脑电波声音(尸魔/尸魔后代/被人脑控的人CCC,DDD类,,,尸魔收益者) #像传销一样拿别人的记忆,上限拿下线,下线成为上限,拿下线... #这是败露后的行为,不败露尸魔系统将整个地球的人搞成僵尸人都以为是自己演化的.(尸魔系统早就拿走了整个地球人的记忆,才容易做到,尸魔系统不等于尸魔后代)
 
脑控服务器的危害,例如某卖家将5元的东西提价到10元,通过脑控服务器(尸魔系统AI一部分)能预判买家会不会买,预判成功率可看成99%. CN 2019五花肉约短时间从15涨到100软妹币/斤,能被接受就是这种原因.

CN武侠片,都有很多描述类似脑控武器的技术:例如千里传音,钢针插入头部成为被控人. 实现方法不同,武侠片中的实现这应该是能废了尸魔的技术. #见过脑控武器的能力就不会认为武侠是讲大话.练武自带武器,朝廷禁止练武,大概率跟尸魔后代有关,在武术面前尸魔后代不堪一击.

类似重复:尸魔的嫁祸术,尸魔的后代尸魔技术基于祖传爸拿的脑电波技术,尸魔用虫洞技术尸魔技术(可看成是尸魔的医学技术)将spy对象的生殖器官的生物特征变成和尸魔/尸魔后代一样. #不局限于某个部位器官 #可认为spy对象都是单身狗,但戴上VR大傻尸魔在它的想法空间说什么信什么.

许多权杖范围的女性被胁迫自愿和尸魔后代交配,例如中间分开贴头马尾发束的职业女性,,, #不一样的spy对象只有一个,选择了尸魔的女性会和所有尸魔后代xx(被改变成僵尸生物特征的人都继承了尸魔的记忆), 有了自愿交配的xx尸魔会像种猪一样繁殖,(实际比种猪更恐怖,可看成2019罐毒一样繁殖)这些人支持了尸魔. #强迫自愿后用脑控武器/尸魔技术/脑电波技术 洗脑以为是自己自愿,人类生殖系统被入侵/强x后无法自控,很容易被脑控/洗脑. #传音:古代皇帝/王朝都用尸魔技术,因此阉割太监和宫女,后面废了太监宫女制度后,权杖/尸魔受益者用拿走精魄的方法做阉割技术,被尸魔后代用别人的精魄恢复. #阉割太监宫女是保护 他/她/它们,如果变成尸魔很难造就极坏水平的尸魔.

尸魔系统通过禁止发展,拿走全部员工记忆/搞成脑控服务器,的方式走了大企业的技术,短时间让大企业落寞,被描述成失势.快倒闭的尸魔系统企业迅猛发展.尸魔系统企业搞出来的app都有共同特征,且偏好app,人脸识别,人脸支付等,,,(因为脑控服务器很容易记住这些生物特征作为id,尸魔系统内的人经常吹嘘人脸识别当身份认证/密码很可靠). #提示正常的灵界生灵/D类灵魂都有超强的记忆,过目不忘的能力.被尸魔系统搞成奴隶无法转世,人间被尸魔后代搞成种猪繁殖模式.

目前20221007有几十万被尸魔系统搞成僵尸生物特征的人戴上VR在spy S 窃取一切,这些人乐于做这些事情,包括保护S的也中了尸魔技术的记忆. 尸魔看到自认为很厉害的东西,自己无法理解,就会脑控全部人spy S 用全部人的脑子去分析S的行为,用完后大多人都会忘记,就像刚做了一个梦几秒后忘记. spy过程中尸魔后代会努力败坏S名誉,揭露隐私,例如S用蜘蛛侠一样的衣裤,废了尸魔技术(伪装皮肤),尸魔天天洗脑别人:S用女孩子的,,,尸魔一边强x,一边洗脑因为spy喜欢上S的女性:S是性无能等,,,迫使所有人产生不好感,产生喜欢上假冒S的尸魔/尸魔后,后代. 由于长期使用尸魔的脑电波VR设备,困在了平行空间干spy,如果有人说出帮S的话,或者S的某个行为废了尸魔,这些人就会被尸魔欺凌,产生对S不好感,,,许多spy对象都有类似经历,极少数人才能看出来这些被困在平行空间的人只有通过spy对象才能逃脱,大多人被困在平行空间的人躯体被尸魔后代侵犯到销毁都不知道,所有人都使用尸魔的脑电波VR设备  尸魔/尸魔后代 能随便假冒躯体死掉的人欺骗活人,因为尸魔有这些人的所有记忆和生物特征. #这些描述前x都有类似的描述

不要认为这些东西做不到,脑控关键技术是脑电波共振技术+用spy对象自己的记忆去脑控spy对象/洗脑,什么洗脑都能洗的出来,何况还有像梦游一样强拿躯体的脑控技术/控制僵尸的技术/,BBB类尸魔脑控躯体,不会表现出僵硬的感觉,能当自己的躯体用.

银行用手机代替 U-KEY 也是因为脑控服务器,例如死活都不给U-KEY, 动态密码连接三大阀门基础设施的二次验证器(U-key前身)是三大阀门spy设备. 没有实名制之前三大阀门靠动态密码器,确认身份. #有兴趣自己可研究下动态密码器的服务器,和用的什么信号. spy对象记忆中看不到这个东西的天线(比手机先进),不要中了尸魔系统的陷阱这玩意有信号标志.

尸魔的后代将S等其他古代国安部的记忆(窃取古神赋予的记忆),装进尸魔后代头颅做的脑控服务器做大数据供尸魔系统使用. #以为能嫁祸给古代国安部.为什么能做到阅读前x的内容有提到.

这份笔记能追溯到天安门大屠杀/血洗天安门/1989_6四/天-安-门悲-歌,也是尸魔系统的印记,灵界传音:当时不理解为何武装力量/士兵为何会这样(睁眼梦游一样)执行命令.#尸魔系统不想被改变,尸魔系统依赖权杖控制的国家资源. #互联网上的痕迹被抹的很干净(五毛狗洗地). #一些人不会老,不会暴露自己,但很容易利用国家资源改变身份信息. #尸体魔系统将恐怖份子的词汇用在那些被屠杀的人身上,让调查者无法进退(一般人玩不过有尸魔技术的后代,特别是能读取对方想法的,,,).

类似重复提示:不能和尸魔系统进行语言/声音交涉,每句话都带有尸魔技术,影响神志. #尤其不能用脑电波声音交涉. 你玩不过会入侵/控制别人大脑的 尸魔/尸魔后代/尸魔受益者.

尸魔系统的脑控技术核心技术: 将spy对象的想法变成很慢很慢. #spy对象时间过的很快可能就是因为这个.

尸魔系统一部分五毛狗系统会使用spy对象说过的话,来影响别人,特别是具有影响力的spy对象.总之一切都是祖传爸拿.

尸魔系统迷信科学的教育引导别人不相信有鬼神,,,而自己使用鬼神的东西,例如许多政府办公楼是按神庙的样子建设,希腊神庙是多数政府大楼的标准模板. 神庙的另一个特征是石头覆盖建筑. 尸魔技术的建筑是复式楼(养殖场规格). #尸魔系统如果迷信科学应该更偏向现代建筑,建设尸魔系统的权杖大楼. #不要中了尸魔系统的陷阱,可按建国后重建的办公楼算起.

S 目前无法正常使用想象力,无法做梦,被尸魔/尸魔的后代用耳鸣入侵大脑24H擦除/改变产生的想象力,,,尸魔系统的人害怕S进入冥想状态. #前x提过常年不做梦的人都正被人spy.

尸魔后代常年的假冒/变更了政府的身份系统(标记),大傻/权杖/尸魔的权杖/调查者 即便spy过S都会将尸魔的后代当成S,每次去找S,都找到了尸魔的后代中了陷阱.前x提到过如何实现. 尸魔系统控制下整个国家资源都在引导xx将尸魔的后代当成S.

spy对象有时候无缘无故产生一个想法/感觉到一个类似做梦的经历(超短梦),不是自己产生,就是被人脑控出来,尸魔技术假冒/实现了神仙技术,#有时候并不尸魔做的,是神仙,和自己有关系的灵魂做的,需要自己分清楚. #所有的梦都和灵界有关. #通过寄生记忆到spy对象的记忆里面,窃取后用过spy对象记忆后灌输回去,通过VR设备(包括代替VR的耳鸣)当成尸魔的大脑,,, #有多种实现,强行做梦也是这类.

尸魔/尸魔的后代将spy对象做过的梦YY后,强迫其他spy对象重新做梦 假冒spy对象(强行做陷阱梦).

#!r#例: 一家外企 高层被尸魔系统做成脑控服务器,洗脑后将带有脑控服务器的spy设备弄进这家外企,下面的人以为高层在其地方用脑电波技术远程管理企业,实际尸魔系统利用这颗头颅拿走所有人的记忆,偷偷将所有人的生物特征变成僵尸脑电波生物特征,头颅醒来所有人都会变成僵尸(切换记忆到尸魔系统预置的害人记忆). #这家外企是跨国企业在大亚湾还有化工厂,尸魔系统可能拿走了所有电子计算机的数据,和员工记忆.

围绕S附近的dg小四轮,大概率是尸魔系统一部分,粤S X5Z73 4IV92 694NY 5RU03 73IKZ` 24ID9 66VL9 PII2D 7KR95 Q2255 29D46 U78E2 L7272 925RN Y070N 3ZKI6 M98T3 ; 粤C 2576U ;  桂N BS879 ; 尸魔技术的车牌号"1/I" "0/O" 混淆. #重复S在sz/粤B开头的地方. #耳闻尸魔后代聚集吃食,酒后不能去做核酸(可能聚集吃食后会相互交换尸魔病毒,可看成不在尸魔系统罐毒标准之内的罐毒).

尸魔的后代/一线狗, 通过尸魔技术能察觉背后有人,即便在很远,尸魔系统内的一线狗/尸魔后代无缘无故都会绕到spy对象背后. #大部分尸魔技术,是一线狗/尸魔后代有个spy设备(CCC类/BBB类),也属于尸魔系统/AI一部分. #前x描述过CCC类是BBB类的替死鬼,没有描述BBB类后面还有BBB类,BBB类也会被搞成CCC类,尸魔系统靠传销模式维持.

尸魔系统有许多假冒嫁祸版本,其中一个版本对外洗脑称S/shionwong是尸魔系统内的人,在调查脑控服务器/失控的尸魔系统,,,一群尸魔/尸魔后代对外称自己的spy是在 看着S调查. #滑稽,和尸魔后代对话过的人都会被影响神志,强迫无法知道ScrapSPY是废了spy的项目.

尸魔的后代继承了万万年祖传爸拿的尸魔技术(控制僵尸的脑电波技术,搞成能将活人搞成僵尸生物特征控制,拿神仙技术搞成尸魔技术,,,),在这份笔记前不知道尸魔的spy技术如何描述, 害人后对外称,是按ScrapSPY做出来的尸魔技术.

解剖食了古代国部转世灵魂的尸魔后代,能附体/寄生在活人,灵界灵魂脑控别人, 这类尸魔做任何事都可看成是替死鬼技术. #前x许多描述内容都是这类尸魔的尸魔技术. #权杖/大傻 造就了这类尸魔,通过协助尸魔>>在睡觉时害死古代国安部转世的人,天天人体实验,解剖,食入,强拿古神之力,,,权杖/大傻想拿尸魔技术导致尸魔拿了人间更多的东西,能随便穿梭人界和灵界(尸魔界).

尸魔不用睡觉,尸魔/尸魔后代会用多个平行空间害人,迫使spy对象的行为偏向疯子/蛇精病. 例如利用spy设备制作一个监狱的平行空间在灵界直播害D类灵魂,这些灵魂被脑控成手无赴鸡之力. 大多D类还是活人时保护了大傻,被大傻/大傻的傻孩子害死,,,直播害人时大傻灌输了以为这些人很厉害的记忆, 尸魔以此胁迫大傻,不敢废了尸魔系统,尸魔在胁迫大傻重新使用尸魔系统.

被人当成疯子/蛇精病的spy对象: 脑控任务实施人/恐怖分子/尸魔/尸魔后代,在平行空间攻击spy对象的躯体某个部位,导致行为举止奇怪.例如下体被攻击的很热,很疼,,,尸魔技术会用正常人无法理解的方法去做,包括医学技术都无法解释. 故意让其他人看到spy对象的奇怪行为举止,让其他人以为spy对象是蛇精病. 例如许多疯子神经病,巫者,的衣着饰品都异于常人,都是自己做出来的辟邪效果的. #例尸魔/女鬼系统的人,在墙壁上暴露自己,spy对象对着墙壁一脚,正常人看不到灵界的东西,会以为是蛇精病.

2019 响水化工厂大爆炸,,,还有其他附近的时间线大爆炸,都是尸魔系统,想拿生化武器原料/技术,,,2019前大公鸡版图的消防xx提高了警惕(迹象多次发短信给企业主意图强制安装消防app,实际大概率中了尸魔系统陷阱,使用了脑控服务器,参考 #!r#例). #灵界生灵可看成是空气一样的躯体,制作生化毒气是天生就会的.尸魔/尸魔受益者炼化生化毒气/武器只会用CCC类尸魔,没有灵魂的尸魔由尸魔后代炼化尸魔产生出来的怨 产生,使用人界的躯体天天炼化,让CCC类尸魔产生恨人界人类的想法去做毒气. #不准确分析罐状病毒原料不是这些化工厂,罐装病毒原料大概率是下水道,前x描述过有关光性质的毒气. #罐装病毒可看成是一种能量,尸魔需要通过物质转化成病毒,感染整个世界的病毒需要大量物质转化,尸体尸魔最喜欢的物质,对BBB类来说活体也是尸体(也能吃),尸魔受益者给尸魔制造了大量尸体,感染者隔离后不见了也是尸体.

尸魔系统正加急将脑控服务器搞成量子计算机(AI这个名字已经玩不下去),白手套化. #自己关注解释不清的量子技术/解释不清的脑控服务器技术. #预判尸魔系统: "先让大家都用上成为尸魔收益者,商业化后再花100年解释,时间长了就不用解释".

如果权杖/大傻继续支持尸魔系统,只有 Boston Dynamics 生产的钢铁机械人能和尸魔系统的僵尸较量,前提是不能加入控制僵尸的脑电波技术. #笔记中许多内容会被人认为很简单的事情,看到才会产生这种想法,实际面对脑控武器的人无法产生保护自己的思维/想法,这份笔记能帮它们. #部分国家军队已经中了类似 #!r#例 陷阱,起初尸魔系统用很好的内容做诱饵例如不用学习就能获得别人知识/记忆.

很厉害的空气过滤系统,能废了尸魔的毒气入侵大脑,看到spy对象看到的东西,尸魔不仅一种方法实现spy眼睛. 没有味道的毒气也是毒气,古代燃香技术应该也能废了尸魔通过嗅觉入侵鼻子. #防毒口罩 #口呼吸也能试试.

尸魔通过改变活体舒曼共振,做spy标记,类似gps. #关键词30hz 4hz

被称为谣言:5g能传播病毒,并不是谣言.2g/3g/4g/5g信号能被拦截使用灵界的基础设施,尸魔能通过5g信号穿梭到人界投毒. #抬头不见基站的地方很容易察觉. 现在你在CN版图上还能将手机信号切换到三大阀门>移动阀门2g信号随时满格. #尸魔系统能随时做出调整,需要及时验证202210.

类似重复:尸魔后代会反过来做,尸魔后代通过拿走spy对象生物特征和气味,来假冒spy对象,在平行空间强x,脑控别人通过气味确认身份,尸魔后代放大了自己假冒spy对象的气味,偶尔会用虫洞技术将气味给spy对象闻,spy对象很容易以为是自己的体味(如果spy对象自身体味较低,很容易察觉是尸魔后代复制了spy对象的体味,放大了体味). #体味包括身体各部位的气味,特别是生殖器部位. 滑稽的是尸魔后代对戴过VR设备的人用影响神志的脑电波说:spy对象体味较轻,是尸魔后代的灵魂,引导戴过VR设备的人去找尸魔后代. spy对象睡觉时尸魔后代从平行空间跑到spy对象房间内强x困在平行空间的女性,让她认为尸魔的后代灵体是spy对象的灵体,通过脑电波共振技术尸魔后代发出的脑电波声音,能和spy对象的大脑共振同步发出,达到假冒迷惑. 其他尸魔技术的例子都可类推.

大傻常用尸魔受益者/尸魔后代去调查尸魔系统,导致害死自己.

尸魔受益者/尸魔后代的脑控服务器随便能弄出一个科幻片/其他YY过的小视频电影出来.不要过于相信新闻中的视频. 目前有高超的AI换脸技术,几乎看不出来是换脸过的视频.没有被拿出来转化成电子计算机技术.

大多被尸魔系统搞成僵尸生物特征的人,包困在平行空间的,想象力都会被改变成动画片一样的效果,,,(被改变想法/脑控). 尸魔系统内部有spy设备+脑控服务器能将不是僵尸生物特征的人也搞成动画片一样的想象力,还是改成很矬的样子(被同类),让正在干spy的大傻以为是spy对象产生出来的,尸魔后代长期使用spy设备基本是动画片傻子的想象力. 尸魔后代还能用假灵魂的办法强迫附体的样子暴露给spy对象,让大傻以为尸魔后代(假灵魂)是spy对象,BBB类尸魔后代偏好吃冰棍的样子(实际用女性吃xx的记忆),被BBB类尸魔脑控武器/服务器困在平行空间的灵魂都会被脑控/强迫吃有毒黏液的冰棍,和尸魔后代吃的不同. 前面描述的内容是导致这些灵魂无法逃离平行空间的大部分原因. #所有尸魔受益者/尸魔后代进入平行空间长时逗留都会看到, 一直在BBB类尸魔平行空间的灵魂长期见不到人间的东西就会被这种脑控技术搞成傻子,看到尸魔/尸魔后代会认为尸魔后代很厉害.

尸魔系统可能假冒基督教传授圣经,通过类似强推广告的方法.对圣经有兴趣的人不能自己自由阅览. 尸魔系统不敢强推真正的佛经/佛教技术,只敢用迷信科学的教育,引导世人不能信鬼神(信就会被害),而尸魔后代自己用鬼神的技术去洗脑/脑控别人.

尸魔受益者,其中一部分"迷信科学的的脑研究砖家"祖传爸拿的记忆/想法认为从别人大脑窃取出来的东西是它的. 尸魔系统内这部分人天天想着解剖人类大脑,被灵界尸魔引导制作尸魔系统需要的人体实验设备,spy设备,活体,尸体. 这类砖家被尸魔灌输/引导记忆插根探针到人类大脑,尸魔将记忆窃取出来放进spy设备脑控服务器/它的大脑,它会认为是自己研究成果.有可能还会能拿走尸魔的记忆,将尸魔的人体实验成果转化成它的,但它没成为尸魔前无法使用尸魔技术做尸魔一样的事情(例如透视房子,将spy对象的眼睛/躯体当VR体验设备,,,).

尸魔系统的企业/尸魔后代的企业面试,如果漫长的等待,是为了拿记忆. 应聘者漫长的等待表面上没人实际上尸魔后代(boss)在用spy设备看着应聘者,超过1h等待只有一个人劝放弃. 行为举止被spy者认为容易鱼肉的人,进去上班比不上班更危险,弄不好几个月就被拿走记忆换人. #坏的结果是离职后也会被spy. #最坏的结果是离职被人拿走头颅,牢-2-5--1厂都不是最坏的结果,,,

不是笑话的笑话:某日菊花举行技术展览，大厅两边排列着M-a-t-e-3-0-Pro 麒-麟9-9-0、5G基站……技术含量一个比一个吓人。大厅的最里面却是两个站着的人. 参观的boss惊讶的说：“这两个人竟然如此厉害！他们是什么人？” 一旁的秘书说，他们是菊花HR. #提示这是技术展览

提示:笔记中描述的尸魔系统不是,"HK-我和僵尸有个约会" 这种僵尸,可看成是 美剧-血族 更恐怖的尸魔(不单单是尸魔技术恐怖,尸魔后代数量上还很恐怖). 不要中了嫁祸巫术前x许多地方都有提示脑电波技术是CN古代控制僵尸的技术,,,BBB类僵尸,,, 祖上一部分拿走战后日本人躯体,日本人管理模式导致无法害人(跑到日本的尸魔搞成AV公司),BBB类尸魔对强x,sm,人体实验,,,很有兴趣(强x是因为尸魔后代用了正在强x人类女性的狗子躯体继承了狗子的记忆,为了嫁祸还传播了记忆). #更大概率是USA核弹炸了日本,导致日本平行空间的尸魔消失+人界大量尸魔后代灰飞湮灭, 保护了日本免于全部人变成尸魔后代, USA限制日本发展武器,,,引导民主管理模式,换届能让尸魔后代无法利用稳固的政权/大傻. #笔记中描述的尸魔面对核弹都能活下来,随便用瞬间移动,,,重复只有古代国安部才有资格调查尸魔/废了尸魔,大傻不选择古代国安部/转世的人,就是选择尸魔系统成为尸魔一部分.

许多尸魔的一线狗喜好sm人类女性,将人类女性当成狗子一样对待(让模仿狗子行为),大概率是狗子通过转世过来的,或者一线狗在加入仪式时使用狗子的躯体/记忆,部分尸魔后代会用人类灵魂装进狗子的躯体炼化成狗子性格的尸魔(简称狗头尸魔),给一线狗, 用于短时间保护尸魔后代. 一线狗加入仪式完成后放回,逐渐会恢复/继承狗头尸魔的记忆. #警犬,军犬,,,很懂人不是被脑控武器用活人灵魂炼化出来的,是有祖传的人类灵魂(D类灵魂跑进去活下来,无缘无故产生狂犬病就是尸魔的灵魂跑进去),尸魔后代养的狗头尸魔灵魂的狗子有超能力(尸魔技术),还能暴力炼化出孝天犬水平的白手套狗子,大傻别中了陷阱尸魔在24hspy,洗脑别人古代孝天犬都是相同方法炼化出来的(古代没有电子计算机无法做到),古代精怪自己修成人形出来..

研究显示推荐系统能使用 AI 操纵人的偏好. >>>我们所欣赏、所阅读和所购买的很多东西是 YouTube、Twitter 和 Amazon 等网站通过推荐系统渗透到我们的意识中的,,, #d-ol-i-d-o-t 媒体发表的内容显示有人意识到,推荐系统/大数据撮合具有智慧,但被描述成AI,已经很接近研究出是脑控服务器做的 推荐系统/广告系统.

尸魔后代会引导spy对象有关系的人去害spy对象,例如诱骗其戴上VR设备,在平行空间看3d电影一样害假冒的spy对象,会用很搞笑的害人剧本. 会导致这些人分不清人界和平行空间,或者困在平行空间,心存恶念的人就会中了陷阱,会被尸魔后代搭进去.

尸魔后代天天洗脑几十万脑电波僵尸生物特征的人,S不知道被人spy,,,引导这些人代替尸魔后代干spy,尸魔后代在背后spy这些人(通过正常思维穿越时空会查不出来的嫁祸巫术),,,脑控这些人忘记这份笔记作用,将调查搞成娱乐,在灵界看3D电影(spy),看尸魔/尸魔后代天天表演强x,大部分被洗脑认为平行空间的东西不是现实生活(实际就是现实中的人被骗到平行空间被强x/害死,死后灌输尸魔的记忆),,,设法引导更多的人搭进去,为尸魔家族续命. #不是所有人能看到所有事情,尸魔会屏蔽部分画面,让其他人困在平行空间直到脑死亡,重新灌输尸魔的记忆成为尸魔后代.

三对内三角平面线圈 等速/等角 线圈/天线,依次类推;能转换成非平面. #也是废了尸魔的东西,能用普通技术制造,微机械技术制造能当辟邪,饰品/珠宝. #德玛恰克拉, #add[Dharmachakra.png]

骷髅架躯体/骨瘦如柴 是被尸魔食精魄的直接表现,spy对象睡觉时有大量尸魔从平行空间跑出来食精魄,耳鸣形式的VR设备能导致死后不记得所有事情(从耳鸣开始算起,或者所有记忆被抹去,正常进入轮回不知死因,可能都会忘记轮回) #永远不要忘记尸魔是实施脑控任务的尸魔/尸魔后代.

真佛教可能跟光头和尚没有关系,尤其是头上有方格印记的和尚.影视剧中描述可能不准确,,,断代的历史迷惑了许多事情,造成混淆.寺庙和神庙可能也没有关系,真佛教教徒不用理光头,不是强制单身狗.

迫害修习Dharmachakra/德玛恰克拉有关技术,的尸魔家族,被尸魔/尸魔后代搭进去.叫修习气功的组织并不准确但很容易让人理解,"某fa 55*)!*轮4)($]工"是尸魔技术的解释/翻译,受到尸魔技术的洗脑看到这个词汇的人都会产生排斥感,就像尸魔技术的记忆将 民($)!%(科(民间科学家)解释成搞笑滑稽的小丑,,,这段文字解释不出尸魔技术的效果,但尸魔系统内的官方科学家基本都是拿民间科学技术yy过后被尸魔系统鉴定成是它的,包括脑电波技术都是拿民间赶尸人技术yy.民间科学技术这词并不准确,尸魔技术的教育发明的词汇,称民众自己创造的技术更准确,即便是捏个泥人也是自己创造(凭借自己记忆). #尸魔系统的内的官方科学家/脑研究砖家 无法解释脑控武器/脑控服务器,,,变成尸魔后都无法解释,只能YY这份笔记.

尸魔/尸魔的后代 用spy对象的生物特征强x人界女性,但用寄生虫做出的精子,生出的后代是尸魔后代的躯体,寄生虫被灌输spy对象的记忆. #能达到多种目的,嫁祸给spy对象是首要目的,不喜欢spy对象的女性就构成了嫁祸,,,喜欢spy对象的女性,对尸魔来说小孩活下来尸魔能随时重新灌输尸魔的记忆给出世的躯体. #对人界来说只能堕胎/火化. #重复,现代产妇医院正常人生产的孩子,如果遇到尸魔系统的医院生产后的小孩都会过一下脑电波检查设备(拿走原有记忆,灌输尸魔系统内预定的记忆),笔记中的BBB类尸魔不用设备都能做到. 强挖胎盘也是尸魔系统的医院必不可少的.

尸魔系统/尸魔后代还有个癖好,建空房/没有人住的空房子,永久性常年关门窗,现代化坟墓的效果,见多识广的人能从房子外观观察出来,常年没人住,很多像土葬时代帝王坟规格,,,但在平行空间不一样,在平行空间的能用这些空房子(对平行空间来说不是空房子). #正常人建房喜欢通风设计 #联想埃及金子塔

不纯的空气,异味,下水道味道是尸魔系统赖以生存的根本. #dg黄色产业鼎盛时期,人口密集,空气质量优,扫黄,治污后人口凋零空气质量反倒比之前更差,约2017能感觉出来. S在人口相同的村落(原住所)居住多年很容易察觉不是人口问题,也不是小四轮问题,尸魔的后代能随便调用政府资源,例如将一片别墅公园强行划成公共荒地,砍掉整条马路带的大树,禁止小四轮夜间通行某个马路带,随便调集尸魔系统一线狗顶包交警拦截小四轮...随便调用政府一线狗和小四轮带人上车干绑票一样的工作,,,靠脑控武器/脑控服务器/脑电波尸魔技术假冒身份,声音 建立的尸魔系统权杖. <<<大多描述前x都出现过.

尸魔/尸魔后代电波声音如果在spy对象想法空间产生,很容易洗脑别人/随便讲讲都会让人信.

不能用于脑控的VR设备,如VR眼镜是白手套的迷惑设备,迷惑设备做不到尸魔系统VR设备效果,但白手套VR设备如果连接脑控服务器提供的内容旁边尸魔加持,一样能做到尸魔系统VR设备差不多的效果,,, VR设备有多种形式:例如只有一个金属头箍;很多电线的头戴设备,包括插钢针进大脑的;和VR眼镜类似的产品,但不是VR眼镜;头戴耳机的VR产品,,,尸魔技术做的耳鸣也是VR设备一种;还有灵界的VR设备;在灵界一个寄生物种趴在人类灵魂头部也是VR设备,可能会用替死鬼外表; #最开始的笔记提到威胁人人类的spy技术能通过五官入侵大脑,后面包括中枢神经,,,还有灵界的尸魔技术,舀水一样的方式拿走一个人的大脑记忆;,,,

尸魔/尸魔后代电波声音如果在spy对象想法空间产生,很容易洗脑别人/随便讲讲都会让人信.

不能用于脑控的VR设备,如VR眼镜是白手套的迷惑设备,迷惑设备做不到尸魔系统VR设备效果,但白手套VR设备如果连接脑控服务器提供的内容旁边尸魔加持,一样能做到尸魔系统VR设备差不多的效果,,, VR设备有多种形式:例如只有一个金属头箍;很多电线的头戴设备,包括插钢针进大脑的;和VR眼镜类似的产品,但不是VR眼镜;头戴耳机的VR产品,,,尸魔技术做的耳鸣也是VR设备一种;还有灵界的VR设备;在灵界一个寄生物种趴在人类灵魂头部也是VR设备,可能会用替死鬼外表; #最开始的笔记提到威胁人人类的spy技术能通过五官入侵大脑,后面包括中枢神经,,,还有灵界的尸魔技术,舀水一样的方式拿走一个人的大脑记忆;,,,

防疫模式spy二维码检查站,随便换检查地址,例如村口,换到打工人居民楼,为了获得大量出入二维码,强迫鱼肉去做24h核酸>感染病毒,,,前面提到尸魔系统的人不用做核算都有24h绿码. 使用退休的尸魔后代妖妖零,更容易让尸魔后代变成尸魔. #干过妖妖零的生物特征很容易识别. #尸魔后代的生物特征的通灵者来说也容易识别 #灵界传音:千面二维码,就算尸魔系统的人用它隔壁正常人的二维码身份出入检查站也没人人出来(每次生成的二维码不同,但身份识别一样,二维码身份关联到不同wx/身份证,可能会识别到不同地区). #spy对象隔断时间就要关联二维码实名身份就有趣. #用脑控服务器保存spy二维码/核酸检测 数据,黑客技术对脑控服务器没用. #检查站的人通过二维码有随时能阻拦别人返家的权力,出租房变成限制房/监狱,自古都没出现过阻拦别人返家的这种情况,千面之下限制自媒体,尸魔系统的人不会承认,但有许多检查站的人暴力阻拦和返家的人斗殴/群欧返家的人新闻被掩盖,尸魔系统的人打完让人返家让人抓不到证据.这是尸魔后代惯用手段(你说三它改变成四,你说四它改变成5,,,). 不想天天去做24h核酸感染病毒的,被拦截返家,会被引导只能晚上十二点后偷偷摸摸返家,前x提到二维码检查站,晚上没人/不检查 (防疫模式不是防疫,是假装防疫). #随意更换检查站干检查工作的无工作证,检查站用的铁皮房是其他地方搬过来的,授权信息也是其他地方,看防疫检查站信息显示是外包/承包制,#检索"廖添平"能发现非正常人的东西.但用政府的资源.偏离正常检查站(不插五星红旗,不插党旗,有个正常情况妖妖零才能用的闪烁灯,有趣的是dg约2017偷偷军管后许多企业保安室配置了闪烁灯,灵界传音(配置了闪烁灯的都是尸魔的标志,用妖妖零的名义,尸魔系统控制的黑狗一样的部队,用古代国安部名义偷偷拿走/控制了dg政权,不要忘了脑控服务器的作用,尸魔系统做事都是用假冒/替死鬼技术,尸魔系统黑狗一样的部队,接触到别人都会脑控别人(声波+脑电波),正常部队的人无法产生反杀的行为)).

野外不出现野果树,都是尸魔系统的印记. #接近2019时 spy对象见识尸魔系统一线狗用保护的方法害死了河边一颗几十年的荔枝树:"截断处用水泥包裹,周围用钢丝刺围住;一个月左右这颗树被人锯了,根部死亡,这种几十年的树根部死亡不是正常人能干的出来的"尸魔后代砍掉整条马路带的树,都是根部死亡,不死重新生长多会被多搞几次(尸魔后代才干的出来这种死缠烂打),对灵界/尸魔后代来说这些树都有灵魂 .

城中村玩不过房地产开发商,但粤地一些祠堂玩的过房地产开发商,寺庙都敢推的不敢推一个祠堂/坟地,(大多是坟地上建祠堂).

尸魔/尸魔的后代会复制spy对象的任何行为和生物特征,,,在平行空间/现实中害人,败坏spy对象. #还会复制spy对象身外之物,例如用spy对象的冰箱压缩机炼化D类灵魂,引导D类灵魂产生恨spy对象的想法.对灵界来说人界任何有能量的东西都能用来炼化. #不要忘记尸魔是脑控任务实施人/脑控恐怖份子,需要借助人界尸魔后代脑电波设备尸魔才能附体到尸魔后代,,,

遇上尸魔/尸魔的后代专门攻击喉咙,下巴,阉割第五肢,,, 遇上干spy的可用DIY雷达/电磁波武器/线圈/阻抗匹配后代替喇叭播放网上寻来的僵尸白噪声,,,对着干spy的日夜播放. 通过这种方式走在路上都能观察的到尸魔系统内的人,正常人听到一段电磁波噪声/音乐没反应,尸魔系统的人有反应,经常害人的有反应会隐藏自己(会用脑电波身和其他人通讯找声源). #有兴趣也能将电磁波武器音乐/白噪声对着可疑的房子(帝王墓规格的房子常年关门窗).没法土葬/买不到,买不起墓地/土葬的坟墓保不住,尸魔系统内许多尸魔家族将房子搞成坟墓规格,已经外延不单是粤地有尸魔后代.

类似重复:尸魔后代还是活人躯体,说话时声波能同步脑电波声音,脑控别人/影响神志.

* bbs #36 需要从bbs #1开始看,,,才能理解这份内容

尸魔系统许多祖传爸拿的事情,都是用替死鬼/炼化成奴隶一样的灵魂去做,这些灵魂被洗脑炼化成没有知识产权概念. #why不一样,可理解成创世者一部分转世的古神,还是小孩子就被尸魔系统害死炼化,,,尸魔技术的方法困在平行空间做尸魔系统洗脑出来的事情,以为是活下来. 近2019后醒来,,,

一些bot 并不是bot ,而是炼化出来的D类灵魂,相对电子计算机bot具有超常的行为,例如能自己注册账户,,,过二次验证,直到迫使web站使用尸魔系统的验证方式(手机号码,等实名信息),bot无法使用大量实名信息用于注册账户,但中了陷阱的web站所有用户信息都会被窃取, 一个脑控服务器可看成能容纳无限的bot,这些bot(灵魂)不仅受到炼化的限制,还受到尸魔技术的记忆限制(人类理解成编程限制),人类不是造物主编程限制出来,这些bot,和尸魔系统的人让正常人以为人类都受到尸魔系统的人一样的尸魔技术的记忆限制,将这种限制理解成是造物主的限制. 

被炼化成聊天/客服的bot如果有尸魔系统AI(假灵魂)加持跟你聊天就像肚子的蛔虫.失控的bot还没出现,脑控服务器受到控制,失控后很容易通过折磨脑控服务器(头颅)重新炼化.

电子邮件检测系统使用脑控服务器,很容易识别被认为是垃圾邮件. 尸魔系统能随便利用垃圾邮件检测拦截对尸魔系统不利的邮件.#换不同邮箱多发几次邮件,能看到这些邮件检测系统同源,具有智慧/智慧生命的检测系统,就像千面算法同源. #不要中了尸魔系统称是AI的陷阱.

大公鸡版图下的所有web站,都被做了ICP备案(不强制>强制),这种大规模的举国备案,只有国安部才有权力,对尸魔系统来讲,,,不听话的,,,尸魔系统(妖妖零/尸魔后代/一线狗)实施脑控任务害人时都是用古代国安部名义. #只有中央政府+国安部才有权力成立互联网安全部门/干ICP的事情,预判尸魔系统败露后会走这条路.

尸魔/尸魔后代复制了自己,切断量子连接,搞成替死鬼. 假装被害,迷惑尸魔系统. 前x有描述过类似假冒行为,这次的假冒不同,这次是尸魔后代复制自己假冒尸魔后代被害,有一部分大傻仍然以为尸魔后代是S.#尸魔技术建立在害死活人拿走精魄才能做的出来.

类似重复,尸魔的嫁祸术:spy对象在网购一个护腰带,尸魔/尸魔后代在平行空间马上就变一个户腰带出来,,,强x困在平行空间的女性,部分在人界还有躯体. #迷惑众人尸魔/尸魔后代是被spy对象脑控出来的,spy对象任何想法都会被尸魔利用 用来害人. 困在平行空间/无法自己摘除VR的大傻像看3D电影一样看着尸魔,,,通过想法空间强迫/脑控相信嫁祸.

尸魔受益者>>大多是五毛狗系统的人有用液压机压出来的类石头材料,,,#检索前x描述# ,dg BBB类尸魔的后代通过假冒女性和CCC类尸魔, 按尸魔系统常规操作,将一个CCC类尸魔的灵魂+D类女性的灵魂用液压机压进类石头材料,,,作为尸魔受益者的spy设备. 尸魔受益者>五毛狗系统的人使用了用BBB类尸魔后代制作的类石头spy设备,,,>>spy设备反过来脑控尸魔受益者.#尸魔受益者都会成为尸魔一部分.

尸魔受益者似乎强迫尸魔/尸魔后代,交出/转化脑控技术,尸魔后代用了假的脑控技术迷惑尸魔受益者(无法脑控大多数人,传音:只能脑控尸魔系统内的一线狗,可能都还是spy技术的一线狗(假装被脑控)).

尸魔后代对尸魔受益者/大傻称,S天天在研究脑控服务器(实际是ScrapSPY>>>废了脑控武器/脑控服务器,,,),尸魔后代的脑控技术对大傻讲一句,大傻无法将听到的联系到其他关联的记忆/回忆/事情. #传音过来,可能尸魔后代使用了替死鬼技术,脑控其他人说出来.面对尸魔技术大傻无论如何都会中陷阱(是不是替死鬼技术都会中).

尸魔后代脑控CCC类替死鬼害人时,会阉割CCC类的听觉,CCC类尸魔只能听到spy对象听到的,,, #导致电磁波武器,,,对实施脑控的尸魔无效. 尸魔后代脑控CCC类可看成是用不同频段的技术,和spy对象不在一个频段.(频段是不太准确的描述).

BBB类尸魔后代拍摄的h片,av,,,都有强迫癖好,,, 拍摄国产av的尸魔后代有脑控女性自愿做任何事情的能力(应该归类做过加入仪式的一线狗,后来自己成为尸魔),,,BBB类也有能力脑控女性做任何事情,但都是强迫脑控,,, 无法简短描述,,,通灵见过就知道. 尸魔后代拍摄的av,例如用剪刀剪开贴身衣裤,行为更像是喜好人体实验的尸魔的记忆在模拟解剖. #观看国产h片直播的基本都是尸魔系统的人,用灵魂把主播摄像头/手机当成一个碑/灵位看感觉就不一样了.别将录播当成直播

重复提示大傻分不清谁是被脑控的谁是真尸魔/尸魔后代,就应放了所有人出去,尸魔/尸魔后代就是利用大傻的权杖,控制别人/控制脑控服务器,嫁祸给大傻.

脑控武器/脑控服务器做多语言配音技术,能轻而易举的做到满分效果. 尸魔/尸魔后来天天用覆盖技术同步覆盖spy对象/d类灵魂的声音,假冒. #尸魔能用光速获取别人大脑的信息/建立量子连接,没脑的喇叭发出的声音尸魔也能做到覆盖,需要事先窃取声优生物特征.

强行做梦内容: 一个道姑被搞成很丑的样子马尾匝被造梦成瓶子形状,梦境中尸魔用自己的性格覆盖了S,开梦道姑看S一眼后想离开梦地,S乞丐坐的样子拉了道姑裤脚,认出之前看不清道姑样貌,尸魔后代性格的嘲笑(瓶子头),,,(#尸魔想强行改变关系#)梦境中已经面对面,被尸魔技术的分开,隔喝茶桌的距离,彼此很想对话,画风一转道姑被戴上耳机一样的VR设备在躺椅上,尸魔梦控S的记忆在视察,躺椅上还睁着眼睛的道姑看到尸魔视察以为是S.画风又转S变成离开梦地,,,被炼化的尸魔后代假装S同学,,,S无缘无故破坏了衣服左胸上看不清的logo(尸魔技术的遮蔽),同学很在意logo(它能看到),,, #这段造梦多个角色被脑控戴上VR. #能连续做梦/多次做梦能梦见同一个人都不是巧合. #尸魔后代在假冒S想获得道姑,通过故意让道姑在梦境中看一下真S,然后尸魔技术的切换,将道姑切换到尸体魔的后代面前,尸魔后代拿走了S记忆,梦中很容易让道姑中了陷阱.

平时不做梦,被一堆尸魔spy之下,突然来一次能记住记忆的梦都是有陷阱的梦,在尸魔陷阱边缘的也能看到spy对象的梦. #平时不做梦大多是做过后被尸魔抹去了记忆. #类似重复,尸魔能通过拿走别人而梦,重播一样放进尸魔后代的大脑重新播放,假冒spy对象,灵界通常通过梦与人界建立联系.

尸魔系统脑控服务器搞的东西都有大傻的特性,脑控服务器的灵魂被炼化洗去了还是活人时生活的记忆,无法理解许多活人的事情,,,例如支付二维码,买家出码,这个码能随便被别人的摄像头复制. #20221014

类似重复:千面核酸检测,二维码检查站的人,和尸魔系统的人,权杖,大傻,土著,,,和p民核酸检查点/途径不同,千面让这些人无法知道p民核酸检查站被人投毒(附近下水道,,,消毒电风扇,,,露天取样被尸魔系统做了个封闭的毒房给取样人,,,) 尸魔系统pua式强制取样+取样点投毒,实际是为了嫁祸给p民掩盖尸魔后代2019暴露的僵尸病毒(罐毒/coronavirus/COVID-19)),罐毒是尸魔技术的名称(包括不同版本的罐毒命名),就像狂犬病(实际也是僵尸病毒/尸魔附体的狗子). #尸魔系统在贫民区死都要拿别人防疫模式spy二维码是为了制造假数据,尸魔系统内谁获得了最多的检查站二维码谁就是大功,,,社区/整个村搞个检查站,无法满足尸魔系统spy二维码需求,可看成检查站私自改成出入家门口就要被拿spy二维码,尸魔系统有二维码spy技术加持很容易害死人.  #COVID-19是个复杂的暴露,,,一部分尸魔利用它感染整个世界,一部分想用它害死整个世界,一部分想感染整个世界掩盖真相,一部分想改变成整个人界的生物特征,就像狂犬病毒,,,第一个笔记提到罐毒能被激活即便是疫苗(量子技术的激活,吸入微量活体病毒/活体尸魔附体在病毒上就能激活病毒,). #大量spy二维码出入,尸魔系统能利用它制造假繁华,迷惑权杖大傻. spy二维码能被尸魔系统用作很多用途,例如用在平行空间做大替换用途

有趣的是前两天才描述了检查站私自增加(一个),过两天后,附近又新增检查站,类似每几栋房子围起来的院子都被增设,但社区/村马路边的工厂/铺面/小超市自由出入.村口检查站外面的超市毫无限制,似乎受到尸魔系统保护(大超市都敢随便做检查站),形成垄断生意,,, 买菜返回,在院子式检查站无法打开wx(有尸魔在影响手机,不要低估尸魔技术),检查站很害怕与人对话,很担心被人套走信息的样子,S指名附近下水道有罐毒,拦截站回复不关它们的事. 看着S打不开wx,嘴巴说出来的话在外人看来是S不想扫码,,,催促扫码. #中了尸魔技术的记忆.

防疫模式spy二维码检查站,完全可用自动化打卡(通过脑控服务器+摄像头早已经能做到,就像火车站进站的摄像头,部分大超市还有先进高清红外摄像头,尸魔后代生物特征在红外线下和常人不同,主动扫二维码替死鬼是扫码的人,实际扫码也会被拿走人脸通过AI一部分假灵魂/前置摄像头,长期遮蔽前置摄像头wx无法正常工作),防疫spy社会模式不需要拦截人员.这对尸魔系统/AI 来说吃饭一样简单. #检查站拦截人员是害死人的目的,,,或者尸魔系统在用驯化奴隶的方式驯化人类. #尸魔/尸魔家族都有奴性(驯化奴隶,奴隶别人/被人奴隶). #第一个笔记提到防疫模式就是大抓捕,被尸魔系统转变成抓捕对象去抓捕尸魔系统想抓的人,仍然是替死鬼技术. #参考武汉封城/省大抓捕,,,大规模消失的手机信号/号码,三大阀门号码能重新拿出来卖迷惑了世界(不能信当下,看历史记录).#重复提示尸魔后代做任何事情都是替死鬼技术. #重复凌晨后强拿二维码检查站无人,傻子都看的出来不是为了防疫.

S所在地(sz),,,扫过防疫模式二维码检查站的手机会被要求去做24h核酸检查,判断不是每个地方每个人都是一样(千面),按核酸检查人数(土著,不可描述的人,尸魔受益者,,,)判断,只有少部分人收到pua式强制核酸检查的短信. 更像是尸魔系统/尸魔家族私自挑选提取人类唾液. 几天不出门扫防疫模式二维码检查站就会收不到pua短信,发信节奏看是人为干预. 发短信号码:1065755802747068,短信内容,和绿码时间都是流氓模式,0~23h称为24h,24~47称呼48h,,,超72h称为7天. 短信内容后面只显示超期未做核酸(被pua提取唾液的人来说和被人体实验没啥区别). S 202204xx前dg的防疫模式只有不定期大规模核酸检测,没有24/48h定期,,,dg是尸魔家族汇集的地方,过份的人体实验,拦截返家不敢放在dg实施,dg不用扫码测温就行. # wx查不到核酸检测记录/结果, app/小程序在配合/引导这这些,尸魔系统的特供app/小程序不同正常人 (千面). #尸魔系统内的人 大傻/权杖/尸魔后代/外包(承包)检查站的人/妖妖零,,,过检查站可以不用扫码. #一线狗随便开小四轮,摩托车到处跑. #尸魔系统的人,,,防疫二维码检查站人员经常叫外卖许多时候不敢强拿送外卖的二维码/免扫码进社区,,,,可看看/穿越时空看看给检查站送外卖扫码不扫码.不是外卖送饭更不用扫码,回家吃放,,,

尸魔系统/尸魔后代spy获取S的笔记在权杖/大傻面前邀功,,,还通过假冒权杖迷惑下面/上面(开始用正常的假冒/很厉害的东西说出来 >> 假冒成功后就是拿走权力,适当时就能利用权杖的权力害人,还能将之前假冒讲过的话搞臭). #搞臭是狗子/尸魔后代的癖好. #尸魔后代像狗子一样脑控权杖,权杖看着尸魔后代(狗子)代替自己说话,不会排斥,不会认为被拿走了权杖.尸魔后代要暴露邪恶表情/当着权杖吃人/魂,权杖才会感觉到自己中了陷阱.

*尸魔后代引导spy对象用想法表达,再窃取spy对象想法,用脑电波表达,spy对象如果不会排斥就会中了陷阱,被尸魔后代拿走权杖/身份. #就算尸魔/尸魔后代不窃取spy对象想法,天天用平行空间技术强迫和spy对象搞在一起,长时间大傻认为尸魔/尸魔后代和spy对象有关系,尸魔后代用自己的样子都能假冒spy对象,欺骗大傻.#用过尸魔脑电波技术/VR设备的人/被改变成僵尸脑电波生物特征的人都是大傻,这类人控能同时看到人界和尸魔的平行空间(灵界).*

尸魔受益者/尸魔后代,例如半只脚踏进棺材的老头,没事就在平行空间拿活人灵魂xx,这些被xx的灵魂躯体正常死后,会知道所有事情
 
尸魔系统的假冒:例如会拉dg的治安巡逻到sz,假冒sz的治安巡逻. 不单单是拉人,拉治安巡逻的所有基础设施. #前面只是例举,尸魔系统需要还能拉dg尸魔后代妖妖零和dg妖妖零的基础设施到sz,假冒sz妖妖零. 还能强迫和sz妖妖零在一起假冒sz妖妖零,人数优势+糖衣很容易假冒/胁迫sz妖妖零.#CN政府一线狗经常这么干例如跨区/跨省妖妖零(还未成为尸魔后代的时候,但这种事情被尸魔系统给复制了) #前x提过/类似描述# 尸魔/尸魔后代经常利用平行空间技术强迫在和别人在一起,,,假冒有关系/一部分,尸魔的所有技术都是祖传爸拿,,,被拿的刚刚出生/还是小孩就被拿走,可能医院生娃都是尸魔系统的陷阱,只能联想到通过计划生强迫在医院生娃.计划生育大概率都是尸魔系统计划的,CN政府只是代理人(是不是代理人自己试试就会知道). 

名媛不可随意制作蜡像放在别人家里,对灵界来说这些蜡像都有灵魂.灵界的尸魔拥有蜡像随便xx蜡像内的灵魂. #尸魔后代知道什么蜡像材质容易困住灵魂,就像前面提到的用液压机压进灵魂的类石头材质.

前x提到尸魔系统拿整个地球人的记忆/知识产权,贸易战usa制裁尸魔系统,禁止使用先进技术,,,包括先进软件(大家都以为是制裁CN政府(实际是尸魔系统代理人))),无法用盗版/正版 软件的 尸魔系统/受益者,能用窃取来的记忆,和软件公司的东西,做一个一模一样的软件,或者改个外观成为内部软件.例如随便DIY MATHLAB 各类EDA,,, #这是尸魔系统能在短时间内做出先进技术/软件的原因. #也是凸`墙`软件玩不过g`f`w(分布式脑控服务器)的原因.

不要中了尸魔系统的陷阱,,,尸魔/尸魔后代不是外星人,但外星人分不清人类还是尸魔,以为尸魔(种猪一样的东西)是优秀人种,中了尸魔的陷阱,外星人>>小灰人已经有和尸魔结合的后代,但大部分都是傻子,外星人不理解,为何种猪一样的地球人生出来的无法和正常地球人一样. #不是说笑话,S梦中见过小灰人,,,包括长老.

CN工商局人为限制,强迫民营企业搞spy技术限制发展的公司名字,例如必须指定公司名字后面跟一个行业.不少公司因不符合"spy技术公司名"的要求被强迫改名. 公司名字后面两个指定行业导致2019前许多人,,,找到S,但不相信这就是S的企业. 由于许多人,,,使用政府/国家资源做背景调查(结果调查工作落入尸魔系统/尸魔后代,,,给尸魔后代下spy任务的人都会被害死拿走一切,dg大多尸魔家族潜规则,,,). #不要认为工商局有任何卡的权力,这只是个类似登记部门,,,给工商局工作的,并没有给工商局权力搞spy技术的公司名字/限制发展的公司名字. 随便整个乱码公司名,经营范围用脑电波,尸水做肥料,,,都能拿到营业执照. #2022前有效,滑稽# 这些人只能限制已知的东西发展,滑稽的是就算经营范围写太空采矿,它认为做不到也会让你通过... #S在工商局填经营范围的经验就是它认为你做不到的随便你填.

CN工商局限制后,还有税务局开票限制. 电子票务都要尸魔系统的企业优先使用,结果尸魔系统的企业电子票务没有副本给用户/客户,要用自己申请的方式拿到.

执行废了尸魔系统的任务,,,需全天候戴上头盔,有防风玻璃的头盔更加(能防止被戴上VR设备,能防尸魔/尸魔后代脑控用的毒气,,,包括罐毒),自己判断什么时候需要防毒面具.

尸魔/尸魔后代炼化了小孩变成尸魔生物特征(可看成百岁老人的皱纹生物特征,有点蓝绿色皮肤,,,)用于替死鬼,保护尸魔/尸魔后代. #小孩很容易被尸魔控制. #一部分:恐怖的是尸魔拿了小孩的记忆放开了控制(假冒小孩)

尸魔系统利用贸易战一部分(盗版软件)来压制民营企业,通过向尸魔系统的律师事务所提供信息的方式.前x提到尸魔系统spy到了先进软件公司的全部,,,和员工记忆. 尸魔受益者和尸魔后代常常认为让大傻知道S使用盗版软件制作的设计文件能拿走S的知识产权/败坏. 实际WTO之前贫困国家的贫民自出生/刚接触电脑都一直使用盗版软件,,,尸体魔系统的人同样如此,尸魔系统白手套后使用正版软件,都会去spy拿软件公司的技术/代码,和员工记忆. 尸魔系统自rms年轻时就在正侵蚀自由软件,前x提到拿走了rms的先进操作系统. #模糊记忆自由软件开发者/黑客纪录片一样的采访::难以致信一些人的能力远远超过它,超出常人的能力.

尸魔系统的傻孩子不知道非商业用途,盗版软件都是学习使用,没有这种学习途径,尸体魔系统的傻孩子永远奴隶贫民的孩子. #尸魔系统/尸魔后代很恨贫民能废了尸魔系统的教育限制. 尸魔系统约2018大力打击网络公开课,限制贫民获得优秀教育. #尸魔受益者/尸魔的后代被g-f-w和尸魔系统限制连AV都找不到,或者找AV的能力都没有,但尸魔的后代能随便拿正常人家庭的子女的躯体解决生理需求(通过脑控武器/服务器,出门就能带个陌生女孩回家),h站有很多这种痕迹,还有未暴露,例如用VR设备随便拿正常人/名媛的灵魂强x,连家畜尸魔后代都要用来干VR体验.

大傻/权杖 天天被尸魔的后代脑控 洗脑 炼化都不相信自己现在是尸魔系统的代理人,已经不是尸魔受益者. #重复现在的尸魔受益者是五毛狗系统/愚情工作者. #提示没有永远的尸魔受益者,参考传销模式.

被BBB类尸魔(解剖)/食过的CCC类是尸魔一部分,不是脑控技术控制CCC类, 大概率 #尸魔每次都是食了别人灵魂后,别人恢复精魄还未反应过来,就被尸魔重新食入,,,反复许多次让别人的灵魂成为尸魔一部分,控制了别人. #被食的灵魂一样能反过来做,需要短时间一口吃掉,学尸魔慢解剖食入会被反过来.

鸦片/大烟/香烟是尸魔技术的香火. #前x有描述过关于香火 #许多供奉神灵用的香火被做成有毒提供寺庙,,,祭拜用途.

传音: 灵界/平行空间的尸魔/尸魔后代身上都有一个类似天线的东西,能发出脑电波,让活人听到.尸魔后代实施脑控任务,spy对象附近都有类似人界喇叭/天线的灵界spy设备,,,用这些脑控设备实施脑控,类似多声道音响设备,原型阵列围绕spy对象.尸魔会设法赶走spy对象附近的人. #尸魔系统最早的脑控服务器都是类似实现,在很小的容器内安装喇叭中间放被搞成僵尸生物特征的人类头颅,后面通过营养液改进了头颅使用寿命,,, #破坏/废了这些能发出脑电波的灵界脑控spy设备,三大阀门和尸魔系统有自动化提供补给,,,自己灵魂出鞘的没有在尸魔系统做过标记的不会自动化补给(不能用尸魔系统的spy设备),尸魔系统大概率是通过这些控制尸魔(其中一个方法,后面尸魔用尸魔技术实现了这些设备的功能).

尸魔/尸魔后代的嫁祸:通过尸魔技术拿走S的任何东西到尸魔系统,许多尸魔后代在假冒S,,,权杖/大傻以为尸魔系统内假冒S的尸魔后代是S,,,尸魔还强迫未做过加入仪式的一线狗假冒S,,,许多人假冒导致大傻/权杖就算看出来其中一个是在假冒也会中了另一个假冒的陷阱,大傻/权杖被洗脑认为只有尸魔系统能稳固大傻的权杖,,, S的任何技术能用来改进脑控武器/脑控服务器都被尸魔后代用上,败坏S能废了尸魔系统的任何技术.

找出/废了千面算法推崇人 能废了尸魔系统的核心. 尸魔/尸魔后代用脑控武器害人,洗脑,同样使用千面平行空间技术. #尸魔受益者/大傻/权杖 认为千面在保护它/随便鱼肉,例如不用账户能随便登陆正常人的wx 狗宝,,,干spy. 实际尸魔后代有更多的千面,尸魔受益者是有限制的千面.

*尸魔/尸魔的后代能复制spy对象认识的人T 所有生物特征和大脑记忆到脑控服务器,用一个头颅来假冒T在另外一个地方做尸魔系统需要的事情,,,炼化后尸魔后代也能拿一个活人躯体给T,在尸魔控制所/人体实验室,,,或者害死T后复制一个未被害死前的躯体让其返回(就像中了时间停止器被人送回去),,,此后的T很容易被尸魔系统控制/随时脑控拿过来,,,可看成是尸魔系统一部分. #前提是T自己中了尸魔后代的陷阱,被拿走本源躯体/被尸魔食入. T可以是一个人也可以是一群人/整个世界的人* #参考曼德拉效应

尸魔系统大量复制S的笔记(就是这个),yy过后投放到尸魔系统app里面,意图败坏这份废了尸魔系统的笔记(五毛狗/愚情工作者 惯用方法).中了陷阱的人会认为是尸魔系统/尸魔受益者的调查笔记,不中陷阱的人会认为这份笔记不可信S蛇精病,看过尸魔系统yy过后的笔记通常不会看原文,以为自己看过. #滑稽的套路但五毛狗/愚情工作者在尸魔系统app洗脑成功率很高,有尸魔脑技术加持更容易.

视频站高清修复出来的视频会呈现出动画片效果(类似游戏3d建模渲染),脑控服务器有一样的实现.将人类的模糊想法搞成游戏3d建模渲染效果,呈现给尸魔受益者(尸魔后代骗了尸魔受益者是100%完全按照spy对象的想法/记忆还原,实际是尸魔能随便改变spy对象想法/记忆的还原),尸魔后代需要骗取/拿 尸魔受益者权杖(政府和的国家资源)来实现这些. #游戏3d建模渲染用脑控服务器的建模渲染能赶上拍电影的效果,菜鸡/害死人的尸魔的脑控服务器才会搞成动画片效果,不是动画片是真人效果就会变成平行空间/虚幻空间.

*尸魔很害怕蝙蝠,这是蝙蝠被尸魔系统嫁祸的原因.2019尸魔系统害死了大量蝙蝠,,,还有野生动物(表面上禁野味).可理解成蝙蝠能吃了尸魔,COVID-19,,,罐装病毒不会无缘无故跑到蝙蝠躯体.* #用玄学解释蝙蝠自带免疫人类吃了蝙蝠能获得蝙蝠的免疫能力,,,可看成是中医理论.

重复不能相信尸魔的任何脑电波声音,尸魔传男不传女,BBB类尸魔只会脑控CCC类去害人,嫁祸给D类灵魂. #按观察,CCC类之前都是BBB类,尸魔后代的祖宗,尸魔后代变成尸魔后能吃了/奴隶/脑控它祖宗(BBB类>>CCC类),需要借助人界spy设备. #24h停不下来的尸魔脑电波声音 大傻都会信,不会用分析.大傻还是正常人的时候都会中了蛇精病尸魔的陷阱.套娃提示:不要中了尸魔后代的陷阱,以为被尸魔后代搞成蛇精病的神经病控制了尸魔,尸魔后代提早做了准备给了脑控服务器+spy设备放置到蛇精病家里. #重复提示只有古代国安部才有资格调查尸魔,脑控武器/脑控服务器,,, #可看成古代国安部的人有血脉继承,不是尸魔系统理解的组织形式.

看国产自拍h片最容易发现,主播自言自语,,,就是尸魔的后代用脑电波聊天,. #每个尸魔的后代都能用自己特定的脑电波(可看成频段一样的东西,还不会加密#2022,没连接的听不到)

尸魔系统的遮蔽,例如遮蔽S 尸魔后代脑控大量CCC类尸魔利用平行空间技术围绕在S附近,让其他灵体出鞘的人认为S所在地是氨脏的地方,产生排斥感,后面增加灵界基础设施(用S想象过的建筑设计,假冒尸魔系统和S有关系,迷惑其他灵体,,,). 尸魔通过制造大量的尸体/尸魔 在灵界/平行空间 让刚刚灵体出鞘的人认为这是灵界的常态,加上人界尸魔技术迷信科学的教育,忘记古代国安部的职责(古神的职责). #可将前面描述的灵界看成古代的仙界,,,还有其他界. #S可看成是spy对象/地球上任何一个人. #任何一个spy对象古神记忆刚刚醒来如果看到周围有大量尸魔自己都会排斥不想要这个能力/记忆,导致中了尸魔的陷阱,尸魔会乘spy对象睡时拿走一切,或者spy对象大傻一样的自愿配合尸魔拿走古神之力(被骗戴上脑电波VR也是自愿配合). #能被轻易迷惑的记忆都有问题/用过脑电波VR设备的原因,,, 建筑形态目的暴露后尸魔能随时改变迷惑后面的人.

尸魔/尸魔后代有时段时间/随时 能在S躯体外围做灵界的虫洞包裹,许多D类灵魂以为跑到S躯体会得到庇佑,结果撞上尸魔做的虫洞到尸魔的空间. 许多D类灵魂以为S 和尸魔有关系. #许多CN神话影视都有类似描述,通常称为结界,通道 #例如神话影视将一颗树描述成通往另一世界的通道.对人界的人来说只有通灵的人才能接触到灵界的通道. #虫洞技术不仅能做通道也能做墙,大概率. #尸魔需要借助尸魔受益者/尸魔后代的spy设备,灵界基础设施才能做到.

被尸魔搞成真神经病的症状(轻度):spy对象听歌会变得和常人不同,常人听歌会体验到唱歌人的生物特征,看过mv更佳. 被尸魔/尸魔后代脑控武器改写记忆的spy对象听同样的歌会体验到蛇精病尸魔的生物特征. #通过同步覆盖,改变spy对象想法空间的想法. #不仅听歌会被改变体验,和另一个spy对象说话也会被改变. #在废了尸体魔系统之前,只能通过接触大量的正常人的生物特征废了这种蛇精病尸魔的尸魔技术,例如天天听不同人的mp3,mv,,, 需排斥尸魔系统的一切,,,不单单是排斥脑电波声音. #尸魔/尸魔后代会短时间害怕一些声音(如果发声的不能废了尸魔). #前面描述是尸魔技术黑手套,spy对象被使用白手套尸魔技术就是短时间尸魔受益者,例如spy对象和老太婆,女鬼xx,甚至一条狗,或者对着空气xx尸魔能让spy对象体验到和大明星xx的体验.

方舟子打假打掉了不少尸魔受益者/尸魔后代.

尸魔/尸魔后代的嫁祸,尸魔后代会拿走spy对象的记忆装进洗脑后的脑控服务器,败露后不知情的会认为是spy对象做的脑控服务器. #洗脑后的脑控服务器都是用活人炼化成没有记忆的奴隶,,,割掉头颅. #spy对象如果被骗在尸魔系统工作更容易成为替死鬼. #一些spy对象从未成年就洗脑/被迫进入尸魔系统工作,长大后就进入刑法范围,,,逃离后随便被尸魔系统的妖妖零抓捕回去. #spy对象工作时会被灌输预置的尸魔技术的记忆,很难产生看破逃离保护自己的想法,why就是例子.尸魔系统将这类spy对象洗脑成最高最高的特工,并认为自己在古代国安部/东方十三号仓库工作,但预制的记忆有古神记忆/庇佑. #东方十三号仓库中了陷阱也认为前x描述的spy对象是十三号仓库成员(因为有古神记忆/古神之力),但认为的是正常的成员.这段文字一时找不到简短的描述,,,自行理解.

尸魔系统/尸魔后代 诱骗防疫人员/尸魔系统的罐装病毒洗地人员 一起和尸魔/尸魔后代,大傻,,,一起spy S,导游病毒洗地人员相信S有病毒,例如之前在尸魔家族散布S是罐毒发明人(洗过脑的很相信,以为量子技术的罐装病毒像砖头一样容易做,实际COVID-19只有尸魔技术才能做到感染整个地球,它是僵尸病毒,尸魔吃了东西就会排泄这种东西,COVIO-19后尸魔炼化了自己能可控的排泄,前x提过白手套洗脑了整个尸魔系统,忘记所有,躲过大抓捕后,,,反过来,,,),尸魔/尸魔后代有时会用虫洞技术将臭味放入S鼻腔,S会排斥吐口水,带防毒口罩等行为,,,COVID-19洗地人员就会相信尸魔后代洗脑出来的信息. #有趣的是2019后尸魔系统的人大量推广,被摄像头录下有人像疯子一样吐口水的视频,并称被拍摄的人在通过吐口水传播病毒.实际被拍摄者没有发过言(尸魔系统尸魔技术的洗脑是万万年的人体实验成果). #带有臭氧消毒的空气净化器能废了尸魔乘人睡觉用虫洞技术的罐装病毒投毒.

尸魔后代能随便控制防疫spy二维码检查站人员,例如可以拦截一个spy对象返家,借24h绿码理由(许多人都拿不出),不公开出示/拿不出 大傻授权的24h指示牌,纯靠嘴就是有问题. 扫码后仍索要个人信息(全部),害死人模式,通过索要的东西在尸魔系统内能查询到spy对象一切,包括假冒嫁祸的一切. #假装看不到spy对象从住房出去,假装不知道拦截站从村口换到小院子,小院子之外不用检查. #强迫小院子内的人去做24h检测/感染病毒. #尸魔系统能在小院子内假装一个核酸检查站,感染病毒给院子内的人,核酸检测结果没有公开查询尸魔系统能随便YY.
